In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import tqdm
import sys
import os
import pandas as pd
import time

In [3]:
from sentence_transformers import SentenceTransformer

encoding_model = SentenceTransformer("clip-ViT-B-32")

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

CLIPModel LOAD REPORT from: /home/kantz/.cache/huggingface/hub/models--sentence-transformers--clip-ViT-B-32/snapshots/327ab6726d33c0e22f920c83f2ff9e4bd38ca37f/0_CLIPModel
Key                                  | Status     |  |
-------------------------------------+------------+--+-
vision_model.embeddings.position_ids | UNEXPECTED |  |
text_model.embeddings.position_ids   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [4]:
import dotenv
import os

config = dotenv.dotenv_values(".env")
replace_keys = ["JAVA_HOME", "FUSEKI_HOME"]
append_keys = ["PATH"]
for key, value in config.items():
    # append to os.environ
    if key in append_keys:
        os.environ[key] = f"{os.environ.get(key, '')}:{value}"
    elif key in replace_keys:
        os.environ[key] = value

# check and compare values in fuseki log
os.environ["OPENBLAS_NUM_THREADS"] = "4"

In [5]:
sys.path.append("..")

In [6]:
from utils.datasets import DBPedia
from utils.dbs.qlever_native import QleverDBNative
from utils.dbs.fuseki_native import FusekiDBNative
from utils.datasets.base_dataset import QUERY_DIFFICULTY, QUERY_TYPE
from pathlib import Path
import numpy as np
from utils.datasets.base_dataset import DataTensor

2026-04-27 15:53:20,435 - INFO - Loading faiss with AVX512 support.
2026-04-27 15:53:20,439 - INFO - Could not load library with AVX512 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx512'")
2026-04-27 15:53:20,488 - INFO - Loading faiss with AVX2 support.
2026-04-27 15:53:20,489 - INFO - Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2026-04-27 15:53:20,490 - INFO - Loading faiss.
2026-04-27 15:53:20,532 - INFO - Successfully loaded faiss.

In [7]:
dataset = DBPedia(base_dir=Path("../data/dbpedia"))

In [8]:
test_label = "horse on the bow"
test_tensor = DataTensor.from_numpy(encoding_model.encode(test_label))

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [9]:
test_tensor.to_literal().n3()

'"{\\"data\\": [-0.04262268915772438, -0.1333884298801422, 0.08612467348575592, -0.02091798186302185, -0.15041583776474, 0.1737712323665619, -0.348517507314682, -0.9152146577835083, -0.3341490924358368, 0.17787908017635345, 0.05680551752448082, -0.20725640654563904, 0.5095284581184387, 0.18332251906394958, 0.11725624650716782, 0.1168459951877594, 0.20500661432743073, -0.1478302776813507, -0.007135884836316109, 0.4961417019367218, 0.3664361536502838, 0.41410648822784424, -0.04107498377561569, 0.5009220838546753, -0.2138804793357849, -0.23931393027305603, -0.7052134275436401, 0.4793880879878998, -0.17963360249996185, 0.2792432904243469, -0.06826944649219513, 0.0803503543138504, -0.20019735395908356, 0.25140535831451416, -0.16235408186912537, 0.1176009476184845, 0.10282524675130844, 0.20387926697731018, -0.04952261596918106, 0.26974374055862427, 0.13957971334457397, 0.5327335596084595, 0.12486020475625992, -0.08572806417942047, 0.1065823957324028, -0.06904290616512299, 0.19244082272052765, 0.004055921919643879, -0.016175957396626472, 0.14999307692050934, 0.058157339692115784, -0.2949751913547516, -0.30239489674568176, 0.2556452751159668, -0.056346990168094635, 0.0034323800355196, -0.24107672274112701, 0.266265332698822, -0.21348032355308533, 0.401064395904541, 0.2964056432247162, 0.0030471496284008026, 0.0780687928199768, -0.10076116770505905, 0.12922954559326172, -0.0007172836922109127, -0.07724957168102264, 0.15974968671798706, 0.13473500311374664, 0.002694841008633375, 0.043134912848472595, 0.01628531515598297, 0.28354209661483765, -0.022883642464876175, 0.09224116057157516, -0.5340399742126465, -0.23960845172405243, 0.12176563590765, -0.34699109196662903, 0.05000511556863785, 0.062218617647886276, 0.1143401563167572, -0.01417964044958353, 0.5364919304847717, 0.2277376502752304, -0.029826924204826355, -0.34357592463493347, -0.10327602177858353, -0.0889338031411171, 0.36991357803344727, 0.012964829802513123, -0.07436607033014297, -1.309548258781433, 0.44614243507385254, 0.018672700971364975, -0.2529124319553375, 0.28713902831077576, 0.01675035059452057, 0.035857703536748886, -0.22998324036598206, -0.14083877205848694, -0.07106801122426987, -0.09642128646373749, 0.21655051410198212, 0.09358265995979309, 0.23318399488925934, -0.15376906096935272, 0.27460137009620667, -0.21038588881492615, 0.3248600959777832, -0.1732352375984192, 0.014894681051373482, -0.039007216691970825, 0.1811979115009308, -0.31202074885368347, -0.11454087495803833, -0.16019298136234283, -0.08498432487249374, 0.3788904845714569, -0.1883203685283661, -0.07226619124412537, -0.9254443645477295, -0.18329882621765137, -0.06734245270490646, 0.2413122057914734, -0.164064422249794, -0.3879578113555908, -0.2547023594379425, 0.14271141588687897, 0.39550554752349854, -0.13101597130298615, -0.45052370429039, -0.08015789091587067, 4.995395660400391, -0.23945783078670502, -0.37153586745262146, -0.29315686225891113, 0.08353441953659058, 0.10397690534591675, -0.24532519280910492, -0.29608869552612305, 0.0728289932012558, -0.19765496253967285, 0.2663191854953766, 0.1443239003419876, 0.06140514463186264, -0.0636756494641304, -0.136429563164711, -0.37929514050483704, 0.040126048028469086, 0.20846030116081238, -0.046803634613752365, -0.09697604179382324, 0.2885654866695404, -0.13826711475849152, -0.4298671782016754, 0.454520046710968, -0.3830225467681885, -0.2549723982810974, 0.1788555532693863, 0.07007404416799545, 0.14401200413703918, -0.02052035927772522, -0.06321345269680023, 0.14143216609954834, -0.002827470190823078, 0.13198769092559814, -0.4338044226169586, 0.31351831555366516, -0.015382522717118263, 0.03972843289375305, -0.11416905373334885, 0.32447728514671326, -0.08284606039524078, -0.2795880436897278, 0.33499065041542053, -0.13286051154136658, 0.1413523107767105, 0.1438053846359253, 0.4994203448295593, -0.12618792057037354, 0.13858260214328766, -0.1577799767255783, -0.24153682589530945, 0.3336068093776703, 0.11076335608959198, 0.27649617195129395, 0.19507920742034912, -0.3491799235343933, 0.10086368024349213, -0.1947011947631836, 0.14734765887260437, -0.1792561113834381, -0.2404884546995163, -0.20638126134872437, 0.1594625562429428, -0.2064419835805893, 0.4686662256717682, 0.1224103569984436, -0.1929231882095337, -0.3304961621761322, -0.15453074872493744, 0.3289383053779602, -0.19276845455169678, -0.1419120728969574, 0.036372654139995575, -0.032568495720624924, -0.2757578194141388, -0.17087632417678833, -0.3603208363056183, 0.3550761640071869, 0.07408803701400757, 0.16397617757320404, 0.4174465537071228, 0.03409815952181816, 0.015406325459480286, 0.14059369266033173, -0.2836103141307831, 0.04072924703359604, -0.13061843812465668, 0.08163174986839294, -0.24610236287117004, 0.09389635920524597, -0.24005071818828583, 0.13519728183746338, 0.0464361235499382, 0.22132527828216553, 0.02697714976966381, -0.08397431671619415, 0.23355722427368164, 0.07472678273916245, -0.07733243703842163, -0.08717343956232071, -0.056425370275974274, 0.3738686144351959, 0.03457840532064438, 0.3578338623046875, 0.1249217838048935, -0.3770174980163574, -0.02174508571624756, 0.3847891688346863, -0.31229445338249207, 0.24248838424682617, 0.1730431318283081, 0.21590428054332733, 0.028434207662940025, -0.04749997705221176, -0.354280561208725, 0.2951468825340271, 0.03223574534058571, -0.33378469944000244, 0.5995599031448364, 0.16036856174468994, 0.37374818325042725, -0.27309471368789673, 0.47794461250305176, 0.27809959650039673, 0.07505334913730621, 0.04588694125413895, 0.44692400097846985, -0.061994630843400955, -0.01789759285748005, 0.02898450754582882, -0.17852738499641418, -0.270717054605484, 0.05693190172314644, -0.0238601416349411, -0.1925913393497467, -0.3413273096084595, -0.1934177130460739, -0.30758562684059143, -0.2947530746459961, 0.26107990741729736, 0.1175401359796524, -0.0725201964378357, -0.029527168720960617, -0.37710872292518616, 0.06373333930969238, 0.3712431788444519, 0.16918398439884186, -0.1874537318944931, 0.09985712170600891, 0.10260182619094849, 0.20361138880252838, 0.014345571398735046, 0.5188203454017639, 0.16811496019363403, 0.25370705127716064, 0.11705280840396881, -0.05278034880757332, 0.03722261264920235, 0.3069724142551422, -0.3166779577732086, 0.3612406551837921, -0.3461386263370514, 0.14271120727062225, -0.4891326129436493, -0.031868647783994675, -0.2105318009853363, -0.10849712789058685, 0.5024760365486145, -0.42960524559020996, 0.09099404513835907, 0.10781149566173553, -0.08149893581867218, -0.36489272117614746, -0.19751374423503876, 0.4677923619747162, -0.19604173302650452, -0.5108305215835571, 0.04228796809911728, 0.40673041343688965, 4.982846260070801, 0.2281806766986847, 0.07898621261119843, 0.015636280179023743, 0.10525976121425629, -0.24056093394756317, 0.1307922601699829, 0.11874490231275558, 0.16272300481796265, 0.33506906032562256, 0.12341885268688202, 0.23444749414920807, 0.0751492977142334, 0.4529761075973511, -0.09843146800994873, -0.0868949443101883, 0.15630561113357544, -1.9064604043960571, 0.1436811089515686, -0.0647597685456276, 0.10218008607625961, 0.22556403279304504, -0.1312151700258255, 0.08798596262931824, -0.316336065530777, 0.08733700215816498, 0.4364594519138336, -0.0841616541147232, -0.12824013829231262, 0.17684020102024078, 0.0005449578166007996, -0.4466038644313812, 0.2596926987171173, -0.04485166817903519, 0.36150938272476196, 0.29519420862197876, -0.13554643094539642, 0.17567718029022217, -0.04864608496427536, 0.09418146312236786, 0.11930356919765472, -0.1689140498638153, -0.07621348649263382, -0.04019908607006073, 0.025453871116042137, -0.04131506010890007, 0.613564133644104, 0.17166201770305634, 0.19252869486808777, -0.1529507040977478, -0.3212543725967407, 0.29930058121681213, 0.183676615357399, 0.256805956363678, -0.348125159740448, -0.24246308207511902, -0.15343236923217773, 0.045282796025276184, 0.12715944647789001, 0.1002541035413742, 0.3344520628452301, 0.12696677446365356, -0.03679069131612778, 0.08682677894830704, 0.027234166860580444, 0.12669570744037628, -0.14569342136383057, -0.11954189836978912, 0.005335235968232155, -0.023069556802511215, 0.12944917380809784, -0.5794199705123901, 0.4554336667060852, 0.26931557059288025, -0.14136828482151031, 0.16985487937927246, 0.035368259996175766, -0.21738597750663757, -0.19395196437835693, -0.2554394602775574, 0.036201342940330505, 0.0026678694412112236, 0.03341682255268097, -0.00012027658522129059, -0.20584441721439362, -0.2441178858280182, -0.29085585474967957, 0.6269326210021973, -0.07581208646297455, 0.01799778640270233, 0.26985567808151245, -0.18378271162509918, -0.21640625596046448, 0.07882273197174072, 0.11399638652801514, 0.16782686114311218, 0.1454664021730423, -0.14690759778022766, 0.5914286375045776, -0.06359510123729706, -0.4243270754814148, 0.419055312871933, 0.03688973933458328, 0.09080688655376434, -0.20464570820331573, -0.23673778772354126, 0.12423155456781387, -0.3539251387119293, -0.05117426812648773, -0.33227285742759705, 0.09913495182991028, -0.5108201503753662, 0.2183261215686798, 0.14858272671699524, -0.03194478526711464, -0.2500399053096771, 0.3474576473236084, -0.08445319533348083, 0.05256013572216034, 0.12885384261608124, 0.05474567040801048, 0.28207558393478394, 0.24913564324378967, 0.017554350197315216, -0.04651769623160362, -0.21744558215141296, -0.5378966331481934, 0.35821494460105896, 0.02395261451601982, 0.2269265353679657, -0.48503151535987854, -0.4348192811012268, 0.2893373370170593, 0.13147799670696259, 0.30677375197410583, -0.38510605692863464, 0.22093357145786285, 0.26399722695350647, -0.49346867203712463, 0.10722221434116364, 0.004673405550420284, -0.2786339819431305, 0.13793890178203583, -0.049813125282526016, -0.258821964263916, 0.336711049079895, 0.19765441119670868, -0.09453567862510681, 0.01727696880698204, 0.10990896075963974, 0.5079712271690369, 0.18238453567028046, 0.29509949684143066, 0.0021931459195911884, 0.44314414262771606, -0.1369258612394333, 0.03231927752494812, -0.013810236006975174, -0.1325978934764862, -0.40534934401512146, 0.30387064814567566, -0.31678539514541626, -0.06312119215726852, 0.35880550742149353, -0.14602607488632202, 0.23039574921131134, -0.10129227489233017, 0.4284210801124573, -0.21266235411167145, -0.38488680124282837, 0.3961750268936157, -0.13077367842197418, 0.2837107181549072, -0.4066965579986572, -0.28119900822639465, -0.12295553833246231, -0.2169499695301056, -0.1610642671585083, -0.2141464203596115, -0.1797635853290558, -0.17363053560256958, 0.8139917254447937, -0.015077708289027214, -0.19219623506069183, 0.5032162666320801, 0.290952205657959, -0.20581594109535217, 0.22820858657360077, -0.07482161372900009, -0.14803574979305267, -0.345528244972229, 0.3796443045139313, -0.03132491186261177, 0.14449141919612885, -0.19413748383522034, 0.3182498812675476, 0.28465232253074646, -0.015421017073094845, -0.04212811961770058, -0.20381203293800354], \\"type\\": \\"float32\\", \\"shape\\": [512]}"^^<https://w3id.org/rdf-tensor/datatypes#NumericDataTensor>'

In [10]:
db_qlever = QleverDBNative(
    id="qlever",
    base_dir=Path(f"./scratch/{dataset.base_dir.name}"),
    dataset=dataset,
    use_encoded_ttl=True,
    name="QLever",
    port_offset=-100
)
db_no_tensor_idx = QleverDBNative(
    id="qlever",
    base_dir=Path(f"./scratch/{dataset.base_dir.name}"),
    dataset=dataset,
    use_encoded_ttl=True,
    enable_tensor_index=False,
    name="QLever (No Tensor Vocabulary)",
    port_offset=-200
)
db_fuseki = FusekiDBNative(
    id="fuseki",
    base_dir=Path(f"./scratch/{dataset.base_dir.name}"),
    dataset=dataset,
    use_encoded_ttl=True,
    name="Fuseki",
    exec_dir="../../jena-datatensor",
    port_offset=-300
)
possible_queries = db_qlever.get_queries(test_tensor)
print(possible_queries)
dbs: list[QleverDBNative | FusekiDBNative] = [db_qlever, db_no_tensor_idx, db_fuseki]
indices = ["index-encoded", "index-encoded-no-tidx", "fuseki-encoded"]
ids = ["dbpedia-encoded-tidx", "dbpedia-encoded", None]
for db, index, id in zip(dbs, indices, ids):
    db.db_dir = Path("../data/dbpedia") / index
    db.id = id if id is not None else db.id

2026-04-27 15:53:24,502 - WARNING - Killing any existing process using port 25943 before starting the server
2026-04-27 15:53:24,525 - ERROR - Command failed with return code 1
2026-04-27 15:53:24,526 - INFO - Initialized QLeverDBNative with id=qlever, port_id=25943, dataset=DBPedia, name=QLever, use_encoded_ttl=True, endpoint=http://localhost:25943/qlever-with-tidx/sparql
2026-04-27 15:53:24,527 - WARNING - Killing any existing process using port 25844 before starting the server
2026-04-27 15:53:24,547 - ERROR - Command failed with return code 1
2026-04-27 15:53:24,547 - INFO - Initialized QLeverDBNative with id=qlever, port_id=25844, dataset=DBPedia, name=QLever (No Tensor Vocabulary), use_encoded_ttl=True, endpoint=http://localhost:25844/qlever-no-tidx/sparql
2026-04-27 15:53:24,548 - WARNING - Killing any existing process using port 28745 before starting the server
2026-04-27 15:53:24,566 - ERROR - Command failed with return code 1

{<QUERY_DIFFICULTY.EASY: 'easy'>: {<QUERY_TYPE.EMBEDDED: 'embedded'>: '\nPREFIX dbr: <http://dbpedia.org/resource/>\nPREFIX dbo: <http://dbpedia.org/ontology/>\nPREFIX dtf: <https://w3id.org/rdf-tensor/functions#>\nSELECT DISTINCT ?s ?thumb_emb ?dist WHERE {\n    ?s a dbo:Ship ;\n         dbo:thumbnail_embedding ?thumb_emb .\n    BIND(dtf:dotProduct(?thumb_emb, "{\\"data\\": [-0.04262268915772438, -0.1333884298801422, 0.08612467348575592, -0.02091798186302185, -0.15041583776474, 0.1737712323665619, -0.348517507314682, -0.9152146577835083, -0.3341490924358368, 0.17787908017635345, 0.05680551752448082, -0.20725640654563904, 0.5095284581184387, 0.18332251906394958, 0.11725624650716782, 0.1168459951877594, 0.20500661432743073, -0.1478302776813507, -0.007135884836316109, 0.4961417019367218, 0.3664361536502838, 0.41410648822784424, -0.04107498377561569, 0.5009220838546753, -0.2138804793357849, -0.23931393027305603, -0.7052134275436401, 0.4793880879878998, -0.17963360249996185, 0.2792432904243469, -0.06826944649219513, 0.0803503543138504, -0.20019735395908356, 0.25140535831451416, -0.16235408186912537, 0.1176009476184845, 0.10282524675130844, 0.20387926697731018, -0.04952261596918106, 0.26974374055862427, 0.13957971334457397, 0.5327335596084595, 0.12486020475625992, -0.08572806417942047, 0.1065823957324028, -0.06904290616512299, 0.19244082272052765, 0.004055921919643879, -0.016175957396626472, 0.14999307692050934, 0.058157339692115784, -0.2949751913547516, -0.30239489674568176, 0.2556452751159668, -0.056346990168094635, 0.0034323800355196, -0.24107672274112701, 0.266265332698822, -0.21348032355308533, 0.401064395904541, 0.2964056432247162, 0.0030471496284008026, 0.0780687928199768, -0.10076116770505905, 0.12922954559326172, -0.0007172836922109127, -0.07724957168102264, 0.15974968671798706, 0.13473500311374664, 0.002694841008633375, 0.043134912848472595, 0.01628531515598297, 0.28354209661483765, -0.022883642464876175, 0.09224116057157516, -0.5340399742126465, -0.23960845172405243, 0.12176563590765, -0.34699109196662903, 0.05000511556863785, 0.062218617647886276, 0.1143401563167572, -0.01417964044958353, 0.5364919304847717, 0.2277376502752304, -0.029826924204826355, -0.34357592463493347, -0.10327602177858353, -0.0889338031411171, 0.36991357803344727, 0.012964829802513123, -0.07436607033014297, -1.309548258781433, 0.44614243507385254, 0.018672700971364975, -0.2529124319553375, 0.28713902831077576, 0.01675035059452057, 0.035857703536748886, -0.22998324036598206, -0.14083877205848694, -0.07106801122426987, -0.09642128646373749, 0.21655051410198212, 0.09358265995979309, 0.23318399488925934, -0.15376906096935272, 0.27460137009620667, -0.21038588881492615, 0.3248600959777832, -0.1732352375984192, 0.014894681051373482, -0.039007216691970825, 0.1811979115009308, -0.31202074885368347, -0.11454087495803833, -0.16019298136234283, -0.08498432487249374, 0.3788904845714569, -0.1883203685283661, -0.07226619124412537, -0.9254443645477295, -0.18329882621765137, -0.06734245270490646, 0.2413122057914734, -0.164064422249794, -0.3879578113555908, -0.2547023594379425, 0.14271141588687897, 0.39550554752349854, -0.13101597130298615, -0.45052370429039, -0.08015789091587067, 4.995395660400391, -0.23945783078670502, -0.37153586745262146, -0.29315686225891113, 0.08353441953659058, 0.10397690534591675, -0.24532519280910492, -0.29608869552612305, 0.0728289932012558, -0.19765496253967285, 0.2663191854953766, 0.1443239003419876, 0.06140514463186264, -0.0636756494641304, -0.136429563164711, -0.37929514050483704, 0.040126048028469086, 0.20846030116081238, -0.046803634613752365, -0.09697604179382324, 0.2885654866695404, -0.13826711475849152, -0.4298671782016754, 0.454520046710968, -0.3830225467681885, -0.2549723982810974, 0.1788555532693863, 0.07007404416799545, 0.14401200413703918, -0.02052035927772522, -0.06321345269680023, 0.14143216609954834, -0.002827470190823078, 0.13198769092559814, -0.4338044226169586, 0.31351831555366516, -0.015382522717118263, 0.03972843289375305, -0.11416905373334885, 0.32447728514671326, -0.08284606039524078, -0.2795880436897278, 0.33499065041542053, -0.13286051154136658, 0.1413523107767105, 0.1438053846359253, 0.4994203448295593, -0.12618792057037354, 0.13858260214328766, -0.1577799767255783, -0.24153682589530945, 0.3336068093776703, 0.11076335608959198, 0.27649617195129395, 0.19507920742034912, -0.3491799235343933, 0.10086368024349213, -0.1947011947631836, 0.14734765887260437, -0.1792561113834381, -0.2404884546995163, -0.20638126134872437, 0.1594625562429428, -0.2064419835805893, 0.4686662256717682, 0.1224103569984436, -0.1929231882095337, -0.3304961621761322, -0.15453074872493744, 0.3289383053779602, -0.19276845455169678, -0.1419120728969574, 0.036372654139995575, -0.032568495720624924, -0.2757578194141388, -0.17087632417678833, -0.3603208363056183, 0.3550761640071869, 0.07408803701400757, 0.16397617757320404, 0.4174465537071228, 0.03409815952181816, 0.015406325459480286, 0.14059369266033173, -0.2836103141307831, 0.04072924703359604, -0.13061843812465668, 0.08163174986839294, -0.24610236287117004, 0.09389635920524597, -0.24005071818828583, 0.13519728183746338, 0.0464361235499382, 0.22132527828216553, 0.02697714976966381, -0.08397431671619415, 0.23355722427368164, 0.07472678273916245, -0.07733243703842163, -0.08717343956232071, -0.056425370275974274, 0.3738686144351959, 0.03457840532064438, 0.3578338623046875, 0.1249217838048935, -0.3770174980163574, -0.02174508571624756, 0.3847891688346863, -0.31229445338249207, 0.24248838424682617, 0.1730431318283081, 0.21590428054332733, 0.028434207662940025, -0.04749997705221176, -0.354280561208725, 0.2951468825340271, 0.03223574534058571, -0.33378469944000244, 0.5995599031448364, 0.16036856174468994, 0.37374818325042725, -0.27309471368789673, 0.47794461250305176, 0.27809959650039673, 0.07505334913730621, 0.04588694125413895, 0.44692400097846985, -0.061994630843400955, -0.01789759285748005, 0.02898450754582882, -0.17852738499641418, -0.270717054605484, 0.05693190172314644, -0.0238601416349411, -0.1925913393497467, -0.3413273096084595, -0.1934177130460739, -0.30758562684059143, -0.2947530746459961, 0.26107990741729736, 0.1175401359796524, -0.0725201964378357, -0.029527168720960617, -0.37710872292518616, 0.06373333930969238, 0.3712431788444519, 0.16918398439884186, -0.1874537318944931, 0.09985712170600891, 0.10260182619094849, 0.20361138880252838, 0.014345571398735046, 0.5188203454017639, 0.16811496019363403, 0.25370705127716064, 0.11705280840396881, -0.05278034880757332, 0.03722261264920235, 0.3069724142551422, -0.3166779577732086, 0.3612406551837921, -0.3461386263370514, 0.14271120727062225, -0.4891326129436493, -0.031868647783994675, -0.2105318009853363, -0.10849712789058685, 0.5024760365486145, -0.42960524559020996, 0.09099404513835907, 0.10781149566173553, -0.08149893581867218, -0.36489272117614746, -0.19751374423503876, 0.4677923619747162, -0.19604173302650452, -0.5108305215835571, 0.04228796809911728, 0.40673041343688965, 4.982846260070801, 0.2281806766986847, 0.07898621261119843, 0.015636280179023743, 0.10525976121425629, -0.24056093394756317, 0.1307922601699829, 0.11874490231275558, 0.16272300481796265, 0.33506906032562256, 0.12341885268688202, 0.23444749414920807, 0.0751492977142334, 0.4529761075973511, -0.09843146800994873, -0.0868949443101883, 0.15630561113357544, -1.9064604043960571, 0.1436811089515686, -0.0647597685456276, 0.10218008607625961, 0.22556403279304504, -0.1312151700258255, 0.08798596262931824, -0.316336065530777, 0.08733700215816498, 0.4364594519138336, -0.0841616541147232, -0.12824013829231262, 0.17684020102024078, 0.0005449578166007996, -0.4466038644313812, 0.2596926987171173, -0.04485166817903519, 0.36150938272476196, 0.29519420862197876, -0.13554643094539642, 0.17567718029022217, -0.04864608496427536, 0.09418146312236786, 0.11930356919765472, -0.1689140498638153, -0.07621348649263382, -0.04019908607006073, 0.025453871116042137, -0.04131506010890007, 0.613564133644104, 0.17166201770305634, 0.19252869486808777, -0.1529507040977478, -0.3212543725967407, 0.29930058121681213, 0.183676615357399, 0.256805956363678, -0.348125159740448, -0.24246308207511902, -0.15343236923217773, 0.045282796025276184, 0.12715944647789001, 0.1002541035413742, 0.3344520628452301, 0.12696677446365356, -0.03679069131612778, 0.08682677894830704, 0.027234166860580444, 0.12669570744037628, -0.14569342136383057, -0.11954189836978912, 0.005335235968232155, -0.023069556802511215, 0.12944917380809784, -0.5794199705123901, 0.4554336667060852, 0.26931557059288025, -0.14136828482151031, 0.16985487937927246, 0.035368259996175766, -0.21738597750663757, -0.19395196437835693, -0.2554394602775574, 0.036201342940330505, 0.0026678694412112236, 0.03341682255268097, -0.00012027658522129059, -0.20584441721439362, -0.2441178858280182, -0.29085585474967957, 0.6269326210021973, -0.07581208646297455, 0.01799778640270233, 0.26985567808151245, -0.18378271162509918, -0.21640625596046448, 0.07882273197174072, 0.11399638652801514, 0.16782686114311218, 0.1454664021730423, -0.14690759778022766, 0.5914286375045776, -0.06359510123729706, -0.4243270754814148, 0.419055312871933, 0.03688973933458328, 0.09080688655376434, -0.20464570820331573, -0.23673778772354126, 0.12423155456781387, -0.3539251387119293, -0.05117426812648773, -0.33227285742759705, 0.09913495182991028, -0.5108201503753662, 0.2183261215686798, 0.14858272671699524, -0.03194478526711464, -0.2500399053096771, 0.3474576473236084, -0.08445319533348083, 0.05256013572216034, 0.12885384261608124, 0.05474567040801048, 0.28207558393478394, 0.24913564324378967, 0.017554350197315216, -0.04651769623160362, -0.21744558215141296, -0.5378966331481934, 0.35821494460105896, 0.02395261451601982, 0.2269265353679657, -0.48503151535987854, -0.4348192811012268, 0.2893373370170593, 0.13147799670696259, 0.30677375197410583, -0.38510605692863464, 0.22093357145786285, 0.26399722695350647, -0.49346867203712463, 0.10722221434116364, 0.004673405550420284, -0.2786339819431305, 0.13793890178203583, -0.049813125282526016, -0.258821964263916, 0.336711049079895, 0.19765441119670868, -0.09453567862510681, 0.01727696880698204, 0.10990896075963974, 0.5079712271690369, 0.18238453567028046, 0.29509949684143066, 0.0021931459195911884, 0.44314414262771606, -0.1369258612394333, 0.03231927752494812, -0.013810236006975174, -0.1325978934764862, -0.40534934401512146, 0.30387064814567566, -0.31678539514541626, -0.06312119215726852, 0.35880550742149353, -0.14602607488632202, 0.23039574921131134, -0.10129227489233017, 0.4284210801124573, -0.21266235411167145, -0.38488680124282837, 0.3961750268936157, -0.13077367842197418, 0.2837107181549072, -0.4066965579986572, -0.28119900822639465, -0.12295553833246231, -0.2169499695301056, -0.1610642671585083, -0.2141464203596115, -0.1797635853290558, -0.17363053560256958, 0.8139917254447937, -0.015077708289027214, -0.19219623506069183, 0.5032162666320801, 0.290952205657959, -0.20581594109535217, 0.22820858657360077, -0.07482161372900009, -0.14803574979305267, -0.345528244972229, 0.3796443045139313, -0.03132491186261177, 0.14449141919612885, -0.19413748383522034, 0.3182498812675476, 0.28465232253074646, -0.015421017073094845, -0.04212811961770058, -0.20381203293800354], \\"type\\": \\"float32\\", \\"shape\\": [512]}"^^<https://w3id.org/rdf-tensor/datatypes#NumericDataTensor>) AS ?dist)\n} \nORDER BY DESC(?dist)\nLIMIT 10\n        ', <QUERY_TYPE.INDEX: 'index'>: '\nPREFIX dbr: <http://dbpedia.org/resource/>\nPREFIX dbo: <http://dbpedia.org/ontology/>\nPREFIX dtf: <https://w3id.org/rdf-tensor/functions#>\nPREFIX tensorIndex: <https://qlever.cs.uni-freiburg.de/tensorIndex/>\nSELECT DISTINCT ?s ?thumb_emb ?dist WHERE {\nSERVICE tensorIndex: {\n    _:config tensorIndex:numNN 10 ;\n    tensorIndex:left ?query_vector ;\n    tensorIndex:bindDistance ?dist ;\n    tensorIndex:payload ?s, ?thumb_emb ;\n    tensorIndex:searchK 1 ;\n    tensorIndex:experimentalRightCacheName "easy_index_dbpedia" ;\n    tensorIndex:right ?thumb_emb ;\n    tensorIndex:algorithm tensorIndex:ivf ;\n    tensorIndex:distance tensorIndex:dot .\n       {\n            ?s a dbo:Ship ;\n            dbo:thumbnail_embedding ?thumb_emb .\n        }\n    }\n    VALUES (?query_vector) { ("{\\"data\\": [-0.04262268915772438, -0.1333884298801422, 0.08612467348575592, -0.02091798186302185, -0.15041583776474, 0.1737712323665619, -0.348517507314682, -0.9152146577835083, -0.3341490924358368, 0.17787908017635345, 0.05680551752448082, -0.20725640654563904, 0.5095284581184387, 0.18332251906394958, 0.11725624650716782, 0.1168459951877594, 0.20500661432743073, -0.1478302776813507, -0.007135884836316109, 0.4961417019367218, 0.3664361536502838, 0.41410648822784424, -0.04107498377561569, 0.5009220838546753, -0.2138804793357849, -0.23931393027305603, -0.7052134275436401, 0.4793880879878998, -0.17963360249996185, 0.2792432904243469, -0.06826944649219513, 0.0803503543138504, -0.20019735395908356, 0.25140535831451416, -0.16235408186912537, 0.1176009476184845, 0.10282524675130844, 0.20387926697731018, -0.04952261596918106, 0.26974374055862427, 0.13957971334457397, 0.5327335596084595, 0.12486020475625992, -0.08572806417942047, 0.1065823957324028, -0.06904290616512299, 0.19244082272052765, 0.004055921919643879, -0.016175957396626472, 0.14999307692050934, 0.058157339692115784, -0.2949751913547516, -0.30239489674568176, 0.2556452751159668, -0.056346990168094635, 0.0034323800355196, -0.24107672274112701, 0.266265332698822, -0.21348032355308533, 0.401064395904541, 0.2964056432247162, 0.0030471496284008026, 0.0780687928199768, -0.10076116770505905, 0.12922954559326172, -0.0007172836922109127, -0.07724957168102264, 0.15974968671798706, 0.13473500311374664, 0.002694841008633375, 0.043134912848472595, 0.01628531515598297, 0.28354209661483765, -0.022883642464876175, 0.09224116057157516, -0.5340399742126465, -0.23960845172405243, 0.12176563590765, -0.34699109196662903, 0.05000511556863785, 0.062218617647886276, 0.1143401563167572, -0.01417964044958353, 0.5364919304847717, 0.2277376502752304, -0.029826924204826355, -0.34357592463493347, -0.10327602177858353, -0.0889338031411171, 0.36991357803344727, 0.012964829802513123, -0.07436607033014297, -1.309548258781433, 0.44614243507385254, 0.018672700971364975, -0.2529124319553375, 0.28713902831077576, 0.01675035059452057, 0.035857703536748886, -0.22998324036598206, -0.14083877205848694, -0.07106801122426987, -0.09642128646373749, 0.21655051410198212, 0.09358265995979309, 0.23318399488925934, -0.15376906096935272, 0.27460137009620667, -0.21038588881492615, 0.3248600959777832, -0.1732352375984192, 0.014894681051373482, -0.039007216691970825, 0.1811979115009308, -0.31202074885368347, -0.11454087495803833, -0.16019298136234283, -0.08498432487249374, 0.3788904845714569, -0.1883203685283661, -0.07226619124412537, -0.9254443645477295, -0.18329882621765137, -0.06734245270490646, 0.2413122057914734, -0.164064422249794, -0.3879578113555908, -0.2547023594379425, 0.14271141588687897, 0.39550554752349854, -0.13101597130298615, -0.45052370429039, -0.08015789091587067, 4.995395660400391, -0.23945783078670502, -0.37153586745262146, -0.29315686225891113, 0.08353441953659058, 0.10397690534591675, -0.24532519280910492, -0.29608869552612305, 0.0728289932012558, -0.19765496253967285, 0.2663191854953766, 0.1443239003419876, 0.06140514463186264, -0.0636756494641304, -0.136429563164711, -0.37929514050483704, 0.040126048028469086, 0.20846030116081238, -0.046803634613752365, -0.09697604179382324, 0.2885654866695404, -0.13826711475849152, -0.4298671782016754, 0.454520046710968, -0.3830225467681885, -0.2549723982810974, 0.1788555532693863, 0.07007404416799545, 0.14401200413703918, -0.02052035927772522, -0.06321345269680023, 0.14143216609954834, -0.002827470190823078, 0.13198769092559814, -0.4338044226169586, 0.31351831555366516, -0.015382522717118263, 0.03972843289375305, -0.11416905373334885, 0.32447728514671326, -0.08284606039524078, -0.2795880436897278, 0.33499065041542053, -0.13286051154136658, 0.1413523107767105, 0.1438053846359253, 0.4994203448295593, -0.12618792057037354, 0.13858260214328766, -0.1577799767255783, -0.24153682589530945, 0.3336068093776703, 0.11076335608959198, 0.27649617195129395, 0.19507920742034912, -0.3491799235343933, 0.10086368024349213, -0.1947011947631836, 0.14734765887260437, -0.1792561113834381, -0.2404884546995163, -0.20638126134872437, 0.1594625562429428, -0.2064419835805893, 0.4686662256717682, 0.1224103569984436, -0.1929231882095337, -0.3304961621761322, -0.15453074872493744, 0.3289383053779602, -0.19276845455169678, -0.1419120728969574, 0.036372654139995575, -0.032568495720624924, -0.2757578194141388, -0.17087632417678833, -0.3603208363056183, 0.3550761640071869, 0.07408803701400757, 0.16397617757320404, 0.4174465537071228, 0.03409815952181816, 0.015406325459480286, 0.14059369266033173, -0.2836103141307831, 0.04072924703359604, -0.13061843812465668, 0.08163174986839294, -0.24610236287117004, 0.09389635920524597, -0.24005071818828583, 0.13519728183746338, 0.0464361235499382, 0.22132527828216553, 0.02697714976966381, -0.08397431671619415, 0.23355722427368164, 0.07472678273916245, -0.07733243703842163, -0.08717343956232071, -0.056425370275974274, 0.3738686144351959, 0.03457840532064438, 0.3578338623046875, 0.1249217838048935, -0.3770174980163574, -0.02174508571624756, 0.3847891688346863, -0.31229445338249207, 0.24248838424682617, 0.1730431318283081, 0.21590428054332733, 0.028434207662940025, -0.04749997705221176, -0.354280561208725, 0.2951468825340271, 0.03223574534058571, -0.33378469944000244, 0.5995599031448364, 0.16036856174468994, 0.37374818325042725, -0.27309471368789673, 0.47794461250305176, 0.27809959650039673, 0.07505334913730621, 0.04588694125413895, 0.44692400097846985, -0.061994630843400955, -0.01789759285748005, 0.02898450754582882, -0.17852738499641418, -0.270717054605484, 0.05693190172314644, -0.0238601416349411, -0.1925913393497467, -0.3413273096084595, -0.1934177130460739, -0.30758562684059143, -0.2947530746459961, 0.26107990741729736, 0.1175401359796524, -0.0725201964378357, -0.029527168720960617, -0.37710872292518616, 0.06373333930969238, 0.3712431788444519, 0.16918398439884186, -0.1874537318944931, 0.09985712170600891, 0.10260182619094849, 0.20361138880252838, 0.014345571398735046, 0.5188203454017639, 0.16811496019363403, 0.25370705127716064, 0.11705280840396881, -0.05278034880757332, 0.03722261264920235, 0.3069724142551422, -0.3166779577732086, 0.3612406551837921, -0.3461386263370514, 0.14271120727062225, -0.4891326129436493, -0.031868647783994675, -0.2105318009853363, -0.10849712789058685, 0.5024760365486145, -0.42960524559020996, 0.09099404513835907, 0.10781149566173553, -0.08149893581867218, -0.36489272117614746, -0.19751374423503876, 0.4677923619747162, -0.19604173302650452, -0.5108305215835571, 0.04228796809911728, 0.40673041343688965, 4.982846260070801, 0.2281806766986847, 0.07898621261119843, 0.015636280179023743, 0.10525976121425629, -0.24056093394756317, 0.1307922601699829, 0.11874490231275558, 0.16272300481796265, 0.33506906032562256, 0.12341885268688202, 0.23444749414920807, 0.0751492977142334, 0.4529761075973511, -0.09843146800994873, -0.0868949443101883, 0.15630561113357544, -1.9064604043960571, 0.1436811089515686, -0.0647597685456276, 0.10218008607625961, 0.22556403279304504, -0.1312151700258255, 0.08798596262931824, -0.316336065530777, 0.08733700215816498, 0.4364594519138336, -0.0841616541147232, -0.12824013829231262, 0.17684020102024078, 0.0005449578166007996, -0.4466038644313812, 0.2596926987171173, -0.04485166817903519, 0.36150938272476196, 0.29519420862197876, -0.13554643094539642, 0.17567718029022217, -0.04864608496427536, 0.09418146312236786, 0.11930356919765472, -0.1689140498638153, -0.07621348649263382, -0.04019908607006073, 0.025453871116042137, -0.04131506010890007, 0.613564133644104, 0.17166201770305634, 0.19252869486808777, -0.1529507040977478, -0.3212543725967407, 0.29930058121681213, 0.183676615357399, 0.256805956363678, -0.348125159740448, -0.24246308

In [11]:
triple_counts = []
for db in dbs[:-1]:
    with db:
        count = db.get_triple_count()
        count_tensors = db.query("""
PREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
SELECT (COUNT(?v) AS ?count) WHERE {
    ?s dbo:thumbnail_embedding ?v .
}""")["count"].values[0]
        print(f"{db.name}: {count} triples, {count_tensors} tensors")
        triple_counts.append({
            "count": count,
            "tensors": count_tensors,
            "db": db.name
        })
print(f"Total triples in DB: {sum([tc['count'] for tc in triple_counts])}")

2026-04-27 15:53:24,679 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-04-27 15:53:24,680 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt.gz
2026-04-27 15:53:24,681 - WARNING - DB directory ../data/dbpedia/index-encoded already exists!
2026-04-27 15:53:24,682 - INFO - Stopping server!

2026-04-27 15:53:24,710 - ERROR - Command failed with return code 1
2026-04-27 15:53:24,711 - INFO - Starting QLever server on port 25943
2026-04-27 15:53:24,712 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25943 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-27 15:53:24,744 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:53:25,746 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:53:26,748 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:53:27,749 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:53:28,763 - INFO - Server is up and responding to queries
2026-04-27 15:53:29,918 - INFO - Stopping server!
2026-04-27 15:53:30,014 - ERROR - Command failed with return code 1
2026-04-27 15:53:30,015 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-no-tidx/qlever-no-tidx_run.log
2026-04-27 15:53:30,016 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt.gz
2026-04-27 15:53:30,016 - WARNING - DB directory ../data/dbpedia/index-encoded-no-tidx already exists!
2026-04-27 15:53:30,017 - INFO - Stopping server!
2026-04-27 15:53:30,034 - ERROR - Command failed with return code 1
2026-04-27 15:53:30,034 - INFO - Starting QLever server on port 25844
2026-04-27 15:53:30,035 - INFO - Running command: qlever-server -i dbpedia-encoded --port 25844 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-27 15:53:30,037 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25844/qlever-no-tidx/sparql)

QLever: 421850341 triples, 2369261 tensors

2026-04-27 15:53:31,038 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25844/qlever-no-tidx/sparql)
2026-04-27 15:53:32,040 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25844/qlever-no-tidx/sparql)
2026-04-27 15:53:33,052 - INFO - Server is up and responding to queries
2026-04-27 15:53:34,143 - INFO - Stopping server!
2026-04-27 15:53:34,213 - ERROR - Command failed with return code 1

QLever (No Tensor Vocabulary): 421850341 triples, 2369261 tensors
Total triples in DB: 843700682

In [12]:
counts_df = pd.DataFrame(triple_counts)
counts_df

       count  tensors                             db
0  421850341  2369261                         QLever
1  421850341  2369261  QLever (No Tensor Vocabulary)

In [13]:
counts_df["power"] = counts_df["count"].apply(lambda x: int(np.log10(x)))
counts_df["size"] = counts_df["count"]
counts_df["full_size"] = counts_df["count"]
counts_df["full_number_of_tensors"] = counts_df["tensors"]

In [14]:
from utils.helpers import pretty_print_counts

out_path_counts = Path("../scratch/results") / "dbpedia_counts.tex"
pretty_print_counts(counts_df, out_path_counts)

['power', 'size', 'full_size', 'full_number_of_tensors'] []

   Power  Generation $t$        $n$  $n_{tensors}$
0      8       421850341  421850341        2369261
1      8       421850341  421850341        2369261

In [15]:
with db_qlever as db:
    timings = []
    for _ in tqdm.tqdm(range(5)):
        start = time.time()
        r = db.query_auto(
            query_difficulty=QUERY_DIFFICULTY.EASY,
            query_type=QUERY_TYPE.INDEX,
            tensor=test_tensor,
        )
        end = time.time()
        timings.append(end - start)
print("Timings avg:", sum(timings) / len(timings))
r

2026-04-27 15:53:34,525 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-04-27 15:53:34,526 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt.gz
2026-04-27 15:53:34,527 - WARNING - DB directory ../data/dbpedia/index-encoded already exists!
2026-04-27 15:53:34,527 - INFO - Stopping server!
2026-04-27 15:53:34,594 - ERROR - Command failed with return code 1
2026-04-27 15:53:34,594 - INFO - Starting QLever server on port 25943
2026-04-27 15:53:34,595 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25943 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-27 15:53:34,597 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:53:35,598 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:53:36,600 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:53:37,601 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:53:38,613 - INFO - Server is up and responding to queries
100%|██████████| 5/5 [00:00<00:00,  8.43it/s]
2026-04-27 15:53:39,209 - INFO - Stopping server!
2026-04-27 15:53:39,279 - ERROR - Command failed with return code 1

Timings avg: 0.11848478317260742

,s,thumb_emb,dist
0,dbr:HMS_Warrior_(1860),"{""data"": [0.036129921674728394, 0.429935306310...",28.27962493896
1,dbr:La_Recouvrance_(schooner),"{""data"": [0.17521078884601593, -0.134947225451...",27.91348266602
2,dbr:Denis_Sullivan_(schooner),"{""data"": [0.07062532007694244, -0.230205625295...",27.86698150635
3,dbr:Falls_of_Clyde_(ship),"{""data"": [0.21303661167621613, -0.423036515712...",27.47668266296
4,dbr:SS_Great_Britain,"{""data"": [-0.03920137882232666, -0.19598063826...",27.4443397522
5,dbr:Elissa_(ship),"{""data"": [0.2183631807565689, 0.27063211798667...",27.43548774719
6,dbr:Skade_(yacht),"{""data"": [0.20522180199623108, -0.226250723004...",27.32021522522
7,dbr:L._A._Dunton_(schooner),"{""data"": [0.4466632306575775, -0.4638951420783...",27.07518768311
8,dbr:Pinta_(ship),"{""data"": [0.28884974122047424, -0.175495266914...",27.01076126099
9,dbr:SB_Mirosa,"{""data"": [-0.07320115715265274, -0.25511276721...",27.0029296875

In [16]:
with dbs[0] as db:
    res_native = db.query(f"""
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dtf: <https://w3id.org/rdf-tensor/functions#>
SELECT * WHERE {{


    ?s a dbo:Ship .
    ?s dbo:thumbnail_embedding ?thumb_emb .
    ?s dbo:thumbnail_original ?thumb .      

    BIND(dtf:dotProduct(?thumb_emb, {test_tensor.to_literal().n3()}) AS ?dist)
}} 

ORDER BY DESC(?dist)
LIMIT 10""")
res_native

2026-04-27 15:53:39,359 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-04-27 15:53:39,360 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt.gz
2026-04-27 15:53:39,361 - WARNING - DB directory ../data/dbpedia/index-encoded already exists!
2026-04-27 15:53:39,361 - INFO - Stopping server!
2026-04-27 15:53:39,431 - ERROR - Command failed with return code 1
2026-04-27 15:53:39,432 - INFO - Starting QLever server on port 25943
2026-04-27 15:53:39,432 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25943 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-27 15:53:39,434 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:53:40,436 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:53:41,438 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:53:42,439 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:53:43,452 - INFO - Server is up and responding to queries
2026-04-27 15:53:43,712 - INFO - Stopping server!
2026-04-27 15:53:43,783 - ERROR - Command failed with return code 1

,s,thumb_emb,thumb,dist
0,dbr:HMS_Trent_(1757),"{""data"": [0.20562176406383514, 0.2037418782711...",https://upload.wikimedia.org/wikipedia/commons...,31.31344604492
1,dbr:Fram,"{""data"": [0.2554498314857483, -0.1410300731658...",https://upload.wikimedia.org/wikipedia/commons...,29.51530838013
2,dbr:Fram,"{""data"": [0.2554498314857483, -0.1410300731658...",https://upload.wikimedia.org/wikipedia/commons...,29.51530838013
3,dbr:Fram,"{""data"": [0.2554498314857483, -0.1410300731658...",http://upload.wikimedia.org/wikipedia/commons/...,29.51530838013
4,dbr:Fram,"{""data"": [0.2554498314857483, -0.1410300731658...",https://upload.wikimedia.org/wikipedia/commons...,29.51530838013
5,dbr:Fram,"{""data"": [0.2554498314857483, -0.1410300731658...",https://upload.wikimedia.org/wikipedia/commons...,29.51530838013
6,dbr:Fram,"{""data"": [0.2554498314857483, -0.1410300731658...",http://upload.wikimedia.org/wikipedia/commons/...,29.51530838013
7,dbr:USCGC_Eagle_(WIX-327),"{""data"": [0.288393497467041, 0.597437918186187...",https://upload.wikimedia.org/wikipedia/commons...,29.12233352661
8,dbr:USCGC_Eagle_(WIX-327),"{""data"": [0.288393497467041, 0.597437918186187...",http://upload.wikimedia.org/wikipedia/commons/...,29.12233352661
9,dbr:USCGC_Eagle_(WIX-327),"{""data"": [0.288393497467041, 0.597437918186187...",http://upload.wikimedia.org/wikipedia/commons/...,29.12233352661

In [17]:
with dbs[0] as db:
    res =db.query(f"""
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dtf: <https://w3id.org/rdf-tensor/functions#>
PREFIX tensorIndex: <https://qlever.cs.uni-freiburg.de/tensorIndex/>
SELECT * WHERE {{
SERVICE tensorIndex: {{
    _:config tensorIndex:numNN 10 ;
    tensorIndex:left ?query_vector ;
    tensorIndex:bindDistance ?dist ;
    tensorIndex:payload ?s, ?thumb ;
    tensorIndex:searchK 64 ;
    tensorIndex:kIVF 128 ;
    # tensorIndex:experimentalRightCacheName "easy_index_dbpedia" ;
    tensorIndex:right ?thumb_emb ;
    tensorIndex:algorithm tensorIndex:ivf ;
    tensorIndex:distance tensorIndex:dot .
       {{
            ?s a dbo:Ship ;
            dbo:thumbnail_embedding ?thumb_emb ;
            dbo:thumbnail_original ?thumb .
        }}
    }}
    VALUES (?query_vector) {{ ({test_tensor.to_literal().n3()}) }}
}} 
ORDER BY DESC(?dist)
""")
res

2026-04-27 15:53:43,853 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-04-27 15:53:43,854 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt.gz
2026-04-27 15:53:43,854 - WARNING - DB directory ../data/dbpedia/index-encoded already exists!
2026-04-27 15:53:43,855 - INFO - Stopping server!
2026-04-27 15:53:43,922 - ERROR - Command failed with return code 1
2026-04-27 15:53:43,923 - INFO - Starting QLever server on port 25943
2026-04-27 15:53:43,923 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25943 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-27 15:53:43,925 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:53:44,926 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:53:45,928 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:53:46,940 - INFO - Server is up and responding to queries
2026-04-27 15:53:47,851 - INFO - Stopping server!
2026-04-27 15:53:47,922 - ERROR - Command failed with return code 1

,query_vector,dist,s,thumb,thumb_emb
0,"{""data"": [-0.04262268915772438, -0.13338842988...",27.4443397522,dbr:SS_Great_Britain,https://upload.wikimedia.org/wikipedia/commons...,"{""data"": [-0.03920137882232666, -0.19598063826..."
1,"{""data"": [-0.04262268915772438, -0.13338842988...",27.4443397522,dbr:SS_Great_Britain,https://upload.wikimedia.org/wikipedia/commons...,"{""data"": [-0.03920137882232666, -0.19598063826..."
2,"{""data"": [-0.04262268915772438, -0.13338842988...",27.4443397522,dbr:SS_Great_Britain,https://upload.wikimedia.org/wikipedia/commons...,"{""data"": [-0.03920137882232666, -0.19598063826..."
3,"{""data"": [-0.04262268915772438, -0.13338842988...",27.4443397522,dbr:SS_Great_Britain,https://upload.wikimedia.org/wikipedia/commons...,"{""data"": [-0.03920137882232666, -0.19598063826..."
4,"{""data"": [-0.04262268915772438, -0.13338842988...",27.4443397522,dbr:SS_Great_Britain,https://upload.wikimedia.org/wikipedia/commons...,"{""data"": [-0.03920137882232666, -0.19598063826..."
5,"{""data"": [-0.04262268915772438, -0.13338842988...",27.4443397522,dbr:SS_Great_Britain,https://upload.wikimedia.org/wikipedia/commons...,"{""data"": [-0.03920137882232666, -0.19598063826..."
6,"{""data"": [-0.04262268915772438, -0.13338842988...",27.4443397522,dbr:SS_Great_Britain,https://upload.wikimedia.org/wikipedia/commons...,"{""data"": [-0.03920137882232666, -0.19598063826..."
7,"{""data"": [-0.04262268915772438, -0.13338842988...",27.4443397522,dbr:SS_Great_Britain,http://upload.wikimedia.org/wikipedia/commons/...,"{""data"": [-0.03920137882232666, -0.19598063826..."
8,"{""data"": [-0.04262268915772438, -0.13338842988...",27.4443397522,dbr:SS_Great_Britain,http://upload.wikimedia.org/wikipedia/commons/...,"{""data"": [-0.03920137882232666, -0.19598063826..."
9,"{""data"": [-0.04262268915772438, -0.13338842988...",27.4443397522,dbr:SS_Great_Britain,http://upload.wikimedia.org/wikipedia/commons/...,"{""data"": [-0.03920137882232666, -0.19598063826..."

In [18]:
res.to_csv(Path("scratch") / "dbpedia_results_index.csv", index=False)

In [19]:
with dbs[1] as db:
    db.query_auto(test_tensor, query_type=QUERY_TYPE.INDEX, query_difficulty=QUERY_DIFFICULTY.HARD)

2026-04-27 15:53:48,071 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-no-tidx/qlever-no-tidx_run.log
2026-04-27 15:53:48,072 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt.gz
2026-04-27 15:53:48,073 - WARNING - DB directory ../data/dbpedia/index-encoded-no-tidx already exists!
2026-04-27 15:53:48,073 - INFO - Stopping server!
2026-04-27 15:53:48,140 - ERROR - Command failed with return code 1
2026-04-27 15:53:48,140 - INFO - Starting QLever server on port 25844
2026-04-27 15:53:48,141 - INFO - Running command: qlever-server -i dbpedia-encoded --port 25844 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-27 15:53:48,142 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25844/qlever-no-tidx/sparql)
2026-04-27 15:53:49,144 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25844/qlever-no-tidx/sparql)
2026-04-27 15:53:50,146 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25844/qlever-no-tidx/sparql)
2026-04-27 15:53:51,148 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25844/qlever-no-tidx/sparql)
2026-04-27 15:53:52,160 - INFO - Server is up and responding to queries
2026-04-27 15:53:59,528 - INFO - Stopping server!
2026-04-27 15:53:59,599 - ERROR - Command failed with return code 1

In [20]:
from utils.helpers import ndcgscore_query
reference_result = res_native
score = ndcgscore_query(res, reference_result, k=10)
print(f"Score: {score}")

Score: 0.8042472959280005

In [21]:
# count ships


with dbs[0] as db:
    rs =db.query(f"""
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
SELECT (COUNT(*) AS ?count) WHERE {{ 
            ?s a dbo:Ship ;
            dbo:thumbnail_embedding ?thumb_emb .
}} LIMIT 10""")
    rr =  db.query(f"""PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
SELECT (COUNT(*) AS ?count) WHERE {{ 
            ?s a dbo:RailwayLine ;
            dbo:thumbnail_embedding ?thumb_emb .
}} LIMIT 10""")
rs.iloc[0], rr.iloc[0]

2026-04-27 15:53:59,738 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-04-27 15:53:59,739 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt.gz
2026-04-27 15:53:59,740 - WARNING - DB directory ../data/dbpedia/index-encoded already exists!
2026-04-27 15:53:59,740 - INFO - Stopping server!
2026-04-27 15:53:59,810 - ERROR - Command failed with return code 1
2026-04-27 15:53:59,811 - INFO - Starting QLever server on port 25943
2026-04-27 15:53:59,812 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25943 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-27 15:53:59,814 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:54:00,815 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:54:01,817 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:54:02,819 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:54:03,831 - INFO - Server is up and responding to queries
2026-04-27 15:54:03,888 - INFO - Stopping server!
2026-04-27 15:54:03,961 - ERROR - Command failed with return code 1

(count    25031
 Name: 0, dtype: str,
 count    7548
 Name: 0, dtype: str)

In [22]:
# for find similar thumbnails between ships and railroads
times = []
with dbs[0] as db:
    #     warmup = db.query("""
    # PREFIX dbr: <http://dbpedia.org/resource/>
    # PREFIX dbo: <http://dbpedia.org/ontology/>
    # PREFIX tensorIndex: <https://qlever.cs.uni-freiburg.de/tensorIndex/>
    # SELECT * WHERE {
    #     { SELECT * WHERE {
    #         ?r a dbo:Work .
    #         ?r dbo:thumbnail_embedding ?thumb_rail_emb .
    #         ?r dbo:thumbnail_original ?thumb_rail .
    #     } LIMIT 1
    #     }
    #     SERVICE tensorIndex: {
    #     _:config tensorIndex:numNN 10 ;
    #     tensorIndex:left ?thumb_rail_emb ;
    #     tensorIndex:bindDistance ?dist ;
    #     tensorIndex:payload ?s, ?thumb_ship ;
    #     tensorIndex:searchK 1 ;
    #     tensorIndex:nTrees 128 ;
    #     tensorIndex:experimentalRightCacheName "hard_index_dbpedia" ;
    #     tensorIndex:right ?thumb_emb_ship ;
    #     tensorIndex:algorithm tensorIndex:ivf ;
    #     tensorIndex:distance tensorIndex:dot .
    #         {
    #             ?s a dbo:Ship ;
    #             dbo:thumbnail_embedding ?thumb_emb_ship ;
    #             dbo:thumbnail_original ?thumb_ship .
    #         }
    #     }
    #     }""")
    for _ in range(0):
        start = time.time()

        noised_tensor = DataTensor.from_numpy(
            test_tensor.data + np.random.normal(scale=0.001, size=test_tensor.shape)
        )
        railway_ship_assoc = db.query(f"""
    PREFIX dbr: <http://dbpedia.org/resource/>
    PREFIX dbo: <http://dbpedia.org/ontology/>
    PREFIX dtf: <https://w3id.org/rdf-tensor/functions#>
    PREFIX tensorIndex: <https://qlever.cs.uni-freiburg.de/tensorIndex/>
    SELECT DISTINCT ?r ?s  ?dist ?thumb_rail_emb ?thumb_ship_emb WHERE {{
        {{
        SELECT DISTINCT ?r ?s ?dist ?thumb_rail_emb ?thumb_ship_emb WHERE {{
            
            ?r a dbo:RailwayLine .
            ?r dbo:thumbnail_embedding ?thumb_rail_emb .
                                        
            SERVICE tensorIndex: {{
            _:config tensorIndex:numNN 1 ;
            tensorIndex:left ?thumb_rail_emb ;
            tensorIndex:bindDistance ?dist ;
            tensorIndex:payload ?s, ?thumb_ship ;
            tensorIndex:searchK 1 ;
            tensorIndex:nTrees 512 ;
            tensorIndex:experimentalRightCacheName "hard_index_dbpedia" ;
            tensorIndex:right ?thumb_ship_emb ;
            tensorIndex:algorithm tensorIndex:ivf ;
            tensorIndex:distance tensorIndex:dot .
            {{
                ?s a dbo:Ship ;
                dbo:thumbnail_embedding ?thumb_ship_emb ;    
            }}
            }}                  
        }}
        }}
        VALUES (?some_emb) {{ ({noised_tensor.to_literal().n3()}) }}
                                    
    }}
    ORDER BY DESC(?dist)
    LIMIT 20""")
        end = time.time()
        delta = end - start
        times.append(delta)
times

2026-04-27 15:54:04,042 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-04-27 15:54:04,043 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt.gz
2026-04-27 15:54:04,044 - WARNING - DB directory ../data/dbpedia/index-encoded already exists!
2026-04-27 15:54:04,045 - INFO - Stopping server!
2026-04-27 15:54:04,112 - ERROR - Command failed with return code 1
2026-04-27 15:54:04,113 - INFO - Starting QLever server on port 25943
2026-04-27 15:54:04,113 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25943 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-27 15:54:04,115 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:54:05,117 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:54:06,119 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:54:07,131 - INFO - Server is up and responding to queries
2026-04-27 15:54:07,132 - INFO - Stopping server!
2026-04-27 15:54:07,201 - ERROR - Command failed with return code 1

[]

In [23]:
with db_qlever as db:
    hard_results = db.query(
        f"""
        PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dtf: <https://w3id.org/rdf-tensor/functions#>
PREFIX tensorIndex: <https://qlever.cs.uni-freiburg.de/tensorIndex/>
SELECT DISTINCT ?r ?s  ?dist ?thumb_work_emb ?thumb_settlement_emb WHERE {{
    {{
    SELECT DISTINCT ?r ?s ?dist ?thumb_work_emb ?thumb_settlement_emb WHERE {{
        
        ?r a dbo:RailwayLine;
         dbo:thumbnail_embedding ?thumb_work_emb ;
         dbo:thumbnail_original ?thumb_work_original .
        BIND(LCASE(STR(?thumb_work_original)) AS ?thumb_work)
        FILTER(STRENDS(?thumb_work, ".png") || STRENDS(?thumb_work, ".jpg") || STRENDS(?thumb_work, ".jpeg")) .
                                    
        SERVICE tensorIndex: {{
        _:config tensorIndex:numNN 1 ;
        tensorIndex:left ?thumb_work_emb ;
        tensorIndex:bindDistance ?dist ;
        tensorIndex:payload ?s, ?thumb_settlement_emb ;
        tensorIndex:searchK 1 ;
        tensorIndex:kIVF 128 ;
        tensorIndex:experimentalRightCacheName "hard_index_dbpedia" ;
        tensorIndex:right ?thumb_settlement_emb ;
        tensorIndex:algorithm tensorIndex:ivf ;
        tensorIndex:distance tensorIndex:dot .
        {{
            ?s a dbo:Ship ;
            dbo:thumbnail_embedding ?thumb_settlement_emb ;  
            dbo:thumbnail_original ?thumb_settlement_original .
            BIND(LCASE(STR(?thumb_settlement_original)) AS ?thumb_settlement)
            FILTER(STRENDS(?thumb_settlement, ".png") || STRENDS(?thumb_settlement, ".jpg") || STRENDS(?thumb_settlement, ".jpeg")) .
        }}
        }}                  
    }}
    }}
    VALUES (?some_emb) {{ ({test_tensor.to_literal().n3()}) }}         
}}
ORDER BY DESC(?dist)
LIMIT 10"""
    )
    # hard_results = db.query_auto(
    #     test_tensor, query_type=QUERY_TYPE.INDEX, query_difficulty=QUERY_DIFFICULTY.HARD
    # )
    easy_results = db.query_auto(
        test_tensor, query_type=QUERY_TYPE.INDEX, query_difficulty=QUERY_DIFFICULTY.EASY
    )

2026-04-27 15:54:07,284 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-04-27 15:54:07,285 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt.gz
2026-04-27 15:54:07,285 - WARNING - DB directory ../data/dbpedia/index-encoded already exists!
2026-04-27 15:54:07,286 - INFO - Stopping server!
2026-04-27 15:54:07,355 - ERROR - Command failed with return code 1
2026-04-27 15:54:07,356 - INFO - Starting QLever server on port 25943
2026-04-27 15:54:07,356 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25943 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-27 15:54:07,358 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:54:08,359 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:54:09,361 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:54:10,372 - INFO - Server is up and responding to queries
2026-04-27 15:54:16,832 - INFO - Stopping server!
2026-04-27 15:54:16,902 - ERROR - Command failed with return code 1

In [24]:
easy_results.to_csv(Path("scratch") / "dbpedia_easy_results.csv", index=False)
easy_results

,s,thumb_emb,dist
0,dbr:HMS_Warrior_(1860),"{""data"": [0.036129921674728394, 0.429935306310...",28.27962493896
1,dbr:La_Recouvrance_(schooner),"{""data"": [0.17521078884601593, -0.134947225451...",27.91348266602
2,dbr:Denis_Sullivan_(schooner),"{""data"": [0.07062532007694244, -0.230205625295...",27.86698150635
3,dbr:Falls_of_Clyde_(ship),"{""data"": [0.21303661167621613, -0.423036515712...",27.47668266296
4,dbr:SS_Great_Britain,"{""data"": [-0.03920137882232666, -0.19598063826...",27.4443397522
5,dbr:Elissa_(ship),"{""data"": [0.2183631807565689, 0.27063211798667...",27.43548774719
6,dbr:Skade_(yacht),"{""data"": [0.20522180199623108, -0.226250723004...",27.32021522522
7,dbr:L._A._Dunton_(schooner),"{""data"": [0.4466632306575775, -0.4638951420783...",27.07518768311
8,dbr:Pinta_(ship),"{""data"": [0.28884974122047424, -0.175495266914...",27.01076126099
9,dbr:SB_Mirosa,"{""data"": [-0.07320115715265274, -0.25511276721...",27.0029296875

In [25]:
easy_results.loc[0, "s"], easy_results.loc[0, "thumb_emb"], easy_results.loc[0, "dist"]

('dbr:HMS_Warrior_(1860)',
 '{"data": [0.036129921674728394, 0.4299353063106537, -0.37877365946769714, 0.30682092905044556, 0.322639524936676, 0.2249593734741211, -0.06521791219711304, 0.17391973733901978, -0.2688770294189453, 0.38226354122161865, 0.152025043964386, -0.19757014513015747, 0.7534399032592773, 0.758370578289032, -0.21658317744731903, -0.02999865636229515, 0.23736977577209473, 0.1001720055937767, 0.42510396242141724, 0.14974050223827362, 0.0637899860739708, 0.11872407793998718, -0.35933512449264526, 0.2847185730934143, 0.43100637197494507, 0.46448808908462524, -0.29308536648750305, 0.39990168809890747, -0.04956104978919029, 0.07813140004873276, -0.5828685164451599, 0.1557556390762329, 0.06378577649593353, 0.5864004492759705, 0.1866665631532669, 0.0543186292052269, -0.04140060395002365, -0.18815915286540985, -0.2874862551689148, 1.5594831705093384, 0.19858968257904053, -0.021679505705833435, 0.38822221755981445, 0.5762841105461121, 0.28483134508132935, -0.5699039697647095, -0.09296844899654388, 0.211222842335701, -0.3635264039039612, 0.19089482724666595, 0.0008625462651252747, -0.1196938082575798, 0.04399822652339935, 0.21202993392944336, 0.21068927645683289, 0.4523462951183319, -0.10039745271205902, 0.42145317792892456, 0.31359127163887024, -0.18312062323093414, 1.0730500221252441, -0.2910715341567993, 0.6942504644393921, 0.19939082860946655, 0.5259839296340942, -0.4011019766330719, 0.4308091104030609, 0.26973241567611694, 0.08681108057498932, -0.28301697969436646, 0.21609388291835785, 0.2959131598472595, -0.2556997239589691, 0.017543941736221313, -0.11951670050621033, 0.24607419967651367, 0.14033883810043335, -0.3617511987686157, -0.45068755745887756, 0.24214418232440948, 0.2658235728740692, -0.20223219692707062, 0.09949198365211487, -0.45292651653289795, 0.3048322796821594, 0.3694412112236023, -2.0198631286621094, 0.35509735345840454, -0.3657280206680298, 0.2762342095375061, 0.2610946297645569, -0.2223995327949524, -6.520959377288818, 0.9067122936248779, -0.19134609401226044, 0.1002846211194992, -0.10415159165859222, -0.1573384553194046, 0.0959666445851326, -0.5622581839561462, -0.01724998652935028, -0.04444816708564758, -0.2418135106563568, 0.08460710942745209, 1.351622223854065, 0.8289247751235962, -1.8528070449829102, -0.11391941457986832, -0.7556246519088745, 0.229812890291214, 0.09635967016220093, -0.6126474142074585, -0.03513084724545479, 0.19141773879528046, 0.07152000814676285, -0.6949110627174377, -0.42995744943618774, -0.24878038465976715, 0.40686145424842834, 0.14478915929794312, -0.2851688861846924, -0.4284991919994354, 0.08093306422233582, -0.4831444025039673, 0.1110001653432846, -0.09684956073760986, 0.07316213846206665, 0.07112574577331543, 0.28703930974006653, 0.4983096420764923, 0.7393622994422913, -0.15457236766815186, -0.491720050573349, 0.882398784160614, 0.37151142954826355, -0.207248255610466, -0.31131505966186523, 0.718226969242096, -0.2548128664493561, -0.12748278677463531, -0.13514235615730286, -0.34873586893081665, 0.2522636353969574, 0.12504249811172485, 0.19043678045272827, -0.10778816044330597, -0.15008024871349335, -0.034909043461084366, -0.7296847701072693, 0.24405638873577118, 0.5149716734886169, 0.14135435223579407, 0.21489574015140533, 0.11527962982654572, 0.06010310351848602, -0.35215750336647034, -0.00837632268667221, -0.18915438652038574, 0.05069313198328018, 0.32843899726867676, 0.01745406910777092, -0.23907026648521423, -0.22302605211734772, -0.11079098284244537, 0.29583650827407837, 0.12747891247272491, 0.5815114378929138, 0.04033400118350983, -0.008924916386604309, 0.09269861876964569, 0.48984578251838684, 0.12681801617145538, -0.04566819220781326, 0.026429615914821625, -0.4219449460506439, 0.13531437516212463, -0.6433698534965515, -0.09466294199228287, 0.10321716219186783, 0.3833633065223694, -0.3162863254547119, -0.11249148100614548, 0.23090176284313202, 0.10847266018390656, 0.21616952121257782, 0.42004716396331787, 0.17456600069999695, 0.006972745060920715, -0.33406275510787964, 0.033967211842536926, 0.09664244204759598, 0.38057899475097656, 0.18257378041744232, -0.29455751180648804, 0.5026445984840393, 0.04631295055150986, -0.019615240395069122, 0.5382623672485352, -0.22164463996887207, 0.2987210750579834, 0.02324608340859413, -0.15201209485530853, 0.11226429045200348, 0.51603102684021, 0.4415212869644165, -0.0487150177359581, -0.07715754956007004, -0.058777883648872375, -0.4814402759075165, 0.11814041435718536, -0.38977012038230896, -0.1327594816684723, 1.0356307029724121e-05, -0.09263181686401367, 0.23832844197750092, 0.1983642280101776, 0.22901098430156708, 0.41208797693252563, -0.8901641368865967, 0.15539473295211792, -0.07171152532100677, 0.448617160320282, 0.2662246525287628, -0.20543637871742249, 0.021257340908050537, -0.2743426263332367, -0.09116101264953613, -0.04180518537759781, 0.23032422363758087, 0.1806749701499939, -0.29012346267700195, 0.10946778953075409, -0.25805309414863586, -0.24174153804779053, 0.29495924711227417, -0.05344346910715103, 0.551288366317749, 0.06343348324298859, -0.22433322668075562, -0.4668870270252228, 0.5422210097312927, 0.13744953274726868, -0.0003862902522087097, -0.4675882160663605, -0.13112200796604156, 0.5058268308639526, 0.17937655746936798, -0.2785646319389343, -0.3977641463279724, -0.1363065391778946, -0.2133919596672058, 0.04581423103809357, 0.34534114599227905, -0.023531123995780945, -0.048581384122371674, 0.3699384331703186, -0.2884080111980438, -0.08587957173585892, 0.7352806329727173, 0.6104374527931213, -0.023590318858623505, -0.0346502810716629, 0.11414450407028198, 0.5708051919937134, 0.1136341542005539, -0.38115936517715454, 0.14644940197467804, 0.15466798841953278, -0.040245816111564636, -0.5073889493942261, -0.11088395863771439, 0.11585600674152374, 0.2508295774459839, 0.01611240580677986, 0.07917746156454086, 0.16882377862930298, -0.28567859530448914, -0.23367758095264435, -0.3546510934829712, -0.5378162264823914, 0.7619132399559021, -0.08100567758083344, -0.0228419229388237, 0.3305242657661438, -0.06285391747951508, 0.6694658994674683, 0.13486811518669128, -0.09564945846796036, -0.04471592605113983, -0.055202990770339966, 0.5697349309921265, 0.032264068722724915, -0.3666282892227173, 0.5516500473022461, -0.010508455336093903, 0.05177714675664902, -0.008959375321865082, 0.18822550773620605, 0.3143823444843292, -0.03343404829502106, 0.21678391098976135, 0.062495578080415726, 0.1600949913263321, 0.19118483364582062, 0.18555521965026855, -0.3006134629249573, -0.3170848786830902, 0.5832589864730835, 0.04895714670419693, -0.05573885142803192, 0.1258438229560852, 0.20719246566295624, 0.8812207579612732, 0.6714490056037903, 0.4377717673778534, 0.5235558152198792, 0.055547211319208145, 0.40069329738616943, 0.008304432034492493, 0.10636378824710846, -0.278376042842865, 0.839748740196228, 0.23943549394607544, -0.2698265016078949, 0.2948666512966156, -0.2484285533428192, -0.42710721492767334, 0.18282392621040344, -0.18848399817943573, 0.059129685163497925, -0.14202652871608734, 0.5317648649215698, -0.10433162748813629, 0.38524872064590454, -0.06999276578426361, 0.19271759688854218, -0.01887477934360504, -0.29801440238952637, 0.10184343159198761, 0.1635638028383255, -0.14738871157169342, 0.13887204229831696, -0.4206129312515259, -0.09261365234851837, 0.04611099138855934, 0.006549760699272156, -0.06204158812761307, 0.17656147480010986, 0.2726517617702484, 0.1577495038509369, -0.18863171339035034, -0.3844388425350189, -0.09204316139221191, -0.21854917705059052, 0.15832364559173584, -0.31365424394607544, -0.813021719455719, -0.4821547567844391, 0.3268333077430725, 0.15021269023418427, 0.19447249174118042, -0.48385950922966003, -0.23304082453250885, -0.042921483516693115, -1.263240098953247, 0.2862890958786011, -0.18273398280143738, -1.061981439590454, 0.05892186611890793, -0.10379381477832794, 0.053795911371707916, 0.048727914690971375, -0.06244500353932381, -0.23828011751174927, 0.07254653424024582, 0.10848458111286163, 0.6597254872322083, -0.15658248960971832, 0.3288083076477051, -0.07804371416568756, -0.19215625524520874, -0.5826812386512756, 0.10845453292131424, -0.6762309670448303, -0.20068934559822083, 0.4126877188682556, 0.2990897297859192, 0.07220868021249771, 0.4410524368286133, 0.41835781931877136, 0.14209961891174316, -0.22481051087379456, -0.10591250658035278, -0.13779862225055695, -0.22779127955436707, -0.12669943273067474, -0.22246062755584717, 0.27528977394104004, -0.22931687533855438, -0.499523401260376, 0.27990928292274475, -0.045701272785663605, 0.15779463946819305, 0.04090417921543121, -0.521507740020752, 0.07610774785280228, 0.47570472955703735, 0.3947008550167084, 0.4658434987068176, -0.29134178161621094, 0.4665665030479431, 0.08508521318435669, -0.32613521814346313, -0.13470448553562164, -0.05358658730983734, -0.0859827995300293, -0.05047052353620529, 0.27218666672706604, 0.40974074602127075, -0.21212346851825714, -0.13264568150043488, -0.22657878696918488, 0.513701319694519, -0.3644500970840454, -0.025823578238487244, -0.04166358709335327, -0.22003638744354248, -0.4540313482284546, 0.49704015254974365, 0.11972592025995255, -0.09565956145524979, 0.0015521049499511719, 0.37129682302474976, -0.3636554479598999, 0.09955260902643204, -0.03473760932683945, 0.18668074905872345, 0.08196867257356644, -0.01750442385673523, 0.12729385495185852, 0.01509733498096466, 0.5279677510261536, -0.2636375427246094, 0.21005471050739288, -0.03288097307085991, -0.3998788297176361, 0.11709770560264587, 0.014226291328668594, 0.19361428916454315, -0.260015070438385, 0.0029138922691345215, -0.1719290018081665, 0.013554945588111877, -0.014432482421398163, 0.08928181976079941, 0.2644835114479065, -0.18321281671524048, 0.3507923483848572, -0.37188097834587097, -0.11560572683811188, -0.06825082004070282, -0.20305979251861572, 0.17225193977355957, 0.3350754678249359, 0.5722231864929199, 0.15823040902614594, 0.631842315196991, -0.5735064744949341, -0.22389940917491913, -0.0017896685749292374, 0.22627806663513184, -0.1695060133934021, -0.09573368728160858, -0.42604202032089233, -0.08940718322992325, -0.5268107652664185, -0.22978292405605316, -0.11247941106557846, -0.2249481976032257, -0.10481689125299454, 0.11898578703403473, -0.2302803099155426, 0.13184303045272827, 0.2686179578304291, 0.015167400240898132, 0.02730829268693924, -0.15759627521038055, -0.1639249324798584, -0.02887050434947014, 0.02569274604320526, -0.5614742040634155, 0.46922072768211365, 0.14172585308551788, -0.884758710861206, -0.3656681180000305, -0.23311732709407806, 0.11202159523963928, -0.3697826564311981, -0.5229246020317078, -0.41202712059020996, 0.06603261828422546, 0.42178094387054443, 0.09296490997076035, 0.4641154408454895, 0.4555566906929016, -0.15941122174263, -0.4679799973964691, 0.006396189332008362, -0.10354532301425934, 0.5624544620513916, 0.17200691998004913, -0.38274016976356506], "type": "float32", "shape": [512]}',
 '28.27962493896')

In [26]:
hard_results

,r,s,dist,thumb_work_emb,thumb_settlement_emb
0,dbr:Chengdu_Metro,dbr:Virginia-class_submarine,149.7560424805,"{""data"": [0.22622768580913544, 0.0546032562851...","{""data"": [-0.1000426858663559, -0.080208711326..."
1,dbr:Taipa_line,dbr:Virginia-class_submarine,148.5401763916,"{""data"": [0.03102342039346695, -0.059559382498...","{""data"": [-0.1000426858663559, -0.080208711326..."
2,dbr:Yangluo_Line,dbr:Virginia-class_submarine,146.5701904297,"{""data"": [0.13836224377155304, 0.1058328151702...","{""data"": [-0.1000426858663559, -0.080208711326..."
3,dbr:Buenos_Aires_Underground,dbr:Virginia-class_submarine,140.4429473877,"{""data"": [-0.057316623628139496, -0.1589123308...","{""data"": [-0.1000426858663559, -0.080208711326..."
4,dbr:Line_13_(CPTM),dbr:Virginia-class_submarine,139.5857849121,"{""data"": [-0.21847796440124512, -0.04886087775...","{""data"": [-0.1000426858663559, -0.080208711326..."
5,dbr:Orlyval,dbr:Virginia-class_submarine,138.4967041016,"{""data"": [0.11910116672515869, -0.394591093063...","{""data"": [-0.1000426858663559, -0.080208711326..."
6,dbr:Abbey_Line,dbr:Virginia-class_submarine,137.7716217041,"{""data"": [0.17977674305438995, -0.300230383872...","{""data"": [-0.1000426858663559, -0.080208711326..."
7,dbr:Kolkata_Metro,dbr:Virginia-class_submarine,137.671875,"{""data"": [-0.012433663010597229, -0.1900815814...","{""data"": [-0.1000426858663559, -0.080208711326..."
8,dbr:London_Overground,dbr:Virginia-class_submarine,137.6464233398,"{""data"": [0.02959146350622177, 0.0380432158708...","{""data"": [-0.1000426858663559, -0.080208711326..."
9,dbr:CDGVAL,dbr:Virginia-class_submarine,135.4984130859,"{""data"": [-0.17296558618545532, 0.003928374499...","{""data"": [-0.1000426858663559, -0.080208711326..."

In [27]:
# load images for both results
from utils.dbs.base_db import BaseDB


def enhance_col_with_thumbs(
    db: BaseDB, df: pd.DataFrame, dbr_col: str, thumb_col_name="thumb"
) -> pd.DataFrame:

    thumbs = []
    g = tqdm.tqdm(df[dbr_col], desc=f"Fetching thumbnails for {thumb_col_name}")
    for s in g:
        g.set_description(f"Fetching thumbnails for {thumb_col_name}: '{s}'")
        s = f"<{s.replace('dbr:', 'http://dbpedia.org/resource/')}>"
        res = db.query(f"""PREFIX dbr: <http://dbpedia.org/resource/>
                            PREFIX dbo: <http://dbpedia.org/ontology/>
                            SELECT ?thumb ?thumb_lc WHERE {{
                                {s} dbo:thumbnail_original ?thumb .
                                BIND (LCASE(STR(?thumb)) AS ?thumb_lc) 
                                FILTER (STRENDS(?thumb_lc, ".png") || STRENDS(?thumb_lc, ".jpg") || STRENDS(?thumb_lc, ".jpeg"))
                            }} LIMIT 1""")
        # print(f"Query result for {s}: {res}")
        if len(res) > 0:
            thumbs.append(res["thumb"].values[0])
        else:
            thumbs.append(None)
    df[thumb_col_name] = thumbs
    return df


with db_qlever as db:
    easy_results = enhance_col_with_thumbs(db, easy_results, "s")
    hard_results = enhance_col_with_thumbs(
        db, hard_results, "s", thumb_col_name="thumb_s"
    )
    hard_results = enhance_col_with_thumbs(
        db, hard_results, "r", thumb_col_name="thumb_r"
    )

2026-04-27 15:54:17,241 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-04-27 15:54:17,242 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt.gz
2026-04-27 15:54:17,243 - WARNING - DB directory ../data/dbpedia/index-encoded already exists!
2026-04-27 15:54:17,244 - INFO - Stopping server!
2026-04-27 15:54:17,314 - ERROR - Command failed with return code 1
2026-04-27 15:54:17,315 - INFO - Starting QLever server on port 25943
2026-04-27 15:54:17,315 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25943 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-27 15:54:17,318 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:54:18,319 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:54:19,321 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:54:20,323 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:54:21,335 - INFO - Server is up and responding to queries
Fetching thumbnails for thumb: 'dbr:SB_Mirosa': 100%|██████████| 10/10 [00:00<00:00, 131.22it/s]
Fetching thumbnails for thumb_s: 'dbr:Virginia-class_submarine': 100%|██████████| 10/10 [00:00<00:00, 151.42it/s]
Fetching thumbnails for thumb_r: 'dbr:CDGVAL': 100%|██████████| 10/10 [00:00<00:00, 155.26it/s]
2026-04-27 15:54:21,550 - INFO - Stopping server!
2026-04-27 15:54:21,621 - ERROR - Command failed with return code 1

In [28]:
hard_results.to_csv(Path("scratch") / "dbpedia_hard_results.csv", index=False)
easy_results.to_csv(Path("scratch") / "dbpedia_easy_results.csv", index=False)

In [29]:
easy_results.loc[0, 'thumb'].split('/')[-1]

'HMS_Warrior_Pembroke_Dock_July_1977_B.jpg'

## Token

You need to set your Oauth tokens in the local `.env`:
```sh
MEDIA_WIKI_TOKEN="..."
MEDIA_WIKI_SECRET="..."
MEDIA_WIKI_ACCESS_TOKEN="..."
MEDIA_WIKI_ACCESS_SECRET="..."
```
You can register a new token [here](https://meta.wikimedia.org/wiki/Special:OAuthConsumerRegistration/propose/oauth1a).

In [30]:
import requests
from requests_oauthlib import OAuth1
import dotenv
from utils.datasets.dbpedia_utils.helpers import USER_AGENT

dotenv.load_dotenv()  # to load MEDIAWIKI_TOKEN from .env file

auth = OAuth1(
    os.getenv("MEDIA_WIKI_TOKEN"),
    os.getenv("MEDIA_WIKI_SECRET"),
    os.getenv("MEDIA_WIKI_ACCESS_TOKEN"),
    os.getenv("MEDIA_WIKI_ACCESS_SECRET"),
)

In [31]:
auth.client

<Client client_key=eea9f51d9008d744c272c3ece851b184, client_secret=****, resource_owner_key=914b284deef1f1f0525ea803d55914b0, resource_owner_secret=****, signature_method=HMAC-SHA1, signature_type=AUTH_HEADER, callback_uri=None, rsa_key=None, verifier=None, realm=None, encoding=utf-8, decoding=utf-8, nonce=None, timestamp=None>

In [32]:
url=f"https://commons.wikimedia.org/wiki/Special:FilePath/{easy_results.loc[0, 'thumb'].split('/')[-1]}?width=330"
resp = requests.get(
    url,
    auth=auth,
    headers={"User-Agent": USER_AGENT},
)

In [33]:
import pywikibot

pywikibot.config.usernames['commons']['commons'] = "Dakantz"
# set user-agent

authenticate = (
    os.getenv("MEDIA_WIKI_TOKEN"),
    os.getenv("MEDIA_WIKI_SECRET"),
    os.getenv("MEDIA_WIKI_ACCESS_TOKEN"),
    os.getenv("MEDIA_WIKI_ACCESS_SECRET"),
)
pywikibot.config.authenticate['commons.wikimedia.org'] = authenticate
pywikibot.config.user_agent = USER_AGENT
site = pywikibot.Site('commons', 'commons')
site.login()

In [34]:
site.allimages()

In [35]:
from PIL import Image
fname = easy_results.loc[0, "thumb"].split("/")[-1]
img = pywikibot.FilePage(site, fname)

img.download(filename=fname, url_width=330)
img = Image.open(fname)

In [36]:
from utils.datasets.dbpedia_utils import image_formatter


def thumbs_to_pil(
    thumbs: pd.Series, scratch_dir=Path("../scratch/dbpedia_thumbs")
) -> pd.Series:

    scratch_dir.mkdir(parents=True, exist_ok=True)
    pil_images = []
    g = tqdm.tqdm(thumbs, desc="Fetching thumbnails")
    for thumb in g:
        g.set_description(f"Fetching thumbnail for {thumb}...")
        # url_thumb = get_wc_thumb(thumb)

        fname = thumb.split("/")[-1]
        out_f = scratch_dir / fname
        if not out_f.exists():
            img = pywikibot.FilePage(site, fname)
            img.download(filename=out_f, url_width=330)
        img = Image.open(out_f)
        pil_images.append(img)
    return pd.Series(pil_images, index=thumbs.index)


easy_results["thumb_img"] = thumbs_to_pil(easy_results["thumb"])
hard_results["thumb_s_img"] = thumbs_to_pil(hard_results["thumb_s"])
hard_results["thumb_r_img"] = thumbs_to_pil(hard_results["thumb_r"])

Fetching thumbnail for https://upload.wikimedia.org/wikipedia/commons/2/23/HMS_Warrior_Pembroke_Dock_July_1977_B.jpg...:   0%|          | 0/10 [00:00<?, ?it/s]

Fetching thumbnail for http://upload.wikimedia.org/wikipedia/commons/0/0d/SS_Great_Britain_diagram.jpg...:  40%|████      | 4/10 [00:08<00:12,  2.15s/it]              WARNING: Http response status 429
WARNING: Unsuccessful request (429): https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/SS_Great_Britain_diagram.jpg/330px-SS_Great_Britain_diagram.jpg
Fetching thumbnail for http://upload.wikimedia.org/wikipedia/commons/0/0d/SS_Great_Britain_diagram.jpg...:  40%|████      | 4/10 [00:11<00:16,  2.79s/it]

FileNotFoundError: [Errno 2] No such file or directory: '../scratch/dbpedia_thumbs/SS_Great_Britain_diagram.jpg'

In [ ]:
out_dir = Path("../scratch/results/")


def to_tex_with_thumbs(
    df,
    t_cols=["thumb_img"],
    col_mapping={
        "s": "Ship",
        "r": "Railway",
        "thumb_img_tex": "Thumbnail",
        "dist": "Distance",
    },
    base_dir="figures/generated",
    sub_dir="dbpedia/media",
    out_name="dbpedia_easy_results.tex",
    col_format ="lp{3cm}r"
):
    out_dir.mkdir(parents=True, exist_ok=True)
    results_dir = Path(out_dir) / sub_dir
    results_dir.mkdir(parents=True, exist_ok=True)
    fig_dir = Path(base_dir) / sub_dir
    for t_col in t_cols:
        df[f"{t_col}_tex"] = df[t_col]
        
        for i, r in df.iterrows():
            if r[t_col] is not None and isinstance(r[t_col], Image.Image):
                fname = f"{t_col}_{i}.png"
                fig_file = fig_dir / fname
                im_file = results_dir / fname
                df.at[i, f"{t_col}_tex"] = f"\\includegraphics[width=3cm]{{{fig_file}}}"
                print(f"Saving image for row {i} to {im_file} and referencing as {fig_file} in LaTeX", r[t_col])
                img: Image = r[t_col]
                img.save(im_file)
            else:
                df.at[i, f"{t_col}_tex"] = "No image"
    df_renamed = df.rename(columns=col_mapping)
    print(f"Renamed columns for LaTeX: {df_renamed.columns}")
    allowed_cols = [c for c in list(col_mapping.values()) if c in df_renamed.columns]
    print(f"Allowed columns for LaTeX output: {allowed_cols}")
    df_renamed = df_renamed[allowed_cols]
    df_renamed.set_index(allowed_cols[0], inplace=True)
    df_renamed.style.to_latex(
        buf= results_dir / out_name,
        column_format=col_format,
    )


to_tex_with_thumbs(easy_results)

Saving image for row 0 to ../scratch/results/dbpedia/media/thumb_img_0.png and referencing as figures/generated/dbpedia/media/thumb_img_0.png in LaTeX <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=330x247 at 0x7FF50012B5C0>
Saving image for row 1 to ../scratch/results/dbpedia/media/thumb_img_1.png and referencing as figures/generated/dbpedia/media/thumb_img_1.png in LaTeX <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=330x217 at 0x7FF500128050>
Saving image for row 2 to ../scratch/results/dbpedia/media/thumb_img_2.png and referencing as figures/generated/dbpedia/media/thumb_img_2.png in LaTeX <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=330x250 at 0x7FF4FBFE3360>
Renamed columns for LaTeX: Index(['Ship', 'thumb_emb', 'Distance', 'thumb', 'thumb_img', 'Thumbnail'], dtype='str')
Allowed columns for LaTeX output: ['Ship', 'Thumbnail', 'Distance']