In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import tqdm
import sys
import os
import pandas as pd
import time

In [3]:
from sentence_transformers import SentenceTransformer

encoding_model = SentenceTransformer("clip-ViT-B-32")

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

CLIPModel LOAD REPORT from: /home/bkantz/.cache/huggingface/hub/models--sentence-transformers--clip-ViT-B-32/snapshots/327ab6726d33c0e22f920c83f2ff9e4bd38ca37f/0_CLIPModel
Key                                  | Status     |  |
-------------------------------------+------------+--+-
vision_model.embeddings.position_ids | UNEXPECTED |  |
text_model.embeddings.position_ids   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [4]:
import dotenv
import os

config = dotenv.dotenv_values(".env")
replace_keys = ["JAVA_HOME", "FUSEKI_HOME"]
append_keys = ["PATH"]
for key, value in config.items():
    # append to os.environ
    if key in append_keys:
        os.environ[key] = f"{os.environ.get(key, '')}:{value}"
    elif key in replace_keys:
        os.environ[key] = value

# check and compare values in fuseki log
os.environ["OPENBLAS_NUM_THREADS"] = "4"

In [5]:
sys.path.append("..")

In [6]:
from utils.datasets import DBPedia
from utils.dbs.qlever_native import QleverDBNative
from utils.dbs.fuseki_native import FusekiDBNative
from utils.datasets.base_dataset import QUERY_DIFFICULTY, QUERY_TYPE
from pathlib import Path
import numpy as np
from utils.datasets.base_dataset import DataTensor

2026-09-02 12:40:11,239 - INFO - Loading faiss with AVX512 support.
2026-09-02 12:40:11,239 - INFO - Could not load library with AVX512 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx512'")
2026-09-02 12:40:11,239 - INFO - Loading faiss with AVX2 support.
2026-09-02 12:40:11,239 - INFO - Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2026-09-02 12:40:11,240 - INFO - Loading faiss.
2026-09-02 12:40:11,251 - INFO - Successfully loaded faiss.

In [7]:
dataset = DBPedia(base_dir=Path("../data/dbpedia"))

In [8]:
test_label = "horse on the bow"
test_tensor = DataTensor.from_numpy(encoding_model.encode(test_label))

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [9]:
test_tensor.to_literal().n3()

'"{\\"data\\": [-0.04262261837720871, -0.13338792324066162, 0.08612485975027084, -0.02091819792985916, -0.15041571855545044, 0.1737712323665619, -0.34851735830307007, -0.915214478969574, -0.3341490924358368, 0.17787931859493256, 0.05680549144744873, -0.2072562426328659, 0.5095283389091492, 0.18332259356975555, 0.11725617945194244, 0.11684612929821014, 0.2050066441297531, -0.147830069065094, -0.007135719060897827, 0.4961419701576233, 0.3664358854293823, 0.4141063094139099, -0.041074950248003006, 0.5009220838546753, -0.2138802707195282, -0.23931394517421722, -0.7052134275436401, 0.4793875813484192, -0.17963369190692902, 0.279243141412735, -0.06826923787593842, 0.08035053312778473, -0.20019766688346863, 0.25140517950057983, -0.16235414147377014, 0.11760087311267853, 0.10282528400421143, 0.20387886464595795, -0.04952246695756912, 0.26974374055862427, 0.1395796537399292, 0.532733678817749, 0.12486031651496887, -0.0857280045747757, 0.10658238083124161, -0.06904299557209015, 0.1924407035112381, 0.0040557533502578735, -0.016175996512174606, 0.14999297261238098, 0.05815725401043892, -0.2949751615524292, -0.3023947775363922, 0.2556454539299011, -0.056347113102674484, 0.003432508558034897, -0.24107696115970612, 0.266265332698822, -0.2134804129600525, 0.40106454491615295, 0.29640546441078186, 0.0030471980571746826, 0.07806861400604248, -0.10076117515563965, 0.1292295604944229, -0.0007172338664531708, -0.07724951207637787, 0.1597495973110199, 0.13473474979400635, 0.0026947632431983948, 0.043134890496730804, 0.01628521829843521, 0.2835419178009033, -0.022884022444486618, 0.09224118292331696, -0.5340400338172913, -0.2396087646484375, 0.12176559865474701, -0.34699124097824097, 0.05000507831573486, 0.06221848726272583, 0.1143399178981781, -0.014179453253746033, 0.5364915132522583, 0.2277376353740692, -0.029826676473021507, -0.3435761630535126, -0.1032758355140686, -0.088934026658535, 0.3699132800102234, 0.012964893132448196, -0.0743662565946579, -1.3095483779907227, 0.4461422860622406, 0.018672585487365723, -0.2529124915599823, 0.28713881969451904, 0.016750093549489975, 0.035858191549777985, -0.2299833595752716, -0.1408388614654541, -0.07106809318065643, -0.09642137587070465, 0.21655043959617615, 0.09358268976211548, 0.2331838309764862, -0.15376894176006317, 0.27460145950317383, -0.2103860229253769, 0.3248600661754608, -0.17323511838912964, 0.014895070344209671, -0.03900758922100067, 0.18119798600673676, -0.31202051043510437, -0.11454081535339355, -0.16019321978092194, -0.08498413860797882, 0.3788909316062927, -0.18832029402256012, -0.07226625829935074, -0.9254441857337952, -0.1832987666130066, -0.06734238564968109, 0.24131202697753906, -0.16406460106372833, -0.3879578113555908, -0.25470250844955444, 0.14271147549152374, 0.395505428314209, -0.1310158222913742, -0.45052385330200195, -0.0801578238606453, 4.995394229888916, -0.23945778608322144, -0.37153565883636475, -0.29315707087516785, 0.08353449404239655, 0.1039765253663063, -0.24532540142536163, -0.29608869552612305, 0.07282878458499908, -0.19765472412109375, 0.266319215297699, 0.14432401955127716, 0.061404865235090256, -0.06367572396993637, -0.1364295780658722, -0.37929514050483704, 0.040126219391822815, 0.20845989882946014, -0.046803444623947144, -0.09697595983743668, 0.288565456867218, -0.13826709985733032, -0.42986711859703064, 0.45452016592025757, -0.38302284479141235, -0.254972368478775, 0.17885541915893555, 0.0700741708278656, 0.14401181042194366, -0.020520225167274475, -0.06321331113576889, 0.14143213629722595, -0.0028275176882743835, 0.13198743760585785, -0.4338041841983795, 0.31351834535598755, -0.015382647514343262, 0.039728716015815735, -0.11416907608509064, 0.3244771361351013, -0.08284628391265869, -0.2795877158641815, 0.3349907398223877, -0.13286039233207703, 0.14135229587554932, 0.1438053995370865, 0.4994204640388489, -0.1261882483959198, 0.13858246803283691, -0.15778028964996338, -0.24153704941272736, 0.3336067199707031, 0.11076349020004272, 0.27649667859077454, 0.1950792372226715, -0.3491799235343933, 0.10086368024349213, -0.19470125436782837, 0.14734764397144318, -0.17925560474395752, -0.24048858880996704, -0.20638099312782288, 0.15946261584758759, -0.20644202828407288, 0.4686662554740906, 0.12241038680076599, -0.19292324781417847, -0.3304961919784546, -0.15453054010868073, 0.3289385735988617, -0.19276867806911469, -0.14191241562366486, 0.03637257218360901, -0.03256833553314209, -0.27575767040252686, -0.17087629437446594, -0.3603207767009735, 0.3550758957862854, 0.07408791780471802, 0.16397632658481598, 0.41744640469551086, 0.034098152071237564, 0.015406399965286255, 0.14059355854988098, -0.2836102247238159, 0.04072922468185425, -0.13061822950839996, 0.08163197338581085, -0.24610207974910736, 0.0938967615365982, -0.2400507926940918, 0.1351974904537201, 0.046436332166194916, 0.22132550179958344, 0.02697707712650299, -0.08397427201271057, 0.2335571050643921, 0.07472646236419678, -0.07733258605003357, -0.08717349171638489, -0.05642538145184517, 0.3738681972026825, 0.03457833454012871, 0.35783377289772034, 0.12492182850837708, -0.37701719999313354, -0.021745264530181885, 0.38478928804397583, -0.3122943341732025, 0.2424883395433426, 0.17304325103759766, 0.21590423583984375, 0.028433961793780327, -0.04750015214085579, -0.35428059101104736, 0.295147180557251, 0.03223571926355362, -0.33378466963768005, 0.5995599031448364, 0.1603686362504959, 0.373747855424881, -0.27309462428092957, 0.477944552898407, 0.2780996859073639, 0.07505357265472412, 0.045886918902397156, 0.4469239413738251, -0.06199461966753006, -0.01789771020412445, 0.0289846733212471, -0.17852748930454254, -0.2707172632217407, 0.05693214014172554, -0.023860447108745575, -0.19259145855903625, -0.34132760763168335, -0.19341745972633362, -0.3075855076313019, -0.29475292563438416, 0.2610797584056854, 0.11754046380519867, -0.0725199282169342, -0.029527094215154648, -0.377108633518219, 0.06373339891433716, 0.37124335765838623, 0.169184148311615, -0.18745383620262146, 0.09985687583684921, 0.10260219126939774, 0.20361125469207764, 0.014345735311508179, 0.51882004737854, 0.16811507940292358, 0.2537069320678711, 0.11705267429351807, -0.052780453115701675, 0.03722219914197922, 0.3069725036621094, -0.3166780471801758, 0.36124086380004883, -0.34613877534866333, 0.14271125197410583, -0.4891323745250702, -0.03186889737844467, -0.2105317860841751, -0.10849729180335999, 0.5024758577346802, -0.4296053647994995, 0.09099423885345459, 0.10781156271696091, -0.08149890601634979, -0.3648923933506012, -0.19751375913619995, 0.4677920341491699, -0.19604165852069855, -0.5108304023742676, 0.042287807911634445, 0.4067304730415344, 4.982845783233643, 0.22818076610565186, 0.07898610085248947, 0.01563611626625061, 0.105259969830513, -0.24056123197078705, 0.13079236447811127, 0.11874516308307648, 0.16272284090518951, 0.33506882190704346, 0.12341848015785217, 0.23444727063179016, 0.07514935731887817, 0.4529765248298645, -0.09843145310878754, -0.08689466863870621, 0.15630555152893066, -1.9064607620239258, 0.14368079602718353, -0.0647599846124649, 0.10218003392219543, 0.22556400299072266, -0.13121503591537476, 0.08798617124557495, -0.31633618474006653, 0.08733680844306946, 0.43645909428596497, -0.08416179567575455, -0.12823979556560516, 0.17684032022953033, 0.0005447790026664734, -0.44660407304763794, 0.2596926987171173, -0.04485172778367996, 0.3615094721317291, 0.29519376158714294, -0.13554659485816956, 0.175677090883255, -0.048646196722984314, 0.09418138116598129, 0.11930355429649353, -0.16891427338123322, -0.07621348649263382, -0.04019924998283386, 0.02545417845249176, -0.041315339505672455, 0.6135640144348145, 0.17166198790073395, 0.19252857565879822, -0.15295064449310303, -0.3212544620037079, 0.2993006408214569, 0.18367624282836914, 0.25680601596832275, -0.34812504053115845, -0.24246320128440857, -0.15343238413333893, 0.045282717794179916, 0.1271594762802124, 0.10025447607040405, 0.334451824426651, 0.12696680426597595, -0.03679068386554718, 0.08682702481746674, 0.027233988046646118, 0.12669581174850464, -0.14569346606731415, -0.11954179406166077, 0.005335257388651371, -0.02306964248418808, 0.12944912910461426, -0.5794200897216797, 0.4554334580898285, 0.2693153917789459, -0.14136779308319092, 0.1698547899723053, 0.03536844998598099, -0.21738606691360474, -0.19395220279693604, -0.25543925166130066, 0.03620150312781334, 0.0026681646704673767, 0.03341686353087425, -0.00012034177780151367, -0.20584435760974884, -0.2441178262233734, -0.2908558249473572, 0.6269327402114868, -0.07581189274787903, 0.017997711896896362, 0.2698557376861572, -0.18378284573554993, -0.21640603244304657, 0.0788225382566452, 0.11399653553962708, 0.16782666742801666, 0.14546649158000946, -0.14690737426280975, 0.5914287567138672, -0.0635950043797493, -0.4243273138999939, 0.41905543208122253, 0.03688976913690567, 0.09080655872821808, -0.20464584231376648, -0.2367374300956726, 0.12423168122768402, -0.35392531752586365, -0.05117424204945564, -0.33227282762527466, 0.09913498908281326, -0.5108200907707214, 0.2183261513710022, 0.1485825479030609, -0.03194474056363106, -0.25003987550735474, 0.34745749831199646, -0.08445323258638382, 0.052560463547706604, 0.12885388731956482, 0.054745785892009735, 0.2820756435394287, 0.24913564324378967, 0.01755470037460327, -0.04651793837547302, -0.2174454629421234, -0.5378966331481934, 0.3582148551940918, 0.023952748626470566, 0.22692671418190002, -0.4850316643714905, -0.4348190724849701, 0.28933748602867126, 0.13147786259651184, 0.306773841381073, -0.3851057291030884, 0.22093342244625092, 0.2639969289302826, -0.49346858263015747, 0.10722213983535767, 0.004673480987548828, -0.2786341607570648, 0.13793891668319702, -0.04981335625052452, -0.2588220238685608, 0.33671075105667114, 0.19765432178974152, -0.09453566372394562, 0.017276830971240997, 0.10990896075963974, 0.5079712271690369, 0.18238458037376404, 0.29509907960891724, 0.0021931976079940796, 0.44314393401145935, -0.13692569732666016, 0.03231937438249588, -0.013810083270072937, -0.1325979232788086, -0.40534916520118713, 0.3038704991340637, -0.3167855143547058, -0.06312127411365509, 0.3588055670261383, -0.14602583646774292, 0.23039546608924866, -0.1012926697731018, 0.4284208118915558, -0.21266217529773712, -0.3848867416381836, 0.3961751461029053, -0.1307736337184906, 0.2837108075618744, -0.4066964089870453, -0.2811991274356842, -0.12295562028884888, -0.2169499397277832, -0.16106459498405457, -0.21414650976657867, -0.17976339161396027, -0.1736304759979248, 0.8139913082122803, -0.015078000724315643, -0.19219626486301422, 0.5032161474227905, 0.29095208644866943, -0.20581603050231934, 0.22820892930030823, -0.0748215913772583, -0.14803528785705566, -0.34552839398384094, 0.3796442151069641, -0.03132515773177147, 0.1444910168647766, -0.1941375434398651, 0.31824991106987, 0.28465208411216736, -0.01542038843035698, -0.04212808236479759, -0.20381207764148712], \\"type\\": \\"float32\\", \\"shape\\": [512]}"^^<https://w3id.org/rdf-tensor/datatypes#NumericDataTensor>'

In [ ]:
db_qlever = QleverDBNative(
    id="qlever",
    base_dir=Path(f"./scratch/{dataset.base_dir.name}"),
    dataset=dataset,
    use_encoded_ttl=True,
    name="QLever",
    port_offset=-100,
)
db_no_tensor_idx = QleverDBNative(
    id="qlever",
    base_dir=Path(f"./scratch/{dataset.base_dir.name}"),
    dataset=dataset,
    use_encoded_ttl=True,
    enable_tensor_index=False,
    name="QLever (No Tensor Vocabulary)",
    port_offset=-200
)
db_fuseki = FusekiDBNative(
    id="fuseki",
    base_dir=Path(f"./scratch/{dataset.base_dir.name}"),
    dataset=dataset,
    use_encoded_ttl=True,
    name="Fuseki",
    exec_dir="../../jena-datatensor",
    port_offset=-300
)
possible_queries = db_qlever.get_queries(test_tensor)
print(possible_queries)
dbs: list[QleverDBNative | FusekiDBNative] = [db_qlever, db_no_tensor_idx, db_fuseki]
indices = ["index-encoded", "index-encoded-no-tidx", "fuseki-encoded"]
ids = ["dbpedia-encoded-tidx", "dbpedia-encoded", None]
for db, index, id in zip(dbs, indices, ids):
    db.db_dir = Path("../data/dbpedia/dbpedia") / index
    db.id = id if id is not None else db.id

TypeError: QleverDBNative.__init__() got an unexpected keyword argument 'timeout'

In [13]:
triple_counts = []
for db in dbs[:-1]:
    with db:
        count = db.get_triple_count()
        count_per_cls = db.query("""PREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
SELECT ?c (COUNT(?v) AS ?count) WHERE {
    ?s a ?c;
        dbo:thumbnail_embedding ?v .
    FILTER(STRSTARTS(STR(?c), "http://dbpedia.org/ontology/")) .
} GROUP BY ?c ORDER BY DESC(?count) LIMIT 100""")
        print(count_per_cls)
        count_tensors = db.query("""
PREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
SELECT (COUNT(?v) AS ?count) WHERE {
    ?s dbo:thumbnail_embedding ?v .
}""")["count"].values[0]
        print(f"{db.name}: {count} triples, {count_tensors} tensors")
        triple_counts.append({
            "count": count,
            "tensors": count_tensors,
            "db": db.name
        })
print(f"Total triples in DB: {sum([tc['count'] for tc in triple_counts])}")

2026-09-02 12:40:32,368 - INFO - Setting up QLeverDBNative db_dir=../data/dbpedia/dbpedia/index-encoded, base_dir=scratch/dbpedia
2026-09-02 12:40:32,369 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-09-02 12:40:32,369 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt
2026-09-02 12:40:32,369 - WARNING - DB directory ../data/dbpedia/dbpedia/index-encoded already exists!
2026-09-02 12:40:32,369 - INFO - Stopping server!
2026-09-02 12:40:32,374 - ERROR - Command failed with return code 1
2026-09-02 12:40:32,374 - INFO - Starting QLever server on port 25946
2026-09-02 12:40:32,374 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25946 -k 0 -m 16G --tensor-search-max-num-threads 4
2026-09-02 12:40:32,380 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25946/qlever-with-tidx/sparql)

2026-09-02 12:40:33,381 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25946/qlever-with-tidx/sparql)
2026-09-02 12:40:34,388 - INFO - Server is up and responding to queries
2026-09-02 12:40:39,453 - INFO - Stopping server!
25946/tcp:
2026-09-02 12:40:39,474 - INFO - Setting up QLeverDBNative db_dir=../data/dbpedia/dbpedia/index-encoded-no-tidx, base_dir=scratch/dbpedia
2026-09-02 12:40:39,475 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-no-tidx/qlever-no-tidx_run.log
2026-09-02 12:40:39,475 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt
2026-09-02 12:40:39,475 - WARNING - DB directory ../data/dbpedia/dbpedia/index-encoded-no-tidx already exists!
2026-09-02 12:40:39,476 - INFO - Stopping server!
2026-09-02 12:40:39,480 - ERROR - Command failed with return code 1
2026-09-02 12:40:39,480 - INFO - Starting QLever server on port 25847
2026-09-02 12:40:39,481 - INFO - Running command: qlever-server -i dbpedia-encoded --port 25847 -k 0 -m 16G --tensor-search-max-num-threads 4
2026-09-02 12:40:39,481 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25847/qlever-no-tidx/sparql)

                      c   count
0             dbo:Place  435458
1          dbo:Location  435458
2           dbo:Species  350010
3         dbo:Eukaryote  349864
4            dbo:Animal  347640
..                  ...     ...
95    dbo:SoccerManager    4422
96   dbo:TelevisionShow    4389
97  dbo:MotorsportRacer    4336
98    dbo:SportsManager    4326
99       dbo:Locomotive    4318

[100 rows x 2 columns]
QLever: 421850341 triples, 2369261 tensors
 1847090

2026-09-02 12:40:40,482 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25847/qlever-no-tidx/sparql)
2026-09-02 12:40:41,487 - INFO - Server is up and responding to queries
2026-09-02 12:41:03,045 - INFO - Stopping server!

                      c   count
0             dbo:Place  435458
1          dbo:Location  435458
2           dbo:Species  350010
3         dbo:Eukaryote  349864
4            dbo:Animal  347640
..                  ...     ...
95    dbo:SoccerManager    4422
96   dbo:TelevisionShow    4389
97  dbo:MotorsportRacer    4336
98    dbo:SportsManager    4326
99       dbo:Locomotive    4318

[100 rows x 2 columns]
QLever (No Tensor Vocabulary): 421850341 triples, 2369261 tensors
Total triples in DB: 843700682

25847/tcp:

 1847265

In [14]:
count_per_cls.to_csv("../data/dbpedia/thumbnail_embedding_count_per_cls.csv", index=False)

In [15]:
counts_df = pd.DataFrame(triple_counts)
counts_df

       count  tensors                             db
0  421850341  2369261                         QLever
1  421850341  2369261  QLever (No Tensor Vocabulary)

In [16]:
counts_df["power"] = counts_df["count"].apply(lambda x: int(np.log10(x)))
counts_df["size"] = counts_df["count"]
counts_df["full_size"] = counts_df["count"]
counts_df["full_number_of_tensors"] = counts_df["tensors"]

In [17]:
from utils.helpers import pretty_print_counts

out_path_counts = Path("../scratch/results") / "dbpedia_counts.tex"
pretty_print_counts(counts_df, out_path_counts)

Format cols: ['power', 'size', 'full_size', 'full_number_of_tensors'] Non-format cols: []

   Power  Generation $t$        $n$  $n_{tensors}$
0      8       421850341  421850341        2369261
1      8       421850341  421850341        2369261

In [45]:
with db_qlever as db:
    timings = []
    for _ in tqdm.tqdm(range(5)):
        start = time.time()
        r = db.query_auto(
            query_difficulty=QUERY_DIFFICULTY.HARD,
            query_type=QUERY_TYPE.INDEX,
            tensor=test_tensor,
            timeout=120
        )
        end = time.time()
        timings.append(end - start)
print("Timings avg:", sum(timings) / len(timings))
r

2026-09-02 13:14:47,700 - INFO - Setting up QLeverDBNative db_dir=../data/dbpedia/dbpedia/index-encoded, base_dir=scratch/dbpedia
2026-09-02 13:14:47,701 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-09-02 13:14:47,701 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt
2026-09-02 13:14:47,701 - WARNING - DB directory ../data/dbpedia/dbpedia/index-encoded already exists!
2026-09-02 13:14:47,701 - INFO - Stopping server!
2026-09-02 13:14:47,706 - ERROR - Command failed with return code 1
2026-09-02 13:14:47,706 - INFO - Starting QLever server on port 25946
2026-09-02 13:14:47,706 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25946 -k 0 -m 16G --tensor-search-max-num-threads 4
2026-09-02 13:14:47,707 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25946/qlever-with-tidx/sparql)

2026-09-02 13:14:48,708 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25946/qlever-with-tidx/sparql)
2026-09-02 13:14:49,713 - INFO - Server is up and responding to queries
100%|██████████| 5/5 [00:01<00:00,  3.84it/s]
2026-09-02 13:14:51,016 - INFO - Stopping server!

 1904229Timings avg: 0.2603337287902832

25946/tcp:

,r,s,dist,thumb_rail_emb,thumb_ship_emb
0,dbr:Hathlangoo,dbr:Ngang_Pass,147.8597106934,"{""data"": [0.1213223785161972, 0.67646539211273...","{""data"": [0.266842782497406, 0.282170355319976..."
1,dbr:Playa_Mayabeque,dbr:Welland_Canal,147.4058380127,"{""data"": [0.09042239189147949, 0.0884934589266...","{""data"": [0.14147435128688812, -0.177494421601..."
2,dbr:Sihri,dbr:Speikboden_(South_Tyrol),139.6905670166,"{""data"": [-0.02784011885523796, -0.11094573140...","{""data"": [0.010983843356370926, -0.03950532525..."
3,"dbr:Big_Pine_Key,_Florida",dbr:Japanese_Alps,137.8491210938,"{""data"": [0.013072215020656586, 0.038753185421...","{""data"": [0.03383301943540573, -0.152067333459..."
4,dbr:Deobahal,dbr:Ngang_Pass,136.5958251953,"{""data"": [-0.13472652435302734, 0.181089758872...","{""data"": [0.266842782497406, 0.282170355319976..."
5,"dbr:Sherwood,_Michigan",dbr:Furtbek,136.1393127441,"{""data"": [-0.19389194250106812, -0.00306503474...","{""data"": [-0.2586419880390167, 0.2508565783500..."
6,"dbr:Hubbard_Lake,_Alcona_County,_Michigan",dbr:Welland_Canal,135.5609436035,"{""data"": [-0.1926412433385849, -0.158066034317...","{""data"": [0.14147435128688812, -0.177494421601..."
7,"dbr:Lost_Lake_Woods,_Michigan",dbr:Welland_Canal,135.1779022217,"{""data"": [-0.1862151026725769, -0.135209918022...","{""data"": [0.14147435128688812, -0.177494421601..."
8,"dbr:Natural_Bridge_Station,_Virginia",dbr:Ngang_Pass,134.256149292,"{""data"": [-0.024006932973861694, 0.29700988531...","{""data"": [0.266842782497406, 0.282170355319976..."
9,"dbr:Pepin,_Wisconsin",dbr:Welland_Canal,134.02003479,"{""data"": [0.26799505949020386, 0.0406789481639...","{""data"": [0.14147435128688812, -0.177494421601..."

In [ ]:
with db_qlever as db:
    timings = []
    for _ in tqdm.tqdm(range(5)):
        start = time.time()
        r = db.query_auto(
            query_difficulty=QUERY_DIFFICULTY.HARD,
            query_type=QUERY_TYPE.INDEX,
            tensor=test_tensor,
        )
        end = time.time()
        timings.append(end - start)
print("Timings avg:", sum(timings) / len(timings))
r

2026-05-18 12:42:30,669 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-05-18 12:42:30,669 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt
2026-05-18 12:42:30,670 - WARNING - DB directory ../data/dbpedia/index-encoded already exists!
2026-05-18 12:42:30,671 - INFO - Stopping server!
2026-05-18 12:42:30,726 - ERROR - Command failed with return code 1
2026-05-18 12:42:30,727 - INFO - Starting QLever server on port 25943
2026-05-18 12:42:30,727 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25943 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-05-18 12:42:30,730 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-05-18 12:42:31,732 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-05-18 12:42:32,733 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-05-18 12:42:33,739 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-05-18 12:42:34,759 - INFO - Server is up and responding to queries
100%|██████████| 5/5 [00:06<00:00,  1.25s/it]
2026-05-18 12:42:41,010 - INFO - Stopping server!
2026-05-18 12:42:41,087 - ERROR - Command failed with return code 1

Timings avg: 1.2492853164672852

,r,s,dist,thumb_rail_emb,thumb_ship_emb
0,dbr:Hathlangoo,dbr:Ngang_Pass,147.8597106934,"{""data"": [0.1213223785161972, 0.67646539211273...","{""data"": [0.266842782497406, 0.282170355319976..."
1,dbr:Playa_Mayabeque,dbr:Welland_Canal,147.4058380127,"{""data"": [0.09042239189147949, 0.0884934589266...","{""data"": [0.14147435128688812, -0.177494421601..."
2,dbr:Sihri,dbr:Speikboden_(South_Tyrol),139.6905670166,"{""data"": [-0.02784011885523796, -0.11094573140...","{""data"": [0.010983843356370926, -0.03950532525..."
3,"dbr:Big_Pine_Key,_Florida",dbr:Japanese_Alps,137.8491210938,"{""data"": [0.013072215020656586, 0.038753185421...","{""data"": [0.03383301943540573, -0.152067333459..."
4,dbr:Deobahal,dbr:Ngang_Pass,136.5958251953,"{""data"": [-0.13472652435302734, 0.181089758872...","{""data"": [0.266842782497406, 0.282170355319976..."
5,"dbr:Sherwood,_Michigan",dbr:Furtbek,136.1393127441,"{""data"": [-0.19389194250106812, -0.00306503474...","{""data"": [-0.2586419880390167, 0.2508565783500..."
6,"dbr:Hubbard_Lake,_Alcona_County,_Michigan",dbr:Welland_Canal,135.5609436035,"{""data"": [-0.1926412433385849, -0.158066034317...","{""data"": [0.14147435128688812, -0.177494421601..."
7,"dbr:Lost_Lake_Woods,_Michigan",dbr:Welland_Canal,135.1779022217,"{""data"": [-0.1862151026725769, -0.135209918022...","{""data"": [0.14147435128688812, -0.177494421601..."
8,"dbr:Natural_Bridge_Station,_Virginia",dbr:Ngang_Pass,134.256149292,"{""data"": [-0.024006932973861694, 0.29700988531...","{""data"": [0.266842782497406, 0.282170355319976..."
9,"dbr:Pepin,_Wisconsin",dbr:Welland_Canal,134.02003479,"{""data"": [0.26799505949020386, 0.0406789481639...","{""data"": [0.14147435128688812, -0.177494421601..."

In [29]:
with dbs[0] as db:
    res_native = db.query(f"""
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dtf: <https://w3id.org/rdf-tensor/functions#>
SELECT * WHERE {{
    ?s a dbo:{dataset.left} .
    ?s dbo:thumbnail_embedding ?thumb_emb .
    ?s dbo:thumbnail_original ?thumb .      
    BIND(dtf:dotProduct(?thumb_emb, {test_tensor.to_literal().n3()}) AS ?dist)
}} 
ORDER BY DESC(?dist)
LIMIT 10""")
res_native

2026-09-02 12:58:22,449 - INFO - Setting up QLeverDBNative db_dir=../data/dbpedia/dbpedia/index-encoded, base_dir=scratch/dbpedia
2026-09-02 12:58:22,450 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-09-02 12:58:22,450 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt
2026-09-02 12:58:22,450 - WARNING - DB directory ../data/dbpedia/dbpedia/index-encoded already exists!
2026-09-02 12:58:22,450 - INFO - Stopping server!
2026-09-02 12:58:22,455 - ERROR - Command failed with return code 1
2026-09-02 12:58:22,455 - INFO - Starting QLever server on port 25946
2026-09-02 12:58:22,455 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25946 -k 0 -m 16G --tensor-search-max-num-threads 4

2026-09-02 12:58:22,456 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25946/qlever-with-tidx/sparql)
2026-09-02 12:58:23,456 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25946/qlever-with-tidx/sparql)
2026-09-02 12:58:24,462 - INFO - Server is up and responding to queries
2026-09-02 12:58:25,235 - INFO - Stopping server!

 1879986

25946/tcp:

,s,thumb_emb,thumb,dist
0,dbr:Kundudo,"{""data"": [-0.20942936837673187, 0.028205197304...",http://upload.wikimedia.org/wikipedia/commons/...,28.98929405212
1,dbr:Kundudo,"{""data"": [-0.20942936837673187, 0.028205197304...",https://upload.wikimedia.org/wikipedia/commons...,28.98929405212
2,dbr:Kundudo,"{""data"": [-0.20942936837673187, 0.028205197304...",https://upload.wikimedia.org/wikipedia/commons...,28.98929405212
3,dbr:Ohio_and_Erie_Canal,"{""data"": [-0.17475301027297974, 0.018981928005...",https://upload.wikimedia.org/wikipedia/commons...,28.41627120972
4,dbr:Ohio_and_Erie_Canal,"{""data"": [-0.17475301027297974, 0.018981928005...",http://upload.wikimedia.org/wikipedia/commons/...,28.41627120972
5,dbr:Ohio_and_Erie_Canal,"{""data"": [-0.17475301027297974, 0.018981928005...",http://upload.wikimedia.org/wikipedia/commons/...,28.41627120972
6,dbr:Chesapeake_and_Ohio_Canal,"{""data"": [-0.42376554012298584, 0.671011090278...",https://upload.wikimedia.org/wikipedia/commons...,27.86582565308
7,dbr:Chesapeake_and_Ohio_Canal,"{""data"": [-0.42376554012298584, 0.671011090278...",https://upload.wikimedia.org/wikipedia/commons...,27.86582565308
8,dbr:Chesapeake_and_Ohio_Canal,"{""data"": [-0.42376554012298584, 0.671011090278...",http://upload.wikimedia.org/wikipedia/commons/...,27.86582565308
9,dbr:Chesapeake_and_Ohio_Canal,"{""data"": [-0.42376554012298584, 0.671011090278...",http://upload.wikimedia.org/wikipedia/commons/...,27.86582565308

In [30]:
with dbs[0] as db:
    res =db.query(f"""
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dtf: <https://w3id.org/rdf-tensor/functions#>
PREFIX tensorIndex: <https://qlever.cs.uni-freiburg.de/tensorIndex/>
SELECT * WHERE {{
SERVICE tensorIndex: {{
    _:config tensorIndex:numNN 10 ;
    tensorIndex:left ?query_vector ;
    tensorIndex:bindDistance ?dist ;
    tensorIndex:payload ?s, ?thumb ;
    tensorIndex:searchK 64 ;
    tensorIndex:kIVF 128 ;
    # tensorIndex:experimentalRightCacheName "easy_index_dbpedia" ;
    tensorIndex:right ?thumb_emb ;
    tensorIndex:algorithm tensorIndex:ivf ;
    tensorIndex:distance tensorIndex:dot .
       {{
            ?s a dbo:{dataset.left} ;
            dbo:thumbnail_embedding ?thumb_emb ;
            dbo:thumbnail_original ?thumb .
        }}
    }}
    VALUES (?query_vector) {{ ({test_tensor.to_literal().n3()}) }}
}} 
ORDER BY DESC(?dist)
""")
res

2026-09-02 12:58:34,911 - INFO - Setting up QLeverDBNative db_dir=../data/dbpedia/dbpedia/index-encoded, base_dir=scratch/dbpedia
2026-09-02 12:58:34,912 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-09-02 12:58:34,912 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt
2026-09-02 12:58:34,912 - WARNING - DB directory ../data/dbpedia/dbpedia/index-encoded already exists!
2026-09-02 12:58:34,912 - INFO - Stopping server!
2026-09-02 12:58:34,935 - ERROR - Command failed with return code 1
2026-09-02 12:58:34,936 - INFO - Starting QLever server on port 25946
2026-09-02 12:58:34,936 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25946 -k 0 -m 16G --tensor-search-max-num-threads 4
2026-09-02 12:58:34,937 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25946/qlever-with-tidx/sparql)

2026-09-02 12:58:35,938 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25946/qlever-with-tidx/sparql)
2026-09-02 12:58:36,943 - INFO - Server is up and responding to queries
2026-09-02 12:58:37,580 - INFO - Stopping server!

 1880302

25946/tcp:

,query_vector,dist,s,thumb,thumb_emb
0,"{""data"": [-0.04262261837720871, -0.13338792324...",28.98929023743,dbr:Kundudo,https://upload.wikimedia.org/wikipedia/commons...,"{""data"": [-0.20942936837673187, 0.028205197304..."
1,"{""data"": [-0.04262261837720871, -0.13338792324...",28.98929023743,dbr:Kundudo,https://upload.wikimedia.org/wikipedia/commons...,"{""data"": [-0.20942936837673187, 0.028205197304..."
2,"{""data"": [-0.04262261837720871, -0.13338792324...",28.98929023743,dbr:Kundudo,http://upload.wikimedia.org/wikipedia/commons/...,"{""data"": [-0.20942936837673187, 0.028205197304..."
3,"{""data"": [-0.04262261837720871, -0.13338792324...",28.41626548767,dbr:Ohio_and_Erie_Canal,https://upload.wikimedia.org/wikipedia/commons...,"{""data"": [-0.17475301027297974, 0.018981928005..."
4,"{""data"": [-0.04262261837720871, -0.13338792324...",28.41626548767,dbr:Ohio_and_Erie_Canal,http://upload.wikimedia.org/wikipedia/commons/...,"{""data"": [-0.17475301027297974, 0.018981928005..."
5,"{""data"": [-0.04262261837720871, -0.13338792324...",28.41626548767,dbr:Ohio_and_Erie_Canal,http://upload.wikimedia.org/wikipedia/commons/...,"{""data"": [-0.17475301027297974, 0.018981928005..."
6,"{""data"": [-0.04262261837720871, -0.13338792324...",27.86582565308,dbr:Chesapeake_and_Ohio_Canal,http://upload.wikimedia.org/wikipedia/commons/...,"{""data"": [-0.42376554012298584, 0.671011090278..."
7,"{""data"": [-0.04262261837720871, -0.13338792324...",27.86582565308,dbr:Chesapeake_and_Ohio_Canal,http://upload.wikimedia.org/wikipedia/commons/...,"{""data"": [-0.42376554012298584, 0.671011090278..."
8,"{""data"": [-0.04262261837720871, -0.13338792324...",27.86582565308,dbr:Chesapeake_and_Ohio_Canal,http://upload.wikimedia.org/wikipedia/commons/...,"{""data"": [-0.42376554012298584, 0.671011090278..."
9,"{""data"": [-0.04262261837720871, -0.13338792324...",27.86582565308,dbr:Chesapeake_and_Ohio_Canal,http://upload.wikimedia.org/wikipedia/commons/...,"{""data"": [-0.42376554012298584, 0.671011090278..."

In [41]:
res.to_csv(Path("scratch") / "dbpedia_results_index.csv", index=False)

In [22]:
with dbs[1] as db:
    db.query_auto(test_tensor, query_type=QUERY_TYPE.INDEX, query_difficulty=QUERY_DIFFICULTY.HARD)

2026-05-18 12:42:59,438 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-no-tidx/qlever-no-tidx_run.log
2026-05-18 12:42:59,439 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt
2026-05-18 12:42:59,440 - WARNING - DB directory ../data/dbpedia/index-encoded-no-tidx already exists!
2026-05-18 12:42:59,441 - INFO - Stopping server!
2026-05-18 12:42:59,454 - ERROR - Command failed with return code 1
2026-05-18 12:42:59,455 - INFO - Starting QLever server on port 25844
2026-05-18 12:42:59,455 - INFO - Running command: qlever-server -i dbpedia-encoded --port 25844 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-05-18 12:42:59,458 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25844/qlever-no-tidx/sparql)
2026-05-18 12:43:00,459 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25844/qlever-no-tidx/sparql)
2026-05-18 12:43:01,462 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25844/qlever-no-tidx/sparql)
2026-05-18 12:43:02,465 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25844/qlever-no-tidx/sparql)
2026-05-18 12:43:03,468 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25844/qlever-no-tidx/sparql)
2026-05-18 12:43:04,487 - INFO - Server is up and responding to queries
2026-05-18 12:43:14,984 - INFO - Stopping server!
2026-05-18 12:43:15,036 - ERROR - Command failed with return code 1

In [23]:
from utils.helpers import ndcgscore_query
reference_result = res_native
score = ndcgscore_query(res, reference_result, k=10)
print(f"Score: {score}")

Score: 0.8042472959280005

In [24]:
# count ships


with dbs[0] as db:
    rs =db.query(f"""
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
SELECT (COUNT(*) AS ?count) WHERE {{ 
            ?s a dbo:{dataset.left} ;
            dbo:thumbnail_embedding ?thumb_emb .
}} LIMIT 10""")
    rr =  db.query(f"""PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
SELECT (COUNT(*) AS ?count) WHERE {{ 
            ?s a dbo:{dataset.right} ;
            dbo:thumbnail_embedding ?thumb_emb .
}} LIMIT 10""")
rs.iloc[0], rr.iloc[0]

2026-05-18 12:43:15,939 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-05-18 12:43:15,943 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt
2026-05-18 12:43:15,943 - WARNING - DB directory ../data/dbpedia/index-encoded already exists!
2026-05-18 12:43:15,946 - INFO - Stopping server!

2026-05-18 12:43:16,053 - ERROR - Command failed with return code 1
2026-05-18 12:43:16,054 - INFO - Starting QLever server on port 25943
2026-05-18 12:43:16,056 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25943 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-05-18 12:43:16,058 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-05-18 12:43:17,059 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-05-18 12:43:18,061 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-05-18 12:43:19,063 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-05-18 12:43:20,065 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-05-18 12:43:21,088 - INFO - Server is up and responding to queries
2026-05-18 12:43:21,234 - INFO - Stopping server!
2026-05-18 12:43:21,336 - ERROR - Command failed with return code 1

(count    46351
 Name: 0, dtype: str,
 count    31149
 Name: 0, dtype: str)

In [40]:
# for find similar thumbnails between ships and railroads
times = []
with dbs[0] as db:
    #     warmup = db.query("""
    # PREFIX dbr: <http://dbpedia.org/resource/>
    # PREFIX dbo: <http://dbpedia.org/ontology/>
    # PREFIX tensorIndex: <https://qlever.cs.uni-freiburg.de/tensorIndex/>
    # SELECT * WHERE {
    #     { SELECT * WHERE {
    #         ?r a dbo:Work .
    #         ?r dbo:thumbnail_embedding ?thumb_rail_emb .
    #         ?r dbo:thumbnail_original ?thumb_rail .
    #     } LIMIT 1
    #     }
    #     SERVICE tensorIndex: {
    #     _:config tensorIndex:numNN 10 ;
    #     tensorIndex:left ?thumb_rail_emb ;
    #     tensorIndex:bindDistance ?dist ;
    #     tensorIndex:payload ?s, ?thumb_ship ;
    #     tensorIndex:searchK 1 ;
    #     tensorIndex:nTrees 128 ;
    #     tensorIndex:experimentalRightCacheName "hard_index_dbpedia" ;
    #     tensorIndex:right ?thumb_emb_ship ;
    #     tensorIndex:algorithm tensorIndex:ivf ;
    #     tensorIndex:distance tensorIndex:dot .
    #         {
    #             ?s a dbo:Ship ;
    #             dbo:thumbnail_embedding ?thumb_emb_ship ;
    #             dbo:thumbnail_original ?thumb_ship .
    #         }
    #     }
    #     }""")
    for _ in range(5):
        start = time.time()

        noised_tensor = DataTensor.from_numpy(
            test_tensor.data + np.random.normal(scale=0.001, size=test_tensor.shape)
        )
        railway_ship_assoc = db.query(f"""
    PREFIX dbr: <http://dbpedia.org/resource/>
    PREFIX dbo: <http://dbpedia.org/ontology/>
    PREFIX dtf: <https://w3id.org/rdf-tensor/functions#>
    PREFIX tensorIndex: <https://qlever.cs.uni-freiburg.de/tensorIndex/>
    SELECT DISTINCT ?r ?s  ?dist ?thumb_rail_emb ?thumb_ship_emb WHERE {{
        {{
        SELECT DISTINCT ?r ?s ?dist ?thumb_rail_emb ?thumb_ship_emb WHERE {{
            
            ?r a dbo:{dataset.left} ;
             dbo:thumbnail_embedding ?thumb_rail_emb .
                                        
            SERVICE tensorIndex: {{
            _:config tensorIndex:numNN 1 ;
            tensorIndex:left ?thumb_rail_emb ;
            tensorIndex:bindDistance ?dist ;
            tensorIndex:payload ?s, ?thumb_ship ;
            tensorIndex:searchK 1 ;
            tensorIndex:kIVF 128 ;
            tensorIndex:experimentalRightCacheName "hard_index_dbpedia" ;
            tensorIndex:right ?thumb_ship_emb ;
            tensorIndex:algorithm tensorIndex:ivf ;
            tensorIndex:distance tensorIndex:dot .
            {{
                ?s a dbo:{dataset.right} ;
                dbo:thumbnail_embedding ?thumb_ship_emb ;    
            }}
            }}                  
        }}
        }}
        VALUES (?some_emb) {{ ({noised_tensor.to_literal().n3()}) }}
                                    
    }}
    ORDER BY DESC(?dist)
    LIMIT 20""")
        end = time.time()
        delta = end - start
        times.append(delta)
times

2026-09-02 13:06:59,100 - INFO - Setting up QLeverDBNative db_dir=../data/dbpedia/dbpedia/index-encoded, base_dir=scratch/dbpedia
2026-09-02 13:06:59,101 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-09-02 13:06:59,101 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt
2026-09-02 13:06:59,101 - WARNING - DB directory ../data/dbpedia/dbpedia/index-encoded already exists!
2026-09-02 13:06:59,102 - INFO - Stopping server!
2026-09-02 13:06:59,107 - ERROR - Command failed with return code 1
2026-09-02 13:06:59,107 - INFO - Starting QLever server on port 25946
2026-09-02 13:06:59,107 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25946 -k 0 -m 16G --tensor-search-max-num-threads 4

2026-09-02 13:06:59,108 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25946/qlever-with-tidx/sparql)
2026-09-02 13:07:00,109 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25946/qlever-with-tidx/sparql)
2026-09-02 13:07:01,114 - INFO - Server is up and responding to queries
2026-09-02 13:07:31,125 - INFO - Stopping server!

 1893142

25946/tcp:

TimeoutError:

In [34]:
railway_ship_assoc

NameError: name 'railway_ship_assoc' is not defined

In [26]:
with db_qlever as db:
    hard_results = db.query(
        f"""
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dtf: <https://w3id.org/rdf-tensor/functions#>
PREFIX tensorIndex: <https://qlever.cs.uni-freiburg.de/tensorIndex/>
SELECT DISTINCT ?l ?r ?dist ?thumb_left ?thumb_right ?thumb_left_emb ?thumb_right_emb WHERE {{
    {{
    SELECT DISTINCT ?l ?r ?dist ?thumb_left ?thumb_right ?thumb_left_emb ?thumb_right_emb WHERE {{

        ?l a dbo:{dataset.left} .
        ?l dbo:thumbnail_embedding ?thumb_left_emb .
        ?l dbo:thumbnail ?thumb_left .

        SERVICE tensorIndex: {{
        _:config tensorIndex:numNN 1 ;
        tensorIndex:left ?thumb_left_emb ;
        tensorIndex:bindDistance ?dist ;
        tensorIndex:payload ?r, ?thumb_right_emb, ?thumb_right ;
        tensorIndex:searchK 1 ;
        tensorIndex:kIVF 512 ;
        tensorIndex:experimentalRightCacheName "hard_index_dbpedia" ;
        tensorIndex:right ?thumb_right_emb ;
        tensorIndex:algorithm tensorIndex:ivf ;
        tensorIndex:distance tensorIndex:dot .
        {{
            ?r a dbo:{dataset.right} ;
            dbo:thumbnail_embedding ?thumb_right_emb ;
            dbo:thumbnail ?thumb_right .
        }}
        }}
    }}
    }}
}}
ORDER BY DESC(?dist)
LIMIT 5"""
    )
    #     # hard_results = db.query_auto(
    #     #     test_tensor, query_type=QUERY_TYPE.INDEX, query_difficulty=QUERY_DIFFICULTY.HARD
    #     # )
    easy_results = db.query(f"""
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dtf: <https://w3id.org/rdf-tensor/functions#>
PREFIX tensorIndex: <https://qlever.cs.uni-freiburg.de/tensorIndex/>
SELECT DISTINCT ?l ?thumb_emb ?dist ?thumb WHERE {{
SERVICE tensorIndex: {{
    _:config tensorIndex:numNN 10 ;
    tensorIndex:left ?query_vector ;
    tensorIndex:bindDistance ?dist ;
    tensorIndex:payload ?l, ?thumb_emb, ?thumb ;
    tensorIndex:searchK 1 ;
    tensorIndex:experimentalRightCacheName "easy_index_dbpedia" ;
    tensorIndex:right ?thumb_emb ;
    tensorIndex:algorithm tensorIndex:ivf ;
    tensorIndex:distance tensorIndex:dot .
       {{
            ?l a dbo:{dataset.left} ;
            dbo:thumbnail_embedding ?thumb_emb ;
            dbo:thumbnail ?thumb .
        }}
    }}
VALUES (?query_vector) {{ ({test_tensor.to_literal().n3()}) }}
}} 
ORDER BY DESC(?dist)
                            """)

2026-05-18 12:43:28,160 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-05-18 12:43:28,161 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt
2026-05-18 12:43:28,162 - WARNING - DB directory ../data/dbpedia/index-encoded already exists!
2026-05-18 12:43:28,162 - INFO - Stopping server!
2026-05-18 12:43:28,211 - ERROR - Command failed with return code 1
2026-05-18 12:43:28,212 - INFO - Starting QLever server on port 25943
2026-05-18 12:43:28,212 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25943 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-05-18 12:43:28,214 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-05-18 12:43:29,217 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-05-18 12:43:30,220 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-05-18 12:43:31,228 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-05-18 12:43:32,232 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-05-18 12:43:33,249 - INFO - Server is up and responding to queries
2026-05-18 12:43:42,117 - INFO - Stopping server!
2026-05-18 12:43:42,219 - ERROR - Command failed with return code 1

In [27]:
hard_results.to_csv(Path("scratch") / "dbpedia_hard_results.csv", index=False)
hard_results

,l,r,dist,thumb_left,thumb_right,thumb_left_emb,thumb_right_emb
0,dbr:Ngang_Pass,dbr:Hathlangoo,147.8597106934,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,"{""data"": [0.266842782497406, 0.282170355319976...","{""data"": [0.1213223785161972, 0.67646539211273..."
1,dbr:Welland_Canal,dbr:Playa_Mayabeque,147.4058380127,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,"{""data"": [0.14147435128688812, -0.177494421601...","{""data"": [0.09042239189147949, 0.0884934589266..."
2,dbr:Speikboden_(South_Tyrol),dbr:Playa_Mayabeque,143.0099334717,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,"{""data"": [0.010983843356370926, -0.03950532525...","{""data"": [0.09042239189147949, 0.0884934589266..."
3,dbr:Rim_(crater),dbr:Playa_Mayabeque,140.2051239014,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,"{""data"": [-0.09978093951940536, 0.058597564697...","{""data"": [0.09042239189147949, 0.0884934589266..."
4,dbr:Wittstrauch,dbr:Hathlangoo,139.259979248,http://commons.wikimedia.org/wiki/Special:File...,http://commons.wikimedia.org/wiki/Special:File...,"{""data"": [0.19549092650413513, 0.1191306039690...","{""data"": [0.1213223785161972, 0.67646539211273..."

In [28]:
easy_results.to_csv(Path("scratch") / "dbpedia_easy_results.csv", index=False)
easy_results

,l,thumb_emb,dist,thumb
0,dbr:Swin_(Thames),"{""data"": [0.3809254765510559, -0.0876748263835...",27.77111434937,http://commons.wikimedia.org/wiki/Special:File...
1,dbr:Lake_Balaton,"{""data"": [0.18073731660842896, -0.051469188183...",27.32340812683,http://commons.wikimedia.org/wiki/Special:File...
2,dbr:Lake_Balaton,"{""data"": [0.3280792236328125, 0.13119816780090...",26.78946304321,http://commons.wikimedia.org/wiki/Special:File...
3,dbr:North_Sea,"{""data"": [0.22238808870315552, -0.094367086887...",26.64107513428,http://commons.wikimedia.org/wiki/Special:File...
4,dbr:Lennox_Passage_(waterway),"{""data"": [0.23200394213199615, -0.242229431867...",26.32609176636,http://commons.wikimedia.org/wiki/Special:File...
5,dbr:Gulf_of_Thailand,"{""data"": [0.510789692401886, -0.14017504453659...",26.1806640625,http://commons.wikimedia.org/wiki/Special:File...
6,dbr:Sproat_Lake,"{""data"": [0.5528449416160583, 0.43867826461791...",26.17969512939,http://commons.wikimedia.org/wiki/Special:File...
7,dbr:Pulicat_Lake,"{""data"": [0.6338863372802734, 0.07557176053524...",26.14479255676,http://commons.wikimedia.org/wiki/Special:File...
8,dbr:Chao_Phraya_River,"{""data"": [0.5662512183189392, 0.35592082142829...",25.5197429657,http://commons.wikimedia.org/wiki/Special:File...
9,dbr:Gulf_of_Mexico,"{""data"": [0.28293147683143616, -0.315052270889...",25.28795051575,http://commons.wikimedia.org/wiki/Special:File...

In [29]:
easy_results.loc[0, "s"], easy_results.loc[0, "thumb_emb"], easy_results.loc[0, "dist"]

KeyError: 's'

In [ ]:
hard_results

,r,s,dist,thumb_work_emb,thumb_settlement_emb
0,dbr:Chengdu_Metro,dbr:Virginia-class_submarine,149.7560424805,"{""data"": [0.22622768580913544, 0.0546032562851...","{""data"": [-0.1000426858663559, -0.080208711326..."
1,dbr:Taipa_line,dbr:Virginia-class_submarine,148.5401763916,"{""data"": [0.03102342039346695, -0.059559382498...","{""data"": [-0.1000426858663559, -0.080208711326..."
2,dbr:Yangluo_Line,dbr:Virginia-class_submarine,146.5701904297,"{""data"": [0.13836224377155304, 0.1058328151702...","{""data"": [-0.1000426858663559, -0.080208711326..."
3,dbr:Buenos_Aires_Underground,dbr:Virginia-class_submarine,140.4429473877,"{""data"": [-0.057316623628139496, -0.1589123308...","{""data"": [-0.1000426858663559, -0.080208711326..."
4,dbr:Line_13_(CPTM),dbr:Virginia-class_submarine,139.5857849121,"{""data"": [-0.21847796440124512, -0.04886087775...","{""data"": [-0.1000426858663559, -0.080208711326..."
5,dbr:Orlyval,dbr:Virginia-class_submarine,138.4967041016,"{""data"": [0.11910116672515869, -0.394591093063...","{""data"": [-0.1000426858663559, -0.080208711326..."
6,dbr:Abbey_Line,dbr:Virginia-class_submarine,137.7716217041,"{""data"": [0.17977674305438995, -0.300230383872...","{""data"": [-0.1000426858663559, -0.080208711326..."
7,dbr:Kolkata_Metro,dbr:Virginia-class_submarine,137.671875,"{""data"": [-0.012433663010597229, -0.1900815814...","{""data"": [-0.1000426858663559, -0.080208711326..."
8,dbr:London_Overground,dbr:Virginia-class_submarine,137.6464233398,"{""data"": [0.02959146350622177, 0.0380432158708...","{""data"": [-0.1000426858663559, -0.080208711326..."
9,dbr:CDGVAL,dbr:Virginia-class_submarine,135.4984130859,"{""data"": [-0.17296558618545532, 0.003928374499...","{""data"": [-0.1000426858663559, -0.080208711326..."

In [ ]:
# load images for both results
from utils.dbs.base_db import BaseDB


def enhance_col_with_thumbs(
    db: BaseDB, df: pd.DataFrame, dbr_col: str, thumb_col_name="thumb"
) -> pd.DataFrame:

    thumbs = []
    g = tqdm.tqdm(df[dbr_col], desc=f"Fetching thumbnails for {thumb_col_name}")
    for s in g:
        g.set_description(f"Fetching thumbnails for {thumb_col_name}: '{s}'")
        s = f"<{s.replace('dbr:', 'http://dbpedia.org/resource/')}>"
        res = db.query(f"""PREFIX dbr: <http://dbpedia.org/resource/>
                            PREFIX dbo: <http://dbpedia.org/ontology/>
                            SELECT ?thumb ?thumb_lc WHERE {{
                                {s} dbo:thumbnail_original ?thumb .
                                BIND (LCASE(STR(?thumb)) AS ?thumb_lc) 
                                FILTER (STRENDS(?thumb_lc, ".png") || STRENDS(?thumb_lc, ".jpg") || STRENDS(?thumb_lc, ".jpeg"))
                            }} LIMIT 1""")
        # print(f"Query result for {s}: {res}")
        if len(res) > 0:
            thumbs.append(res["thumb"].values[0])
        else:
            thumbs.append(None)
    df[thumb_col_name] = thumbs
    return df


with db_qlever as db:
    easy_results = enhance_col_with_thumbs(db, easy_results, "s")
    hard_results = enhance_col_with_thumbs(
        db, hard_results, "s", thumb_col_name="thumb_s"
    )
    hard_results = enhance_col_with_thumbs(
        db, hard_results, "r", thumb_col_name="thumb_r"
    )

2026-04-27 15:54:17,241 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-04-27 15:54:17,242 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt.gz
2026-04-27 15:54:17,243 - WARNING - DB directory ../data/dbpedia/index-encoded already exists!
2026-04-27 15:54:17,244 - INFO - Stopping server!
2026-04-27 15:54:17,314 - ERROR - Command failed with return code 1
2026-04-27 15:54:17,315 - INFO - Starting QLever server on port 25943
2026-04-27 15:54:17,315 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25943 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-27 15:54:17,318 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:54:18,319 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:54:19,321 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:54:20,323 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-27 15:54:21,335 - INFO - Server is up and responding to queries
Fetching thumbnails for thumb: 'dbr:SB_Mirosa': 100%|██████████| 10/10 [00:00<00:00, 131.22it/s]
Fetching thumbnails for thumb_s: 'dbr:Virginia-class_submarine': 100%|██████████| 10/10 [00:00<00:00, 151.42it/s]
Fetching thumbnails for thumb_r: 'dbr:CDGVAL': 100%|██████████| 10/10 [00:00<00:00, 155.26it/s]
2026-04-27 15:54:21,550 - INFO - Stopping server!
2026-04-27 15:54:21,621 - ERROR - Command failed with return code 1

In [ ]:
easy_results.loc[0, 'thumb'].split('/')[-1]

'HMS_Warrior_Pembroke_Dock_July_1977_B.jpg'

## Token

You need to set your Oauth tokens in the local `.env`:
```sh
MEDIA_WIKI_TOKEN="..."
MEDIA_WIKI_SECRET="..."
MEDIA_WIKI_ACCESS_TOKEN="..."
MEDIA_WIKI_ACCESS_SECRET="..."
```
You can register a new token [here](https://meta.wikimedia.org/wiki/Special:OAuthConsumerRegistration/propose/oauth1a).

In [ ]:
import requests
from requests_oauthlib import OAuth1
import dotenv
from utils.datasets.dbpedia_utils.helpers import USER_AGENT

dotenv.load_dotenv()  # to load MEDIAWIKI_TOKEN from .env file

auth = OAuth1(
    os.getenv("MEDIA_WIKI_TOKEN"),
    os.getenv("MEDIA_WIKI_SECRET"),
    os.getenv("MEDIA_WIKI_ACCESS_TOKEN"),
    os.getenv("MEDIA_WIKI_ACCESS_SECRET"),
)

In [ ]:
auth.client

<Client client_key=eea9f51d9008d744c272c3ece851b184, client_secret=****, resource_owner_key=914b284deef1f1f0525ea803d55914b0, resource_owner_secret=****, signature_method=HMAC-SHA1, signature_type=AUTH_HEADER, callback_uri=None, rsa_key=None, verifier=None, realm=None, encoding=utf-8, decoding=utf-8, nonce=None, timestamp=None>

In [ ]:
url=f"https://commons.wikimedia.org/wiki/Special:FilePath/{easy_results.loc[0, 'thumb'].split('/')[-1]}?width=330"
resp = requests.get(
    url,
    auth=auth,
    headers={"User-Agent": USER_AGENT},
)

In [ ]:
import pywikibot

pywikibot.config.usernames['commons']['commons'] = "Dakantz"
# set user-agent

authenticate = (
    os.getenv("MEDIA_WIKI_TOKEN"),
    os.getenv("MEDIA_WIKI_SECRET"),
    os.getenv("MEDIA_WIKI_ACCESS_TOKEN"),
    os.getenv("MEDIA_WIKI_ACCESS_SECRET"),
)
pywikibot.config.authenticate['commons.wikimedia.org'] = authenticate
pywikibot.config.user_agent = USER_AGENT
site = pywikibot.Site('commons', 'commons')
site.login()

In [ ]:
site.allimages()

In [ ]:
from PIL import Image
fname = easy_results.loc[0, "thumb"].split("/")[-1]
img = pywikibot.FilePage(site, fname)

img.download(filename=fname, url_width=330)
img = Image.open(fname)

In [ ]:
from utils.datasets.dbpedia_utils import image_formatter


def thumbs_to_pil(
    thumbs: pd.Series, scratch_dir=Path("../scratch/dbpedia_thumbs")
) -> pd.Series:

    scratch_dir.mkdir(parents=True, exist_ok=True)
    pil_images = []
    g = tqdm.tqdm(thumbs, desc="Fetching thumbnails")
    for thumb in g:
        g.set_description(f"Fetching thumbnail for {thumb}...")
        # url_thumb = get_wc_thumb(thumb)

        fname = thumb.split("/")[-1]
        out_f = scratch_dir / fname
        if not out_f.exists():
            img = pywikibot.FilePage(site, fname)
            img.download(filename=out_f, url_width=330)
        img = Image.open(out_f)
        pil_images.append(img)
    return pd.Series(pil_images, index=thumbs.index)


easy_results["thumb_img"] = thumbs_to_pil(easy_results["thumb"])
hard_results["thumb_s_img"] = thumbs_to_pil(hard_results["thumb_s"])
hard_results["thumb_r_img"] = thumbs_to_pil(hard_results["thumb_r"])

Fetching thumbnail for https://upload.wikimedia.org/wikipedia/commons/2/23/HMS_Warrior_Pembroke_Dock_July_1977_B.jpg...:   0%|          | 0/10 [00:00<?, ?it/s]

Fetching thumbnail for http://upload.wikimedia.org/wikipedia/commons/0/0d/SS_Great_Britain_diagram.jpg...:  40%|████      | 4/10 [00:08<00:12,  2.15s/it]              WARNING: Http response status 429
WARNING: Unsuccessful request (429): https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/SS_Great_Britain_diagram.jpg/330px-SS_Great_Britain_diagram.jpg
Fetching thumbnail for http://upload.wikimedia.org/wikipedia/commons/0/0d/SS_Great_Britain_diagram.jpg...:  40%|████      | 4/10 [00:11<00:16,  2.79s/it]

FileNotFoundError: [Errno 2] No such file or directory: '../scratch/dbpedia_thumbs/SS_Great_Britain_diagram.jpg'

In [ ]:
out_dir = Path("../scratch/results/")


def to_tex_with_thumbs(
    df,
    t_cols=["thumb_img"],
    col_mapping={
        "s": "Ship",
        "r": "Railway",
        "thumb_img_tex": "Thumbnail",
        "dist": "Distance",
    },
    base_dir="figures/generated",
    sub_dir="dbpedia/media",
    out_name="dbpedia_easy_results.tex",
    col_format ="lp{3cm}r"
):
    out_dir.mkdir(parents=True, exist_ok=True)
    results_dir = Path(out_dir) / sub_dir
    results_dir.mkdir(parents=True, exist_ok=True)
    fig_dir = Path(base_dir) / sub_dir
    for t_col in t_cols:
        df[f"{t_col}_tex"] = df[t_col]
        
        for i, r in df.iterrows():
            if r[t_col] is not None and isinstance(r[t_col], Image.Image):
                fname = f"{t_col}_{i}.png"
                fig_file = fig_dir / fname
                im_file = results_dir / fname
                df.at[i, f"{t_col}_tex"] = f"\\includegraphics[width=3cm]{{{fig_file}}}"
                print(f"Saving image for row {i} to {im_file} and referencing as {fig_file} in LaTeX", r[t_col])
                img: Image = r[t_col]
                img.save(im_file)
            else:
                df.at[i, f"{t_col}_tex"] = "No image"
    df_renamed = df.rename(columns=col_mapping)
    print(f"Renamed columns for LaTeX: {df_renamed.columns}")
    allowed_cols = [c for c in list(col_mapping.values()) if c in df_renamed.columns]
    print(f"Allowed columns for LaTeX output: {allowed_cols}")
    df_renamed = df_renamed[allowed_cols]
    df_renamed.set_index(allowed_cols[0], inplace=True)
    df_renamed.style.to_latex(
        buf= results_dir / out_name,
        column_format=col_format,
    )


to_tex_with_thumbs(easy_results)

Saving image for row 0 to ../scratch/results/dbpedia/media/thumb_img_0.png and referencing as figures/generated/dbpedia/media/thumb_img_0.png in LaTeX <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=330x247 at 0x7FF50012B5C0>
Saving image for row 1 to ../scratch/results/dbpedia/media/thumb_img_1.png and referencing as figures/generated/dbpedia/media/thumb_img_1.png in LaTeX <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=330x217 at 0x7FF500128050>
Saving image for row 2 to ../scratch/results/dbpedia/media/thumb_img_2.png and referencing as figures/generated/dbpedia/media/thumb_img_2.png in LaTeX <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=330x250 at 0x7FF4FBFE3360>
Renamed columns for LaTeX: Index(['Ship', 'thumb_emb', 'Distance', 'thumb', 'thumb_img', 'Thumbnail'], dtype='str')
Allowed columns for LaTeX output: ['Ship', 'Thumbnail', 'Distance']