In [72]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [73]:
import tqdm
import sys
import os
import pandas as pd
import time

In [74]:
from sentence_transformers import SentenceTransformer

encoding_model = SentenceTransformer("clip-ViT-B-32")

2026-04-24 15:40:52,213 - INFO - Use pytorch device_name: cpu
2026-04-24 15:40:52,214 - INFO - Load pretrained SentenceTransformer: clip-ViT-B-32
2026-04-24 15:40:52,389 - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/clip-ViT-B-32/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-04-24 15:40:52,402 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/clip-ViT-B-32/327ab6726d33c0e22f920c83f2ff9e4bd38ca37f/modules.json "HTTP/1.1 200 OK"
2026-04-24 15:40:52,531 - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/clip-ViT-B-32/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-04-24 15:40:52,550 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/clip-ViT-B-32/327ab6726d33c0e22f920c83f2ff9e4bd38ca37f/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-04-24 15:40:52,678 - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/clip-ViT-B-32/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-04-24 15:40:52,693 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/clip-ViT-B-32/327ab6726d33c0e22f920c83f2ff9e4bd38ca37f/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-04-24 15:40:52,822 - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/clip-ViT-B-32/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-04-24 15:40:52,834 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/clip-ViT-B-32/327ab6726d33c0e22f920c83f2ff9e4bd38ca37f/README.md "HTTP/1.1 200 OK"
2026-04-24 15:40:52,965 - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/clip-ViT-B-32/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-04-24 15:40:52,979 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/clip-ViT-B-32/327ab6726d33c0e22f920c83f2ff9e4bd38ca37f/modules.json "HTTP/1.1 200 OK"
2026-04-24 15:40:53,111 - INFO - HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/clip-ViT-B-32/revision/main "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

CLIPModel LOAD REPORT from: /home/kantz/.cache/huggingface/hub/models--sentence-transformers--clip-ViT-B-32/snapshots/327ab6726d33c0e22f920c83f2ff9e4bd38ca37f/0_CLIPModel
Key                                  | Status     |  |
-------------------------------------+------------+--+-
text_model.embeddings.position_ids   | UNEXPECTED |  |
vision_model.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-04-24 15:40:53,599 - INFO - HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/clip-ViT-B-32 "HTTP/1.1 200 OK"

In [75]:
import dotenv
import os

config = dotenv.dotenv_values(".env")
replace_keys = ["JAVA_HOME", "FUSEKI_HOME"]
append_keys = ["PATH"]
for key, value in config.items():
    # append to os.environ
    if key in append_keys:
        os.environ[key] = f"{os.environ.get(key, '')}:{value}"
    elif key in replace_keys:
        os.environ[key] = value

# check and compare values in fuseki log
os.environ["OPENBLAS_NUM_THREADS"] = "4"

In [76]:
sys.path.append("..")

In [77]:
from utils.datasets import DBPedia
from utils.dbs.qlever_native import QleverDBNative
from utils.dbs.fuseki_native import FusekiDBNative
from utils.datasets.base_dataset import QUERY_DIFFICULTY, QUERY_TYPE
from pathlib import Path
import numpy as np
from utils.datasets.base_dataset import DataTensor

In [78]:
dataset = DBPedia(base_dir=Path("../data/dbpedia"))

In [79]:
test_label = "horse on the bow"
test_tensor = DataTensor.from_numpy(encoding_model.encode(test_label))

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [80]:
test_tensor.to_literal().n3()

'"{\\"data\\": [-0.04262268915772438, -0.1333884298801422, 0.08612467348575592, -0.02091798186302185, -0.15041583776474, 0.1737712323665619, -0.348517507314682, -0.9152146577835083, -0.3341490924358368, 0.17787908017635345, 0.05680551752448082, -0.20725640654563904, 0.5095284581184387, 0.18332251906394958, 0.11725624650716782, 0.1168459951877594, 0.20500661432743073, -0.1478302776813507, -0.007135884836316109, 0.4961417019367218, 0.3664361536502838, 0.41410648822784424, -0.04107498377561569, 0.5009220838546753, -0.2138804793357849, -0.23931393027305603, -0.7052134275436401, 0.4793880879878998, -0.17963360249996185, 0.2792432904243469, -0.06826944649219513, 0.0803503543138504, -0.20019735395908356, 0.25140535831451416, -0.16235408186912537, 0.1176009476184845, 0.10282524675130844, 0.20387926697731018, -0.04952261596918106, 0.26974374055862427, 0.13957971334457397, 0.5327335596084595, 0.12486020475625992, -0.08572806417942047, 0.1065823957324028, -0.06904290616512299, 0.19244082272052765, 0.004055921919643879, -0.016175957396626472, 0.14999307692050934, 0.058157339692115784, -0.2949751913547516, -0.30239489674568176, 0.2556452751159668, -0.056346990168094635, 0.0034323800355196, -0.24107672274112701, 0.266265332698822, -0.21348032355308533, 0.401064395904541, 0.2964056432247162, 0.0030471496284008026, 0.0780687928199768, -0.10076116770505905, 0.12922954559326172, -0.0007172836922109127, -0.07724957168102264, 0.15974968671798706, 0.13473500311374664, 0.002694841008633375, 0.043134912848472595, 0.01628531515598297, 0.28354209661483765, -0.022883642464876175, 0.09224116057157516, -0.5340399742126465, -0.23960845172405243, 0.12176563590765, -0.34699109196662903, 0.05000511556863785, 0.062218617647886276, 0.1143401563167572, -0.01417964044958353, 0.5364919304847717, 0.2277376502752304, -0.029826924204826355, -0.34357592463493347, -0.10327602177858353, -0.0889338031411171, 0.36991357803344727, 0.012964829802513123, -0.07436607033014297, -1.309548258781433, 0.44614243507385254, 0.018672700971364975, -0.2529124319553375, 0.28713902831077576, 0.01675035059452057, 0.035857703536748886, -0.22998324036598206, -0.14083877205848694, -0.07106801122426987, -0.09642128646373749, 0.21655051410198212, 0.09358265995979309, 0.23318399488925934, -0.15376906096935272, 0.27460137009620667, -0.21038588881492615, 0.3248600959777832, -0.1732352375984192, 0.014894681051373482, -0.039007216691970825, 0.1811979115009308, -0.31202074885368347, -0.11454087495803833, -0.16019298136234283, -0.08498432487249374, 0.3788904845714569, -0.1883203685283661, -0.07226619124412537, -0.9254443645477295, -0.18329882621765137, -0.06734245270490646, 0.2413122057914734, -0.164064422249794, -0.3879578113555908, -0.2547023594379425, 0.14271141588687897, 0.39550554752349854, -0.13101597130298615, -0.45052370429039, -0.08015789091587067, 4.995395660400391, -0.23945783078670502, -0.37153586745262146, -0.29315686225891113, 0.08353441953659058, 0.10397690534591675, -0.24532519280910492, -0.29608869552612305, 0.0728289932012558, -0.19765496253967285, 0.2663191854953766, 0.1443239003419876, 0.06140514463186264, -0.0636756494641304, -0.136429563164711, -0.37929514050483704, 0.040126048028469086, 0.20846030116081238, -0.046803634613752365, -0.09697604179382324, 0.2885654866695404, -0.13826711475849152, -0.4298671782016754, 0.454520046710968, -0.3830225467681885, -0.2549723982810974, 0.1788555532693863, 0.07007404416799545, 0.14401200413703918, -0.02052035927772522, -0.06321345269680023, 0.14143216609954834, -0.002827470190823078, 0.13198769092559814, -0.4338044226169586, 0.31351831555366516, -0.015382522717118263, 0.03972843289375305, -0.11416905373334885, 0.32447728514671326, -0.08284606039524078, -0.2795880436897278, 0.33499065041542053, -0.13286051154136658, 0.1413523107767105, 0.1438053846359253, 0.4994203448295593, -0.12618792057037354, 0.13858260214328766, -0.1577799767255783, -0.24153682589530945, 0.3336068093776703, 0.11076335608959198, 0.27649617195129395, 0.19507920742034912, -0.3491799235343933, 0.10086368024349213, -0.1947011947631836, 0.14734765887260437, -0.1792561113834381, -0.2404884546995163, -0.20638126134872437, 0.1594625562429428, -0.2064419835805893, 0.4686662256717682, 0.1224103569984436, -0.1929231882095337, -0.3304961621761322, -0.15453074872493744, 0.3289383053779602, -0.19276845455169678, -0.1419120728969574, 0.036372654139995575, -0.032568495720624924, -0.2757578194141388, -0.17087632417678833, -0.3603208363056183, 0.3550761640071869, 0.07408803701400757, 0.16397617757320404, 0.4174465537071228, 0.03409815952181816, 0.015406325459480286, 0.14059369266033173, -0.2836103141307831, 0.04072924703359604, -0.13061843812465668, 0.08163174986839294, -0.24610236287117004, 0.09389635920524597, -0.24005071818828583, 0.13519728183746338, 0.0464361235499382, 0.22132527828216553, 0.02697714976966381, -0.08397431671619415, 0.23355722427368164, 0.07472678273916245, -0.07733243703842163, -0.08717343956232071, -0.056425370275974274, 0.3738686144351959, 0.03457840532064438, 0.3578338623046875, 0.1249217838048935, -0.3770174980163574, -0.02174508571624756, 0.3847891688346863, -0.31229445338249207, 0.24248838424682617, 0.1730431318283081, 0.21590428054332733, 0.028434207662940025, -0.04749997705221176, -0.354280561208725, 0.2951468825340271, 0.03223574534058571, -0.33378469944000244, 0.5995599031448364, 0.16036856174468994, 0.37374818325042725, -0.27309471368789673, 0.47794461250305176, 0.27809959650039673, 0.07505334913730621, 0.04588694125413895, 0.44692400097846985, -0.061994630843400955, -0.01789759285748005, 0.02898450754582882, -0.17852738499641418, -0.270717054605484, 0.05693190172314644, -0.0238601416349411, -0.1925913393497467, -0.3413273096084595, -0.1934177130460739, -0.30758562684059143, -0.2947530746459961, 0.26107990741729736, 0.1175401359796524, -0.0725201964378357, -0.029527168720960617, -0.37710872292518616, 0.06373333930969238, 0.3712431788444519, 0.16918398439884186, -0.1874537318944931, 0.09985712170600891, 0.10260182619094849, 0.20361138880252838, 0.014345571398735046, 0.5188203454017639, 0.16811496019363403, 0.25370705127716064, 0.11705280840396881, -0.05278034880757332, 0.03722261264920235, 0.3069724142551422, -0.3166779577732086, 0.3612406551837921, -0.3461386263370514, 0.14271120727062225, -0.4891326129436493, -0.031868647783994675, -0.2105318009853363, -0.10849712789058685, 0.5024760365486145, -0.42960524559020996, 0.09099404513835907, 0.10781149566173553, -0.08149893581867218, -0.36489272117614746, -0.19751374423503876, 0.4677923619747162, -0.19604173302650452, -0.5108305215835571, 0.04228796809911728, 0.40673041343688965, 4.982846260070801, 0.2281806766986847, 0.07898621261119843, 0.015636280179023743, 0.10525976121425629, -0.24056093394756317, 0.1307922601699829, 0.11874490231275558, 0.16272300481796265, 0.33506906032562256, 0.12341885268688202, 0.23444749414920807, 0.0751492977142334, 0.4529761075973511, -0.09843146800994873, -0.0868949443101883, 0.15630561113357544, -1.9064604043960571, 0.1436811089515686, -0.0647597685456276, 0.10218008607625961, 0.22556403279304504, -0.1312151700258255, 0.08798596262931824, -0.316336065530777, 0.08733700215816498, 0.4364594519138336, -0.0841616541147232, -0.12824013829231262, 0.17684020102024078, 0.0005449578166007996, -0.4466038644313812, 0.2596926987171173, -0.04485166817903519, 0.36150938272476196, 0.29519420862197876, -0.13554643094539642, 0.17567718029022217, -0.04864608496427536, 0.09418146312236786, 0.11930356919765472, -0.1689140498638153, -0.07621348649263382, -0.04019908607006073, 0.025453871116042137, -0.04131506010890007, 0.613564133644104, 0.17166201770305634, 0.19252869486808777, -0.1529507040977478, -0.3212543725967407, 0.29930058121681213, 0.183676615357399, 0.256805956363678, -0.348125159740448, -0.24246308207511902, -0.15343236923217773, 0.045282796025276184, 0.12715944647789001, 0.1002541035413742, 0.3344520628452301, 0.12696677446365356, -0.03679069131612778, 0.08682677894830704, 0.027234166860580444, 0.12669570744037628, -0.14569342136383057, -0.11954189836978912, 0.005335235968232155, -0.023069556802511215, 0.12944917380809784, -0.5794199705123901, 0.4554336667060852, 0.26931557059288025, -0.14136828482151031, 0.16985487937927246, 0.035368259996175766, -0.21738597750663757, -0.19395196437835693, -0.2554394602775574, 0.036201342940330505, 0.0026678694412112236, 0.03341682255268097, -0.00012027658522129059, -0.20584441721439362, -0.2441178858280182, -0.29085585474967957, 0.6269326210021973, -0.07581208646297455, 0.01799778640270233, 0.26985567808151245, -0.18378271162509918, -0.21640625596046448, 0.07882273197174072, 0.11399638652801514, 0.16782686114311218, 0.1454664021730423, -0.14690759778022766, 0.5914286375045776, -0.06359510123729706, -0.4243270754814148, 0.419055312871933, 0.03688973933458328, 0.09080688655376434, -0.20464570820331573, -0.23673778772354126, 0.12423155456781387, -0.3539251387119293, -0.05117426812648773, -0.33227285742759705, 0.09913495182991028, -0.5108201503753662, 0.2183261215686798, 0.14858272671699524, -0.03194478526711464, -0.2500399053096771, 0.3474576473236084, -0.08445319533348083, 0.05256013572216034, 0.12885384261608124, 0.05474567040801048, 0.28207558393478394, 0.24913564324378967, 0.017554350197315216, -0.04651769623160362, -0.21744558215141296, -0.5378966331481934, 0.35821494460105896, 0.02395261451601982, 0.2269265353679657, -0.48503151535987854, -0.4348192811012268, 0.2893373370170593, 0.13147799670696259, 0.30677375197410583, -0.38510605692863464, 0.22093357145786285, 0.26399722695350647, -0.49346867203712463, 0.10722221434116364, 0.004673405550420284, -0.2786339819431305, 0.13793890178203583, -0.049813125282526016, -0.258821964263916, 0.336711049079895, 0.19765441119670868, -0.09453567862510681, 0.01727696880698204, 0.10990896075963974, 0.5079712271690369, 0.18238453567028046, 0.29509949684143066, 0.0021931459195911884, 0.44314414262771606, -0.1369258612394333, 0.03231927752494812, -0.013810236006975174, -0.1325978934764862, -0.40534934401512146, 0.30387064814567566, -0.31678539514541626, -0.06312119215726852, 0.35880550742149353, -0.14602607488632202, 0.23039574921131134, -0.10129227489233017, 0.4284210801124573, -0.21266235411167145, -0.38488680124282837, 0.3961750268936157, -0.13077367842197418, 0.2837107181549072, -0.4066965579986572, -0.28119900822639465, -0.12295553833246231, -0.2169499695301056, -0.1610642671585083, -0.2141464203596115, -0.1797635853290558, -0.17363053560256958, 0.8139917254447937, -0.015077708289027214, -0.19219623506069183, 0.5032162666320801, 0.290952205657959, -0.20581594109535217, 0.22820858657360077, -0.07482161372900009, -0.14803574979305267, -0.345528244972229, 0.3796443045139313, -0.03132491186261177, 0.14449141919612885, -0.19413748383522034, 0.3182498812675476, 0.28465232253074646, -0.015421017073094845, -0.04212811961770058, -0.20381203293800354], \\"type\\": \\"float32\\", \\"shape\\": [512]}"^^<https://w3id.org/rdf-tensor/datatypes#NumericDataTensor>'

In [81]:
db_qlever = QleverDBNative(
    id="qlever",
    base_dir=Path(f"./scratch/{dataset.base_dir.name}"),
    dataset=dataset,
    use_encoded_ttl=True,
    name="QLever",
    port_offset=-100
)
db_no_tensor_idx = QleverDBNative(
    id="qlever",
    base_dir=Path(f"./scratch/{dataset.base_dir.name}"),
    dataset=dataset,
    use_encoded_ttl=True,
    enable_tensor_index=False,
    name="QLever (No Tensor Vocabulary)",
    port_offset=-200
)
db_fuseki = FusekiDBNative(
    id="fuseki",
    base_dir=Path(f"./scratch/{dataset.base_dir.name}"),
    dataset=dataset,
    use_encoded_ttl=True,
    name="Fuseki",
    exec_dir="../../jena-datatensor",
    port_offset=-300
)
possible_queries = db_qlever.get_queries(test_tensor)
print(possible_queries)
dbs: list[QleverDBNative | FusekiDBNative] = [db_qlever, db_no_tensor_idx, db_fuseki]
indices = ["index-encoded", "index-encoded-no-tidx", "fuseki-encoded"]
ids = ["dbpedia-encoded-tidx", "dbpedia-encoded", None]
for db, index, id in zip(dbs, indices, ids):
    db.db_dir = Path("../data/dbpedia") / index
    db.id = id if id is not None else db.id

2026-04-24 15:40:55,060 - WARNING - Killing any existing process using port 25946 before starting the server
2026-04-24 15:40:55,079 - ERROR - Command failed with return code 1
2026-04-24 15:40:55,080 - INFO - Initialized QLeverDBNative with id=qlever, port_id=25946, dataset=DBPedia, name=QLever, use_encoded_ttl=True, endpoint=http://localhost:25946/qlever-with-tidx/sparql
2026-04-24 15:40:55,081 - WARNING - Killing any existing process using port 25847 before starting the server
2026-04-24 15:40:55,096 - ERROR - Command failed with return code 1
2026-04-24 15:40:55,096 - INFO - Initialized QLeverDBNative with id=qlever, port_id=25847, dataset=DBPedia, name=QLever (No Tensor Vocabulary), use_encoded_ttl=True, endpoint=http://localhost:25847/qlever-no-tidx/sparql
2026-04-24 15:40:55,097 - WARNING - Killing any existing process using port 28748 before starting the server
2026-04-24 15:40:55,112 - ERROR - Command failed with return code 1

{<QUERY_DIFFICULTY.EASY: 'easy'>: {<QUERY_TYPE.EMBEDDED: 'embedded'>: '\nPREFIX dbr: <http://dbpedia.org/resource/>\nPREFIX dbo: <http://dbpedia.org/ontology/>\nPREFIX dtf: <https://w3id.org/rdf-tensor/functions#>\nSELECT DISTINCT ?s ?thumb_emb ?dist WHERE {\n    ?s a dbo:Ship ;\n         dbo:thumbnail_embedding ?thumb_emb .\n    BIND(dtf:cosineSimilarity(?thumb_emb, "{\\"data\\": [-0.04262268915772438, -0.1333884298801422, 0.08612467348575592, -0.02091798186302185, -0.15041583776474, 0.1737712323665619, -0.348517507314682, -0.9152146577835083, -0.3341490924358368, 0.17787908017635345, 0.05680551752448082, -0.20725640654563904, 0.5095284581184387, 0.18332251906394958, 0.11725624650716782, 0.1168459951877594, 0.20500661432743073, -0.1478302776813507, -0.007135884836316109, 0.4961417019367218, 0.3664361536502838, 0.41410648822784424, -0.04107498377561569, 0.5009220838546753, -0.2138804793357849, -0.23931393027305603, -0.7052134275436401, 0.4793880879878998, -0.17963360249996185, 0.2792432904243469, -0.06826944649219513, 0.0803503543138504, -0.20019735395908356, 0.25140535831451416, -0.16235408186912537, 0.1176009476184845, 0.10282524675130844, 0.20387926697731018, -0.04952261596918106, 0.26974374055862427, 0.13957971334457397, 0.5327335596084595, 0.12486020475625992, -0.08572806417942047, 0.1065823957324028, -0.06904290616512299, 0.19244082272052765, 0.004055921919643879, -0.016175957396626472, 0.14999307692050934, 0.058157339692115784, -0.2949751913547516, -0.30239489674568176, 0.2556452751159668, -0.056346990168094635, 0.0034323800355196, -0.24107672274112701, 0.266265332698822, -0.21348032355308533, 0.401064395904541, 0.2964056432247162, 0.0030471496284008026, 0.0780687928199768, -0.10076116770505905, 0.12922954559326172, -0.0007172836922109127, -0.07724957168102264, 0.15974968671798706, 0.13473500311374664, 0.002694841008633375, 0.043134912848472595, 0.01628531515598297, 0.28354209661483765, -0.022883642464876175, 0.09224116057157516, -0.5340399742126465, -0.23960845172405243, 0.12176563590765, -0.34699109196662903, 0.05000511556863785, 0.062218617647886276, 0.1143401563167572, -0.01417964044958353, 0.5364919304847717, 0.2277376502752304, -0.029826924204826355, -0.34357592463493347, -0.10327602177858353, -0.0889338031411171, 0.36991357803344727, 0.012964829802513123, -0.07436607033014297, -1.309548258781433, 0.44614243507385254, 0.018672700971364975, -0.2529124319553375, 0.28713902831077576, 0.01675035059452057, 0.035857703536748886, -0.22998324036598206, -0.14083877205848694, -0.07106801122426987, -0.09642128646373749, 0.21655051410198212, 0.09358265995979309, 0.23318399488925934, -0.15376906096935272, 0.27460137009620667, -0.21038588881492615, 0.3248600959777832, -0.1732352375984192, 0.014894681051373482, -0.039007216691970825, 0.1811979115009308, -0.31202074885368347, -0.11454087495803833, -0.16019298136234283, -0.08498432487249374, 0.3788904845714569, -0.1883203685283661, -0.07226619124412537, -0.9254443645477295, -0.18329882621765137, -0.06734245270490646, 0.2413122057914734, -0.164064422249794, -0.3879578113555908, -0.2547023594379425, 0.14271141588687897, 0.39550554752349854, -0.13101597130298615, -0.45052370429039, -0.08015789091587067, 4.995395660400391, -0.23945783078670502, -0.37153586745262146, -0.29315686225891113, 0.08353441953659058, 0.10397690534591675, -0.24532519280910492, -0.29608869552612305, 0.0728289932012558, -0.19765496253967285, 0.2663191854953766, 0.1443239003419876, 0.06140514463186264, -0.0636756494641304, -0.136429563164711, -0.37929514050483704, 0.040126048028469086, 0.20846030116081238, -0.046803634613752365, -0.09697604179382324, 0.2885654866695404, -0.13826711475849152, -0.4298671782016754, 0.454520046710968, -0.3830225467681885, -0.2549723982810974, 0.1788555532693863, 0.07007404416799545, 0.14401200413703918, -0.02052035927772522, -0.06321345269680023, 0.14143216609954834, -0.002827470190823078, 0.13198769092559814, -0.4338044226169586, 0.31351831555366516, -0.015382522717118263, 0.03972843289375305, -0.11416905373334885, 0.32447728514671326, -0.08284606039524078, -0.2795880436897278, 0.33499065041542053, -0.13286051154136658, 0.1413523107767105, 0.1438053846359253, 0.4994203448295593, -0.12618792057037354, 0.13858260214328766, -0.1577799767255783, -0.24153682589530945, 0.3336068093776703, 0.11076335608959198, 0.27649617195129395, 0.19507920742034912, -0.3491799235343933, 0.10086368024349213, -0.1947011947631836, 0.14734765887260437, -0.1792561113834381, -0.2404884546995163, -0.20638126134872437, 0.1594625562429428, -0.2064419835805893, 0.4686662256717682, 0.1224103569984436, -0.1929231882095337, -0.3304961621761322, -0.15453074872493744, 0.3289383053779602, -0.19276845455169678, -0.1419120728969574, 0.036372654139995575, -0.032568495720624924, -0.2757578194141388, -0.17087632417678833, -0.3603208363056183, 0.3550761640071869, 0.07408803701400757, 0.16397617757320404, 0.4174465537071228, 0.03409815952181816, 0.015406325459480286, 0.14059369266033173, -0.2836103141307831, 0.04072924703359604, -0.13061843812465668, 0.08163174986839294, -0.24610236287117004, 0.09389635920524597, -0.24005071818828583, 0.13519728183746338, 0.0464361235499382, 0.22132527828216553, 0.02697714976966381, -0.08397431671619415, 0.23355722427368164, 0.07472678273916245, -0.07733243703842163, -0.08717343956232071, -0.056425370275974274, 0.3738686144351959, 0.03457840532064438, 0.3578338623046875, 0.1249217838048935, -0.3770174980163574, -0.02174508571624756, 0.3847891688346863, -0.31229445338249207, 0.24248838424682617, 0.1730431318283081, 0.21590428054332733, 0.028434207662940025, -0.04749997705221176, -0.354280561208725, 0.2951468825340271, 0.03223574534058571, -0.33378469944000244, 0.5995599031448364, 0.16036856174468994, 0.37374818325042725, -0.27309471368789673, 0.47794461250305176, 0.27809959650039673, 0.07505334913730621, 0.04588694125413895, 0.44692400097846985, -0.061994630843400955, -0.01789759285748005, 0.02898450754582882, -0.17852738499641418, -0.270717054605484, 0.05693190172314644, -0.0238601416349411, -0.1925913393497467, -0.3413273096084595, -0.1934177130460739, -0.30758562684059143, -0.2947530746459961, 0.26107990741729736, 0.1175401359796524, -0.0725201964378357, -0.029527168720960617, -0.37710872292518616, 0.06373333930969238, 0.3712431788444519, 0.16918398439884186, -0.1874537318944931, 0.09985712170600891, 0.10260182619094849, 0.20361138880252838, 0.014345571398735046, 0.5188203454017639, 0.16811496019363403, 0.25370705127716064, 0.11705280840396881, -0.05278034880757332, 0.03722261264920235, 0.3069724142551422, -0.3166779577732086, 0.3612406551837921, -0.3461386263370514, 0.14271120727062225, -0.4891326129436493, -0.031868647783994675, -0.2105318009853363, -0.10849712789058685, 0.5024760365486145, -0.42960524559020996, 0.09099404513835907, 0.10781149566173553, -0.08149893581867218, -0.36489272117614746, -0.19751374423503876, 0.4677923619747162, -0.19604173302650452, -0.5108305215835571, 0.04228796809911728, 0.40673041343688965, 4.982846260070801, 0.2281806766986847, 0.07898621261119843, 0.015636280179023743, 0.10525976121425629, -0.24056093394756317, 0.1307922601699829, 0.11874490231275558, 0.16272300481796265, 0.33506906032562256, 0.12341885268688202, 0.23444749414920807, 0.0751492977142334, 0.4529761075973511, -0.09843146800994873, -0.0868949443101883, 0.15630561113357544, -1.9064604043960571, 0.1436811089515686, -0.0647597685456276, 0.10218008607625961, 0.22556403279304504, -0.1312151700258255, 0.08798596262931824, -0.316336065530777, 0.08733700215816498, 0.4364594519138336, -0.0841616541147232, -0.12824013829231262, 0.17684020102024078, 0.0005449578166007996, -0.4466038644313812, 0.2596926987171173, -0.04485166817903519, 0.36150938272476196, 0.29519420862197876, -0.13554643094539642, 0.17567718029022217, -0.04864608496427536, 0.09418146312236786, 0.11930356919765472, -0.1689140498638153, -0.07621348649263382, -0.04019908607006073, 0.025453871116042137, -0.04131506010890007, 0.613564133644104, 0.17166201770305634, 0.19252869486808777, -0.1529507040977478, -0.3212543725967407, 0.29930058121681213, 0.183676615357399, 0.256805956363678, -0.348125159740448, -0.24246308207511902, -0.15343236923217773, 0.045282796025276184, 0.12715944647789001, 0.1002541035413742, 0.3344520628452301, 0.12696677446365356, -0.03679069131612778, 0.08682677894830704, 0.027234166860580444, 0.12669570744037628, -0.14569342136383057, -0.11954189836978912, 0.005335235968232155, -0.023069556802511215, 0.12944917380809784, -0.5794199705123901, 0.4554336667060852, 0.26931557059288025, -0.14136828482151031, 0.16985487937927246, 0.035368259996175766, -0.21738597750663757, -0.19395196437835693, -0.2554394602775574, 0.036201342940330505, 0.0026678694412112236, 0.03341682255268097, -0.00012027658522129059, -0.20584441721439362, -0.2441178858280182, -0.29085585474967957, 0.6269326210021973, -0.07581208646297455, 0.01799778640270233, 0.26985567808151245, -0.18378271162509918, -0.21640625596046448, 0.07882273197174072, 0.11399638652801514, 0.16782686114311218, 0.1454664021730423, -0.14690759778022766, 0.5914286375045776, -0.06359510123729706, -0.4243270754814148, 0.419055312871933, 0.03688973933458328, 0.09080688655376434, -0.20464570820331573, -0.23673778772354126, 0.12423155456781387, -0.3539251387119293, -0.05117426812648773, -0.33227285742759705, 0.09913495182991028, -0.5108201503753662, 0.2183261215686798, 0.14858272671699524, -0.03194478526711464, -0.2500399053096771, 0.3474576473236084, -0.08445319533348083, 0.05256013572216034, 0.12885384261608124, 0.05474567040801048, 0.28207558393478394, 0.24913564324378967, 0.017554350197315216, -0.04651769623160362, -0.21744558215141296, -0.5378966331481934, 0.35821494460105896, 0.02395261451601982, 0.2269265353679657, -0.48503151535987854, -0.4348192811012268, 0.2893373370170593, 0.13147799670696259, 0.30677375197410583, -0.38510605692863464, 0.22093357145786285, 0.26399722695350647, -0.49346867203712463, 0.10722221434116364, 0.004673405550420284, -0.2786339819431305, 0.13793890178203583, -0.049813125282526016, -0.258821964263916, 0.336711049079895, 0.19765441119670868, -0.09453567862510681, 0.01727696880698204, 0.10990896075963974, 0.5079712271690369, 0.18238453567028046, 0.29509949684143066, 0.0021931459195911884, 0.44314414262771606, -0.1369258612394333, 0.03231927752494812, -0.013810236006975174, -0.1325978934764862, -0.40534934401512146, 0.30387064814567566, -0.31678539514541626, -0.06312119215726852, 0.35880550742149353, -0.14602607488632202, 0.23039574921131134, -0.10129227489233017, 0.4284210801124573, -0.21266235411167145, -0.38488680124282837, 0.3961750268936157, -0.13077367842197418, 0.2837107181549072, -0.4066965579986572, -0.28119900822639465, -0.12295553833246231, -0.2169499695301056, -0.1610642671585083, -0.2141464203596115, -0.1797635853290558, -0.17363053560256958, 0.8139917254447937, -0.015077708289027214, -0.19219623506069183, 0.5032162666320801, 0.290952205657959, -0.20581594109535217, 0.22820858657360077, -0.07482161372900009, -0.14803574979305267, -0.345528244972229, 0.3796443045139313, -0.03132491186261177, 0.14449141919612885, -0.19413748383522034, 0.3182498812675476, 0.28465232253074646, -0.015421017073094845, -0.04212811961770058, -0.20381203293800354], \\"type\\": \\"float32\\", \\"shape\\": [512]}"^^<https://w3id.org/rdf-tensor/datatypes#NumericDataTensor>) AS ?dist)\n} \nORDER BY DESC(?dist)\nLIMIT 10\n        ', <QUERY_TYPE.INDEX: 'index'>: '\nPREFIX dbr: <http://dbpedia.org/resource/>\nPREFIX dbo: <http://dbpedia.org/ontology/>\nPREFIX dtf: <https://w3id.org/rdf-tensor/functions#>\nPREFIX tensorSearch: <https://qlever.cs.uni-freiburg.de/tensorSearch/>\nSELECT DISTINCT ?s ?thumb_emb ?dist WHERE {\nSERVICE tensorSearch: {\n    _:config tensorSearch:numNN 10 ;\n    tensorSearch:left ?query_vector ;\n    tensorSearch:bindDistance ?dist ;\n    tensorSearch:payload ?s, ?thumb_emb ;\n    tensorSearch:searchK 1 ;\n    tensorSearch:kIVF 512 ;\n    # tensorSearch:experimentalRightCacheName "easy_index_dbpedia" ;\n    tensorSearch:right ?thumb_emb ;\n    tensorSearch:algorithm tensorSearch:ivf ;\n    tensorSearch:distance tensorSearch:dot .\n       {\n            ?s a dbo:Ship ;\n            dbo:thumbnail_embedding ?thumb_emb .\n        }\n    }\n    VALUES (?query_vector) { ("{\\"data\\": [-0.04262268915772438, -0.1333884298801422, 0.08612467348575592, -0.02091798186302185, -0.15041583776474, 0.1737712323665619, -0.348517507314682, -0.9152146577835083, -0.3341490924358368, 0.17787908017635345, 0.05680551752448082, -0.20725640654563904, 0.5095284581184387, 0.18332251906394958, 0.11725624650716782, 0.1168459951877594, 0.20500661432743073, -0.1478302776813507, -0.007135884836316109, 0.4961417019367218, 0.3664361536502838, 0.41410648822784424, -0.04107498377561569, 0.5009220838546753, -0.2138804793357849, -0.23931393027305603, -0.7052134275436401, 0.4793880879878998, -0.17963360249996185, 0.2792432904243469, -0.06826944649219513, 0.0803503543138504, -0.20019735395908356, 0.25140535831451416, -0.16235408186912537, 0.1176009476184845, 0.10282524675130844, 0.20387926697731018, -0.04952261596918106, 0.26974374055862427, 0.13957971334457397, 0.5327335596084595, 0.12486020475625992, -0.08572806417942047, 0.1065823957324028, -0.06904290616512299, 0.19244082272052765, 0.004055921919643879, -0.016175957396626472, 0.14999307692050934, 0.058157339692115784, -0.2949751913547516, -0.30239489674568176, 0.2556452751159668, -0.056346990168094635, 0.0034323800355196, -0.24107672274112701, 0.266265332698822, -0.21348032355308533, 0.401064395904541, 0.2964056432247162, 0.0030471496284008026, 0.0780687928199768, -0.10076116770505905, 0.12922954559326172, -0.0007172836922109127, -0.07724957168102264, 0.15974968671798706, 0.13473500311374664, 0.002694841008633375, 0.043134912848472595, 0.01628531515598297, 0.28354209661483765, -0.022883642464876175, 0.09224116057157516, -0.5340399742126465, -0.23960845172405243, 0.12176563590765, -0.34699109196662903, 0.05000511556863785, 0.062218617647886276, 0.1143401563167572, -0.01417964044958353, 0.5364919304847717, 0.2277376502752304, -0.029826924204826355, -0.34357592463493347, -0.10327602177858353, -0.0889338031411171, 0.36991357803344727, 0.012964829802513123, -0.07436607033014297, -1.309548258781433, 0.44614243507385254, 0.018672700971364975, -0.2529124319553375, 0.28713902831077576, 0.01675035059452057, 0.035857703536748886, -0.22998324036598206, -0.14083877205848694, -0.07106801122426987, -0.09642128646373749, 0.21655051410198212, 0.09358265995979309, 0.23318399488925934, -0.15376906096935272, 0.27460137009620667, -0.21038588881492615, 0.3248600959777832, -0.1732352375984192, 0.014894681051373482, -0.039007216691970825, 0.1811979115009308, -0.31202074885368347, -0.11454087495803833, -0.16019298136234283, -0.08498432487249374, 0.3788904845714569, -0.1883203685283661, -0.07226619124412537, -0.9254443645477295, -0.18329882621765137, -0.06734245270490646, 0.2413122057914734, -0.164064422249794, -0.3879578113555908, -0.2547023594379425, 0.14271141588687897, 0.39550554752349854, -0.13101597130298615, -0.45052370429039, -0.08015789091587067, 4.995395660400391, -0.23945783078670502, -0.37153586745262146, -0.29315686225891113, 0.08353441953659058, 0.10397690534591675, -0.24532519280910492, -0.29608869552612305, 0.0728289932012558, -0.19765496253967285, 0.2663191854953766, 0.1443239003419876, 0.06140514463186264, -0.0636756494641304, -0.136429563164711, -0.37929514050483704, 0.040126048028469086, 0.20846030116081238, -0.046803634613752365, -0.09697604179382324, 0.2885654866695404, -0.13826711475849152, -0.4298671782016754, 0.454520046710968, -0.3830225467681885, -0.2549723982810974, 0.1788555532693863, 0.07007404416799545, 0.14401200413703918, -0.02052035927772522, -0.06321345269680023, 0.14143216609954834, -0.002827470190823078, 0.13198769092559814, -0.4338044226169586, 0.31351831555366516, -0.015382522717118263, 0.03972843289375305, -0.11416905373334885, 0.32447728514671326, -0.08284606039524078, -0.2795880436897278, 0.33499065041542053, -0.13286051154136658, 0.1413523107767105, 0.1438053846359253, 0.4994203448295593, -0.12618792057037354, 0.13858260214328766, -0.1577799767255783, -0.24153682589530945, 0.3336068093776703, 0.11076335608959198, 0.27649617195129395, 0.19507920742034912, -0.3491799235343933, 0.10086368024349213, -0.1947011947631836, 0.14734765887260437, -0.1792561113834381, -0.2404884546995163, -0.20638126134872437, 0.1594625562429428, -0.2064419835805893, 0.4686662256717682, 0.1224103569984436, -0.1929231882095337, -0.3304961621761322, -0.15453074872493744, 0.3289383053779602, -0.19276845455169678, -0.1419120728969574, 0.036372654139995575, -0.032568495720624924, -0.2757578194141388, -0.17087632417678833, -0.3603208363056183, 0.3550761640071869, 0.07408803701400757, 0.16397617757320404, 0.4174465537071228, 0.03409815952181816, 0.015406325459480286, 0.14059369266033173, -0.2836103141307831, 0.04072924703359604, -0.13061843812465668, 0.08163174986839294, -0.24610236287117004, 0.09389635920524597, -0.24005071818828583, 0.13519728183746338, 0.0464361235499382, 0.22132527828216553, 0.02697714976966381, -0.08397431671619415, 0.23355722427368164, 0.07472678273916245, -0.07733243703842163, -0.08717343956232071, -0.056425370275974274, 0.3738686144351959, 0.03457840532064438, 0.3578338623046875, 0.1249217838048935, -0.3770174980163574, -0.02174508571624756, 0.3847891688346863, -0.31229445338249207, 0.24248838424682617, 0.1730431318283081, 0.21590428054332733, 0.028434207662940025, -0.04749997705221176, -0.354280561208725, 0.2951468825340271, 0.03223574534058571, -0.33378469944000244, 0.5995599031448364, 0.16036856174468994, 0.37374818325042725, -0.27309471368789673, 0.47794461250305176, 0.27809959650039673, 0.07505334913730621, 0.04588694125413895, 0.44692400097846985, -0.061994630843400955, -0.01789759285748005, 0.02898450754582882, -0.17852738499641418, -0.270717054605484, 0.05693190172314644, -0.0238601416349411, -0.1925913393497467, -0.3413273096084595, -0.1934177130460739, -0.30758562684059143, -0.2947530746459961, 0.26107990741729736, 0.1175401359796524, -0.0725201964378357, -0.029527168720960617, -0.37710872292518616, 0.06373333930969238, 0.3712431788444519, 0.16918398439884186, -0.1874537318944931, 0.09985712170600891, 0.10260182619094849, 0.20361138880252838, 0.014345571398735046, 0.5188203454017639, 0.16811496019363403, 0.25370705127716064, 0.11705280840396881, -0.05278034880757332, 0.03722261264920235, 0.3069724142551422, -0.3166779577732086, 0.3612406551837921, -0.3461386263370514, 0.14271120727062225, -0.4891326129436493, -0.031868647783994675, -0.2105318009853363, -0.10849712789058685, 0.5024760365486145, -0.42960524559020996, 0.09099404513835907, 0.10781149566173553, -0.08149893581867218, -0.36489272117614746, -0.19751374423503876, 0.4677923619747162, -0.19604173302650452, -0.5108305215835571, 0.04228796809911728, 0.40673041343688965, 4.982846260070801, 0.2281806766986847, 0.07898621261119843, 0.015636280179023743, 0.10525976121425629, -0.24056093394756317, 0.1307922601699829, 0.11874490231275558, 0.16272300481796265, 0.33506906032562256, 0.12341885268688202, 0.23444749414920807, 0.0751492977142334, 0.4529761075973511, -0.09843146800994873, -0.0868949443101883, 0.15630561113357544, -1.9064604043960571, 0.1436811089515686, -0.0647597685456276, 0.10218008607625961, 0.22556403279304504, -0.1312151700258255, 0.08798596262931824, -0.316336065530777, 0.08733700215816498, 0.4364594519138336, -0.0841616541147232, -0.12824013829231262, 0.17684020102024078, 0.0005449578166007996, -0.4466038644313812, 0.2596926987171173, -0.04485166817903519, 0.36150938272476196, 0.29519420862197876, -0.13554643094539642, 0.17567718029022217, -0.04864608496427536, 0.09418146312236786, 0.11930356919765472, -0.1689140498638153, -0.07621348649263382, -0.04019908607006073, 0.025453871116042137, -0.04131506010890007, 0.613564133644104, 0.17166201770305634, 0.19252869486808777, -0.1529507040977478, -0.3212543725967407, 0.29930058121681213, 0.183676615357399,

In [82]:
triple_counts = []
for db in dbs[:-1]:
    with db:
        count = db.get_triple_count()
        count_tensors = db.query("""
PREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
SELECT (COUNT(?v) AS ?count) WHERE {
    ?s dbo:thumbnail_embedding ?v .
}""")["count"].values[0]
        print(f"{db.name}: {count} triples, {count_tensors} tensors")
        triple_counts.append({
            "count": count,
            "tensors": count_tensors,
            "db": db.name
        })
print(f"Total triples in DB: {sum([tc['count'] for tc in triple_counts])}")

2026-04-24 15:40:55,191 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-04-24 15:40:55,191 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt.gz
2026-04-24 15:40:55,192 - WARNING - DB directory ../data/dbpedia/index-encoded already exists!
2026-04-24 15:40:55,192 - INFO - Stopping server!

2026-04-24 15:40:55,207 - ERROR - Command failed with return code 1
2026-04-24 15:40:55,207 - INFO - Starting QLever server on port 25946
2026-04-24 15:40:55,208 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25946 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-24 15:40:55,210 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25946/qlever-with-tidx/sparql)
2026-04-24 15:40:56,211 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25946/qlever-with-tidx/sparql)
2026-04-24 15:40:57,212 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25946/qlever-with-tidx/sparql)
2026-04-24 15:40:58,214 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25946/qlever-with-tidx/sparql)
2026-04-24 15:40:59,223 - INFO - Server is up and responding to queries
2026-04-24 15:41:00,319 - INFO - Stopping server!
2026-04-24 15:41:00,400 - ERROR - Command failed with return code 1
2026-04-24 15:41:00,401 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-no-tidx/qlever-no-tidx_run.log
2026-04-24 15:41:00,402 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt.gz
2026-04-24 15:41:00,402 - WARNING - DB directory ../data/dbpedia/index-encoded-no-tidx already exists!
2026-04-24 15:41:00,403 - INFO - Stopping server!
2026-04-24 15:41:00,418 - ERROR - Command failed with return code 1
2026-04-24 15:41:00,419 - INFO - Starting QLever server on port 25847
2026-04-24 15:41:00,419 - INFO - Running command: qlever-server -i dbpedia-encoded --port 25847 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-24 15:41:00,421 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25847/qlever-no-tidx/sparql)

QLever: 421770566 triples, 2329464 tensors

2026-04-24 15:41:01,422 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25847/qlever-no-tidx/sparql)
2026-04-24 15:41:02,423 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25847/qlever-no-tidx/sparql)
2026-04-24 15:41:03,425 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25847/qlever-no-tidx/sparql)
2026-04-24 15:41:04,436 - INFO - Server is up and responding to queries
2026-04-24 15:41:05,528 - INFO - Stopping server!
2026-04-24 15:41:05,608 - ERROR - Command failed with return code 1

QLever (No Tensor Vocabulary): 421770566 triples, 2329464 tensors
Total triples in DB: 843541132

In [83]:
counts_df = pd.DataFrame(triple_counts)
counts_df

       count  tensors                             db
0  421770566  2329464                         QLever
1  421770566  2329464  QLever (No Tensor Vocabulary)

In [84]:
counts_df["power"] = counts_df["count"].apply(lambda x: int(np.log10(x)))
counts_df["size"] = counts_df["count"]
counts_df["full_size"] = counts_df["count"]
counts_df["full_number_of_tensors"] = counts_df["tensors"]

In [85]:
from utils.helpers import pretty_print_counts

out_path_counts = Path("../scratch/results") / "dbpedia_counts.tex"
pretty_print_counts(counts_df, out_path_counts)

['power', 'size', 'full_size', 'full_number_of_tensors'] []

   Power  Generation $t$        $n$  $n_{tensors}$
0      8       421770566  421770566        2329464
1      8       421770566  421770566        2329464

In [104]:
with db_qlever as db:
    timings = []
    for _ in tqdm.tqdm(range(5)):
        start = time.time()
        r = db.query_auto(
            query_difficulty=QUERY_DIFFICULTY.EASY,
            query_type=QUERY_TYPE.INDEX,
            tensor=test_tensor,
        )
        end = time.time()
        timings.append(end - start)
print("Timings avg:", sum(timings) / len(timings))
r

2026-04-24 16:10:41,170 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-04-24 16:10:41,170 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt.gz
2026-04-24 16:10:41,171 - WARNING - DB directory ../data/dbpedia/index-encoded already exists!
2026-04-24 16:10:41,171 - INFO - Stopping server!
2026-04-24 16:10:41,189 - ERROR - Command failed with return code 1
2026-04-24 16:10:41,189 - INFO - Starting QLever server on port 25946
2026-04-24 16:10:41,190 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25946 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-24 16:10:41,191 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25946/qlever-with-tidx/sparql)
2026-04-24 16:10:42,192 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25946/qlever-with-tidx/sparql)
2026-04-24 16:10:43,194 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25946/qlever-with-tidx/sparql)
2026-04-24 16:10:44,195 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25946/qlever-with-tidx/sparql)
2026-04-24 16:10:45,208 - INFO - Server is up and responding to queries
100%|██████████| 5/5 [00:00<00:00,  8.94it/s]
2026-04-24 16:10:45,769 - INFO - Stopping server!
2026-04-24 16:10:45,856 - ERROR - Command failed with return code 1

Timings avg: 0.11167473793029785

,s,thumb_emb,dist
0,dbr:SS_Albert_M._Boe,"{""data"": [0.3019237518310547, -0.1744167208671...",27.03730392456
1,dbr:MV_Uhuru,"{""data"": [0.10303764045238495, -0.229101330041...",27.02251815796
2,dbr:Original_six_frigates_of_the_United_States...,"{""data"": [0.3499048352241516, -0.0667797625064...",26.38556671143
3,dbr:Fire-float_Pyronaut,"{""data"": [0.5736645460128784, 0.02624748647212...",26.04682922363
4,dbr:Eppleton_Hall_(1914),"{""data"": [0.15651816129684448, -0.074189648032...",25.96257019043
5,dbr:Sherman_Zwicker,"{""data"": [0.050441011786460876, -0.30955773591...",25.90690803528
6,dbr:PS_Comet,"{""data"": [0.3139987587928772, 0.04801601171493...",25.84019470215
7,dbr:Ross_Tiger,"{""data"": [0.40394482016563416, -0.303305000066...",25.53351593018
8,dbr:NLV_Pole_Star,"{""data"": [0.4585147500038147, 0.00598367303609...",25.43468475342
9,dbr:Kathleen_and_May,"{""data"": [0.24212899804115295, 0.1124063432216...",25.43309020996

In [16]:
with dbs[0] as db:
    res_native = db.query(f"""
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dtf: <https://w3id.org/rdf-tensor/functions#>
SELECT * WHERE {{


    ?s a dbo:Ship .
    ?s dbo:thumbnail_embedding ?thumb_emb .
    ?s dbo:thumbnail_original ?thumb .      

    BIND(dtf:dotProduct(?thumb_emb, {test_tensor.to_literal().n3()}) AS ?dist)
}} 

ORDER BY DESC(?dist)
LIMIT 10""")
res_native

2026-04-24 14:40:08,474 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-04-24 14:40:08,475 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt.gz
2026-04-24 14:40:08,475 - WARNING - DB directory ../data/dbpedia/index-encoded already exists!
2026-04-24 14:40:08,475 - INFO - Stopping server!
2026-04-24 14:40:08,554 - ERROR - Command failed with return code 1
2026-04-24 14:40:08,555 - INFO - Starting QLever server on port 25943
2026-04-24 14:40:08,555 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25943 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-24 14:40:08,557 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-24 14:40:09,558 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-24 14:40:10,560 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-24 14:40:11,572 - INFO - Server is up and responding to queries
2026-04-24 14:40:11,775 - INFO - Stopping server!
2026-04-24 14:40:11,860 - ERROR - Command failed with return code 1

,s,thumb_emb,thumb,dist
0,dbr:HMS_Trent_(1757),"{""data"": [0.20562176406383514, 0.2037418782711...",https://upload.wikimedia.org/wikipedia/commons...,31.31344604492
1,dbr:Fram,"{""data"": [0.25629281997680664, -0.140227705240...",https://upload.wikimedia.org/wikipedia/commons...,29.51948547363
2,dbr:Fram,"{""data"": [0.25629281997680664, -0.140227705240...",https://upload.wikimedia.org/wikipedia/commons...,29.51948547363
3,dbr:Fram,"{""data"": [0.25629281997680664, -0.140227705240...",https://upload.wikimedia.org/wikipedia/commons...,29.51948547363
4,dbr:Fram,"{""data"": [0.25629281997680664, -0.140227705240...",https://upload.wikimedia.org/wikipedia/commons...,29.51948547363
5,dbr:Fram,"{""data"": [0.25629281997680664, -0.140227705240...",http://upload.wikimedia.org/wikipedia/commons/...,29.51948547363
6,dbr:Fram,"{""data"": [0.25629281997680664, -0.140227705240...",http://upload.wikimedia.org/wikipedia/commons/...,29.51948547363
7,dbr:Spanish_ship_San_Ildefonso,"{""data"": [-0.08917225152254105, -0.20555926859...",https://upload.wikimedia.org/wikipedia/commons...,29.03779411316
8,dbr:Spanish_ship_San_Ildefonso,"{""data"": [-0.08917225152254105, -0.20555926859...",https://upload.wikimedia.org/wikipedia/commons...,29.03779411316
9,dbr:Margaret_Todd_(schooner),"{""data"": [0.506389856338501, 0.253706932067871...",https://upload.wikimedia.org/wikipedia/commons...,28.92206573486

In [ ]:
with dbs[0] as db:
    res =db.query(f"""
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dtf: <https://w3id.org/rdf-tensor/functions#>
PREFIX tensorIndex: <https://qlever.cs.uni-freiburg.de/tensorIndex/>
SELECT * WHERE {{
SERVICE tensorIndex: {{
    _:config tensorIndex:numNN 10 ;
    tensorIndex:left ?query_vector ;
    tensorIndex:bindDistance ?dist ;
    tensorIndex:payload ?s, ?thumb ;
    tensorIndex:searchK 64 ;
    tensorIndex:kIVF 128 ;
    # tensorIndex:experimentalRightCacheName "easy_index_dbpedia" ;
    tensorIndex:right ?thumb_emb ;
    tensorIndex:algorithm tensorIndex:ivf ;
    tensorIndex:distance tensorIndex:dot .
       {{
            ?s a dbo:Ship ;
            dbo:thumbnail_embedding ?thumb_emb ;
            dbo:thumbnail_original ?thumb .
        }}
    }}
    VALUES (?query_vector) {{ ({test_tensor.to_literal().n3()}) }}
}} 
ORDER BY DESC(?dist)
""")
res

2026-04-24 14:40:48,643 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-04-24 14:40:48,643 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt.gz
2026-04-24 14:40:48,644 - WARNING - DB directory ../data/dbpedia/index-encoded already exists!
2026-04-24 14:40:48,644 - INFO - Stopping server!
2026-04-24 14:40:48,732 - ERROR - Command failed with return code 1
2026-04-24 14:40:48,732 - INFO - Starting QLever server on port 25943
2026-04-24 14:40:48,732 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25943 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-24 14:40:48,734 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-24 14:40:49,735 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-24 14:40:50,737 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-24 14:40:51,750 - INFO - Server is up and responding to queries
2026-04-24 14:40:52,573 - INFO - Stopping server!
2026-04-24 14:40:52,658 - ERROR - Command failed with return code 1

,query_vector,dist,s,thumb,thumb_emb
0,"{""data"": [-0.04262268915772438, -0.13338842988...",29.51948547363,dbr:Fram,https://upload.wikimedia.org/wikipedia/commons...,"{""data"": [0.25629281997680664, -0.140227705240..."
1,"{""data"": [-0.04262268915772438, -0.13338842988...",29.51948547363,dbr:Fram,https://upload.wikimedia.org/wikipedia/commons...,"{""data"": [0.25629281997680664, -0.140227705240..."
2,"{""data"": [-0.04262268915772438, -0.13338842988...",29.51948547363,dbr:Fram,https://upload.wikimedia.org/wikipedia/commons...,"{""data"": [0.25629281997680664, -0.140227705240..."
3,"{""data"": [-0.04262268915772438, -0.13338842988...",29.51948547363,dbr:Fram,https://upload.wikimedia.org/wikipedia/commons...,"{""data"": [0.25629281997680664, -0.140227705240..."
4,"{""data"": [-0.04262268915772438, -0.13338842988...",29.51948547363,dbr:Fram,http://upload.wikimedia.org/wikipedia/commons/...,"{""data"": [0.25629281997680664, -0.140227705240..."
5,"{""data"": [-0.04262268915772438, -0.13338842988...",29.51948547363,dbr:Fram,http://upload.wikimedia.org/wikipedia/commons/...,"{""data"": [0.25629281997680664, -0.140227705240..."
6,"{""data"": [-0.04262268915772438, -0.13338842988...",28.92206382751,dbr:Margaret_Todd_(schooner),https://upload.wikimedia.org/wikipedia/commons...,"{""data"": [0.506389856338501, 0.253706932067871..."
7,"{""data"": [-0.04262268915772438, -0.13338842988...",28.92206382751,dbr:Margaret_Todd_(schooner),https://upload.wikimedia.org/wikipedia/commons...,"{""data"": [0.506389856338501, 0.253706932067871..."
8,"{""data"": [-0.04262268915772438, -0.13338842988...",28.79962348938,dbr:La_Grace,https://upload.wikimedia.org/wikipedia/commons...,"{""data"": [0.3559197187423706, 0.05999966338276..."
9,"{""data"": [-0.04262268915772438, -0.13338842988...",28.79962348938,dbr:La_Grace,https://upload.wikimedia.org/wikipedia/commons...,"{""data"": [0.3559197187423706, 0.05999966338276..."

In [20]:
res.to_csv(Path("scratch") / "dbpedia_results_index.csv", index=False)

In [21]:
with dbs[1] as db:
    db.query_auto(test_tensor, query_type=QUERY_TYPE.INDEX, query_difficulty=QUERY_DIFFICULTY.HARD)

2026-04-24 14:40:56,056 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-no-tidx/qlever-no-tidx_run.log
2026-04-24 14:40:56,057 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt.gz
2026-04-24 14:40:56,057 - WARNING - DB directory ../data/dbpedia/index-encoded-no-tidx already exists!
2026-04-24 14:40:56,058 - INFO - Stopping server!
2026-04-24 14:40:56,142 - ERROR - Command failed with return code 1
2026-04-24 14:40:56,143 - INFO - Starting QLever server on port 25844
2026-04-24 14:40:56,143 - INFO - Running command: qlever-server -i dbpedia-encoded --port 25844 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-24 14:40:56,146 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25844/qlever-no-tidx/sparql)
2026-04-24 14:40:57,147 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25844/qlever-no-tidx/sparql)
2026-04-24 14:40:58,148 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25844/qlever-no-tidx/sparql)
2026-04-24 14:40:59,162 - INFO - Server is up and responding to queries
2026-04-24 14:41:05,746 - INFO - Stopping server!
2026-04-24 14:41:05,872 - ERROR - Command failed with return code 1

In [24]:
from utils.helpers import ndcgscore_query
reference_result = res_native
score = ndcgscore_query(res, reference_result, k=10)
print(f"Score: {score}")

Score: 0.8042472959280005

In [25]:
# count ships
with dbs[0] as db:
    rs =db.query(f"""
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
SELECT (COUNT(*) AS ?count) WHERE {{ 
            ?s a dbo:Ship ;
            dbo:thumbnail_embedding ?thumb_emb ;
            dbo:thumbnail_original ?thumb  .
}} LIMIT 10""")
    rr =  db.query(f"""PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
SELECT (COUNT(*) AS ?count) WHERE {{ 
            ?s a dbo:RailwayLine ;
            dbo:thumbnail_embedding ?thumb_emb ;
            dbo:thumbnail_original ?thumb  .
}} LIMIT 10""")
rs.iloc[0], rr.iloc[0]

2026-04-24 14:41:25,772 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-04-24 14:41:25,772 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt.gz
2026-04-24 14:41:25,773 - WARNING - DB directory ../data/dbpedia/index-encoded already exists!
2026-04-24 14:41:25,773 - INFO - Stopping server!
2026-04-24 14:41:25,854 - ERROR - Command failed with return code 1
2026-04-24 14:41:25,855 - INFO - Starting QLever server on port 25943
2026-04-24 14:41:25,855 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25943 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-24 14:41:25,857 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-24 14:41:26,858 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-24 14:41:27,860 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-24 14:41:28,873 - INFO - Server is up and responding to queries
2026-04-24 14:41:28,950 - INFO - Stopping server!
2026-04-24 14:41:29,032 - ERROR - Command failed with return code 1

(count    70312
 Name: 0, dtype: str,
 count    39797
 Name: 0, dtype: str)

In [ ]:
# for find similar thumbnails between ships and railroads
times = []
with dbs[0] as db:
    #     warmup = db.query("""
    # PREFIX dbr: <http://dbpedia.org/resource/>
    # PREFIX dbo: <http://dbpedia.org/ontology/>
    # PREFIX tensorIndex: <https://qlever.cs.uni-freiburg.de/tensorIndex/>
    # SELECT * WHERE {
    #     { SELECT * WHERE {
    #         ?r a dbo:RailwayLine .
    #         ?r dbo:thumbnail_embedding ?thumb_rail_emb .
    #         ?r dbo:thumbnail_original ?thumb_rail .
    #     } LIMIT 1
    #     }
    #     SERVICE tensorIndex: {
    #     _:config tensorIndex:numNN 10 ;
    #     tensorIndex:left ?thumb_rail_emb ;
    #     tensorIndex:bindDistance ?dist ;
    #     tensorIndex:payload ?s, ?thumb_ship ;
    #     tensorIndex:searchK 1 ;
    #     tensorIndex:nTrees 128 ;
    #     tensorIndex:experimentalRightCacheName "hard_index_dbpedia" ;
    #     tensorIndex:right ?thumb_emb_ship ;
    #     tensorIndex:algorithm tensorIndex:ivf ;
    #     tensorIndex:distance tensorIndex:dot .
    #         {
    #             ?s a dbo:Ship ;
    #             dbo:thumbnail_embedding ?thumb_emb_ship ;
    #             dbo:thumbnail_original ?thumb_ship .
    #         }
    #     }
    #     }""")
    for _ in range(0):
        start = time.time()

        noised_tensor = DataTensor.from_numpy(
            test_tensor.data + np.random.normal(scale=0.001, size=test_tensor.shape)
        )
        railway_ship_assoc = db.query(f"""
    PREFIX dbr: <http://dbpedia.org/resource/>
    PREFIX dbo: <http://dbpedia.org/ontology/>
    PREFIX dtf: <https://w3id.org/rdf-tensor/functions#>
    PREFIX tensorIndex: <https://qlever.cs.uni-freiburg.de/tensorIndex/>
    SELECT DISTINCT ?r ?s  ?dist ?thumb_rail_emb ?thumb_ship_emb WHERE {{
        {{
        SELECT DISTINCT ?r ?s ?dist ?thumb_rail_emb ?thumb_ship_emb WHERE {{
            
            ?r a dbo:RailwayLine .
            ?r dbo:thumbnail_embedding ?thumb_rail_emb .
                                        
            SERVICE tensorIndex: {{
            _:config tensorIndex:numNN 1 ;
            tensorIndex:left ?thumb_rail_emb ;
            tensorIndex:bindDistance ?dist ;
            tensorIndex:payload ?s, ?thumb_ship ;
            tensorIndex:searchK 1 ;
            tensorIndex:nTrees 512 ;
            tensorIndex:experimentalRightCacheName "hard_index_dbpedia" ;
            tensorIndex:right ?thumb_ship_emb ;
            tensorIndex:algorithm tensorIndex:ivf ;
            tensorIndex:distance tensorIndex:dot .
            {{
                ?s a dbo:Ship ;
                dbo:thumbnail_embedding ?thumb_ship_emb ;    
            }}
            }}                  
        }}
        }}
        VALUES (?some_emb) {{ ({noised_tensor.to_literal().n3()}) }}
                                    
    }}
    ORDER BY DESC(?dist)
    LIMIT 20""")
        end = time.time()
        delta = end - start
        times.append(delta)
times

2026-04-24 14:42:04,041 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-04-24 14:42:04,041 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt.gz
2026-04-24 14:42:04,042 - WARNING - DB directory ../data/dbpedia/index-encoded already exists!
2026-04-24 14:42:04,042 - INFO - Stopping server!
2026-04-24 14:42:04,124 - ERROR - Command failed with return code 1
2026-04-24 14:42:04,125 - INFO - Starting QLever server on port 25943
2026-04-24 14:42:04,125 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25943 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-24 14:42:04,127 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-24 14:42:05,128 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-24 14:42:06,129 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-24 14:42:07,142 - INFO - Server is up and responding to queries
2026-04-24 14:42:07,143 - INFO - Stopping server!
2026-04-24 14:42:07,297 - ERROR - Command failed with return code 1

[]

In [ ]:
with db_qlever as db:
    hard_results = db.query(
        f"""
        PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dtf: <https://w3id.org/rdf-tensor/functions#>
PREFIX tensorIndex: <https://qlever.cs.uni-freiburg.de/tensorIndex/>
SELECT DISTINCT ?r ?s  ?dist ?thumb_rail_emb ?thumb_ship_emb WHERE {{
    {{
    SELECT DISTINCT ?r ?s ?dist ?thumb_rail_emb ?thumb_ship_emb WHERE {{
        
        ?r a dbo:RailwayLine ;
         dbo:thumbnail_embedding ?thumb_rail_emb ;
         dbo:thumbnail_original ?thumb_rail_original .
        BIND(LCASE(STR(?thumb_rail_original)) AS ?thumb_rail)
        FILTER(STRENDS(?thumb_rail, ".png") || STRENDS(?thumb_rail, ".jpg") || STRENDS(?thumb_rail, ".jpeg")) .
                                    
        SERVICE tensorIndex: {{
        _:config tensorIndex:numNN 1 ;
        tensorIndex:left ?thumb_rail_emb ;
        tensorIndex:bindDistance ?dist ;
        tensorIndex:payload ?s, ?thumb_ship_emb ;
        tensorIndex:searchK 1 ;
        tensorIndex:kIVF 512 ;
        tensorIndex:experimentalRightCacheName "hard_index_dbpedia" ;
        tensorIndex:right ?thumb_ship_emb ;
        tensorIndex:algorithm tensorIndex:ivf ;
        tensorIndex:distance tensorIndex:dot .
        {{
            ?s a dbo:Ship ;
            dbo:thumbnail_embedding ?thumb_ship_emb ;  
            dbo:thumbnail_original ?thumb_ship_original .
            BIND(LCASE(STR(?thumb_ship_original)) AS ?thumb_ship)
            FILTER(STRENDS(?thumb_ship, ".png") || STRENDS(?thumb_ship, ".jpg") || STRENDS(?thumb_ship, ".jpeg")) .
        }}
        }}                  
    }}
    }}
    VALUES (?some_emb) {{ ({test_tensor.to_literal().n3()}) }}         
}}
ORDER BY DESC(?dist)
LIMIT 10"""
    )
    easy_results = db.query_auto(
        test_tensor, query_type=QUERY_TYPE.INDEX, query_difficulty=QUERY_DIFFICULTY.EASY
    )

2026-04-24 14:42:12,628 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-04-24 14:42:12,628 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt.gz
2026-04-24 14:42:12,629 - WARNING - DB directory ../data/dbpedia/index-encoded already exists!
2026-04-24 14:42:12,629 - INFO - Stopping server!
2026-04-24 14:42:12,711 - ERROR - Command failed with return code 1
2026-04-24 14:42:12,712 - INFO - Starting QLever server on port 25943
2026-04-24 14:42:12,712 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25943 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-24 14:42:12,714 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-24 14:42:13,715 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-24 14:42:14,716 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-24 14:42:15,730 - INFO - Server is up and responding to queries
2026-04-24 14:42:22,790 - INFO - Stopping server!
2026-04-24 14:42:22,872 - ERROR - Command failed with return code 1

In [30]:
easy_results.to_csv(Path("scratch") / "dbpedia_easy_results.csv", index=False)
easy_results

,s,thumb_emb,dist
0,dbr:Plastiki,"{""data"": [0.2111155092716217, -0.3721050918102...",27.98868370056
1,dbr:La_Recouvrance_(schooner),"{""data"": [0.17521078884601593, -0.134947225451...",27.91348266602
2,dbr:Grace_Quan,"{""data"": [0.4119803309440613, -0.0349842160940...",27.79566192627
3,dbr:Naga_Pelangi,"{""data"": [0.3078002333641052, 0.20805418491363...",27.02926635742
4,dbr:MV_Uhuru,"{""data"": [0.10303764045238495, -0.229101330041...",27.02251815796
5,dbr:Original_six_frigates_of_the_United_States...,"{""data"": [0.3499048352241516, -0.0667797625064...",26.38556671143
6,dbr:T._J._Potter,"{""data"": [0.18704546988010406, 0.1744214743375...",26.16094970703
7,dbr:Rainbow_Warrior_(1957),"{""data"": [0.28070318698883057, -0.729847669601...",25.84356880188
8,dbr:PS_Comet,"{""data"": [0.3139987587928772, 0.04801601171493...",25.84019470215
9,dbr:Gorch_Fock_(1933),"{""data"": [0.08817720413208008, -0.622045218944...",25.55829238892

In [31]:
easy_results.loc[0, "s"], easy_results.loc[0, "thumb_emb"], easy_results.loc[0, "dist"]

('dbr:Plastiki',
 '{"data": [0.2111155092716217, -0.37210509181022644, -0.1256008744239807, 0.3913021981716156, 0.07871392369270325, -0.07938449829816818, 0.11866770684719086, 0.23398229479789734, 0.39779090881347656, -0.16861432790756226, -0.004371523857116699, -0.048737335950136185, 0.4543386399745941, 0.21892008185386658, -0.34641119837760925, -0.2010156363248825, 0.2572568655014038, 0.06256873905658722, 0.26309633255004883, 0.5121279954910278, -0.2595289349555969, 0.06514829397201538, -0.2721770107746124, 0.18661709129810333, 0.7871850728988647, 0.3414989709854126, -0.27971822023391724, 0.42073994874954224, 0.007892824709415436, 0.2540137767791748, 0.03973083198070526, 0.13429725170135498, -0.17217501997947693, 0.4178314805030823, -0.7641716599464417, -0.22243069112300873, -0.2509402632713318, 0.09269417822360992, 0.07116783410310745, 0.7140947580337524, 0.0005893222987651825, -0.07359926402568817, 0.004615098237991333, 0.39646783471107483, -0.10759720206260681, -1.586665391921997, 0.5840935707092285, 0.13181765377521515, -0.6910998821258545, 0.23412281274795532, -0.09404193609952927, -0.5126526355743408, 0.04990001022815704, -0.06954421103000641, 0.3054397404193878, 0.18438515067100525, -0.6058503985404968, -0.13146772980690002, -0.14460356533527374, 0.47883734107017517, 0.18902726471424103, 0.050501883029937744, -0.04272722452878952, 0.15458789467811584, 0.08990152925252914, -0.15886400640010834, 0.40512850880622864, 0.6430702805519104, -0.4533889889717102, -0.17179153859615326, 0.2892112135887146, -0.3248046636581421, 0.4029037356376648, -0.6845741271972656, -0.10949591547250748, -0.3183453381061554, -0.6095151305198669, -0.15013059973716736, -0.33291298151016235, 0.24915088713169098, 0.21288131177425385, 0.3222658634185791, -0.0376075804233551, -0.620922327041626, -0.04262268543243408, 0.16579195857048035, -0.4336744546890259, -0.1895216554403305, 0.022125765681266785, -0.43314871191978455, 0.2412448227405548, 0.05825447663664818, -7.579779624938965, -0.026906434446573257, 0.07222013175487518, 0.10293245315551758, -0.2163206785917282, -0.38005900382995605, 0.2839476466178894, -0.8495196104049683, 0.15516871213912964, 0.04522423446178436, -0.7856447100639343, 0.18450313806533813, 0.5913597941398621, 0.2448456585407257, -1.7669647932052612, -0.33009955286979675, -0.004564493894577026, 0.34030067920684814, 0.19358286261558533, -1.033766269683838, -0.11424949765205383, -0.17651847004890442, 0.0733647346496582, -0.30642062425613403, -0.14581294357776642, -0.4085216522216797, 0.0434691421687603, 0.06539696455001831, -0.43733930587768555, -0.4565944969654083, -0.2736642062664032, -0.32375970482826233, 0.13849279284477234, 0.12222947180271149, -0.17600056529045105, 0.41451495885849, -0.02569630742073059, 0.3043742775917053, 0.19498956203460693, -0.061597153544425964, -0.12385063618421555, 0.8921030759811401, -0.033035121858119965, 0.08858484029769897, 0.011325612664222717, -0.2560824751853943, -0.334884911775589, 0.2208898663520813, -0.022471662610769272, -0.4493499994277954, 0.18842238187789917, 2.7358531951904297e-05, 0.22030490636825562, 0.45935022830963135, -0.17652501165866852, -0.11080072820186615, -0.5506035089492798, 0.5520022511482239, 0.7048671841621399, 0.1144576221704483, 0.5811605453491211, 0.323241651058197, 0.017671337351202965, 0.21347349882125854, 0.179616779088974, 0.10891397297382355, 0.18353822827339172, 0.21936434507369995, 0.17744165658950806, -0.2192266285419464, 0.31422609090805054, -0.16318880021572113, 0.4781325161457062, 0.5199354290962219, 0.21012502908706665, 0.15663252770900726, 0.43417102098464966, 0.105648472905159, 0.20352071523666382, 0.11543931066989899, 0.24778294563293457, 0.1759689599275589, -0.32037249207496643, 0.04182535409927368, 0.44735094904899597, 0.22086839377880096, -0.2624565064907074, 0.5437909960746765, 0.004374900832772255, 0.11340413987636566, 0.012487977743148804, -0.002198144793510437, 0.1494222730398178, 0.026690104976296425, -0.1476355940103531, 0.24603381752967834, 0.1619325876235962, 0.0980277806520462, 0.2949308454990387, 0.28316614031791687, -0.08635812997817993, 0.019486460834741592, 0.2446495145559311, 0.11589258164167404, 0.18807393312454224, 0.24126790463924408, 0.000922083854675293, -0.24647416174411774, -0.19998915493488312, -0.5862705707550049, -0.00885877013206482, 0.761058509349823, -0.13968226313591003, -0.06016749143600464, -0.2678515315055847, -0.20806387066841125, -0.04523453861474991, -0.4170934557914734, 0.3492394685745239, -0.2400810420513153, -0.2748918831348419, -0.5660691261291504, -0.5578771829605103, 0.019538074731826782, 0.49554362893104553, -0.07778003811836243, -0.11199672520160675, -0.06398390233516693, 0.49274733662605286, -0.5400040149688721, -0.2915123403072357, 0.33934006094932556, 0.13985078036785126, 0.5108444094657898, 0.07555513828992844, -0.12062746286392212, 0.5396165251731873, 0.37521952390670776, 0.36614423990249634, 0.006928160786628723, -0.16368253529071808, -0.01577022671699524, -0.10397136211395264, -1.0534391403198242, -0.23124977946281433, -0.12908950448036194, 0.029996700584888458, 0.31284821033477783, 0.3263460397720337, -0.014456547796726227, 0.13667872548103333, 0.10717126727104187, 0.18712660670280457, 0.2677381634712219, 0.09520936012268066, 0.6322159767150879, 0.17392277717590332, -0.0011737719178199768, 0.034579481929540634, 0.2894115447998047, 0.41400933265686035, 0.009462907910346985, 0.2693836987018585, 0.23868384957313538, -0.32595929503440857, 0.250993549823761, 1.3503447771072388, 0.3725334405899048, -0.1975785195827484, -0.16311560571193695, 0.11080573499202728, 1.4647892713546753, -0.06123387813568115, -0.2593362331390381, 0.06430348753929138, 0.31182676553726196, -0.21071305871009827, -0.2432776838541031, -0.04461351037025452, 0.011877194046974182, -0.08508133143186569, 0.05006759613752365, 0.20189382135868073, 0.13439474999904633, -0.23134097456932068, -0.13824883103370667, -0.37333357334136963, 0.2795698344707489, 0.2555578947067261, -0.4208003878593445, -0.19077202677726746, 0.07442571967840195, -0.026256941258907318, 0.14482039213180542, 0.5032179951667786, -0.23254364728927612, -0.26371529698371887, 0.004903882741928101, 0.32296472787857056, 0.1720895916223526, -0.010888360440731049, 0.3523530960083008, 0.1464959681034088, -0.11091142892837524, -0.4318925738334656, 0.14108528196811676, 0.16141098737716675, -0.16902190446853638, -0.17042353749275208, 0.035466134548187256, -0.21736061573028564, 0.41902273893356323, 0.18468588590621948, 0.18417108058929443, 0.008071847259998322, 0.34101396799087524, 0.029815420508384705, -0.20062045753002167, -0.00459609180688858, 0.3020516037940979, 0.890518069267273, 0.16295957565307617, 0.5023419260978699, 0.11279359459877014, 0.04193706810474396, 0.21186496317386627, 0.021397937089204788, 0.09172600507736206, 0.0225537046790123, 1.2189083099365234, -0.13339167833328247, 0.017728392034769058, -0.3954966068267822, -0.15250477194786072, -0.4237605333328247, -0.21010461449623108, -0.14391794800758362, 0.09473837912082672, 0.09845716506242752, 0.05472191795706749, 0.20294535160064697, 0.3413305878639221, 0.15538986027240753, -0.07150468230247498, 0.030435269698500633, -0.024088596925139427, 0.10639220476150513, 0.5724055767059326, -0.10226098448038101, 0.16080236434936523, -0.03161977231502533, -0.5571320652961731, -0.03381235897541046, -0.27885955572128296, 0.02435162663459778, -0.12494660168886185, 0.4350423514842987, 0.13248203694820404, 0.03498576208949089, -0.27492591738700867, 0.00942870695143938, -0.31096500158309937, -0.20335739850997925, -0.5443659424781799, -0.4480486214160919, 0.5076159834861755, 0.21932148933410645, -0.07549481093883514, 0.07731537520885468, -0.22444090247154236, 0.025004103779792786, 0.07692624628543854, -0.1683993637561798, 0.6059564352035522, 0.1369774341583252, -0.6656949520111084, -0.0594116672873497, 0.03636176884174347, 0.15300768613815308, -0.012171633541584015, -0.05907679349184036, -0.3936735689640045, 0.6791471242904663, 0.46101003885269165, 0.9514609575271606, 0.3730071783065796, -0.5294170379638672, 0.39674246311187744, -0.015521571040153503, -0.1611497700214386, -0.06572287529706955, -0.29995080828666687, -0.0030733048915863037, 0.664715051651001, 0.15149419009685516, -0.05718030035495758, 0.22108253836631775, -0.03750714659690857, 0.03246679902076721, -0.3161410689353943, 0.13114723563194275, -0.33280280232429504, 0.12987178564071655, 0.23544485867023468, -0.2860477864742279, -0.1895940750837326, 0.3438044488430023, 0.7890835404396057, 0.1362452358007431, -0.2635955512523651, 0.27654755115509033, -0.025086991488933563, -0.3205038905143738, -0.1631261706352234, -0.014778165146708488, 0.36709555983543396, 0.29401010274887085, -0.31678980588912964, 0.8595573902130127, -0.10863910615444183, -0.6144465208053589, -0.047941919416189194, -0.3745715618133545, -0.05331387370824814, 0.07934848219156265, 0.19546276330947876, 0.24310854077339172, -0.17661753296852112, 0.06768247485160828, 0.16534511744976044, -0.16671791672706604, -0.6600334048271179, 0.08307560533285141, 0.1554459184408188, 0.6152133941650391, -0.17534735798835754, 1.0445799827575684, -0.3833715617656708, 0.11468176543712616, 0.10755670070648193, -0.19996725022792816, -0.3843153417110443, 0.4445037543773651, 0.1494760513305664, -0.2509792745113373, -0.290962278842926, 0.04483476281166077, 0.021856363862752914, 0.24278339743614197, -0.05395519733428955, -0.5610910654067993, -0.2917923629283905, -0.33507367968559265, 0.17663052678108215, -0.0403168685734272, 0.15876221656799316, -0.08325575292110443, -0.10248067229986191, -0.32456719875335693, -0.7385642528533936, -0.38184571266174316, -0.19475597143173218, -0.2519040107727051, -0.13887058198451996, -0.13527899980545044, 0.0427720844745636, -0.020519915968179703, -0.2745184004306793, -0.31961730122566223, 0.10003887116909027, -0.12897108495235443, -0.7156451940536499, 0.06432189792394638, -0.17138218879699707, 0.5834542512893677, -0.21497632563114166, -0.0892501026391983, -0.356100469827652, 0.12985104322433472, -0.1815258264541626, 0.20053771138191223, -0.06215379759669304, -0.23903295397758484, -0.006462112069129944, -0.19487926363945007, 0.04672880470752716, -0.14053143560886383, -0.1942605972290039, -0.05924270674586296, 0.05266830325126648, 0.44169753789901733, 0.012706875801086426, -0.09818284213542938, -0.1411905735731125, -0.2099919468164444, -0.06629401445388794, 0.37932920455932617, -0.17053501307964325, -0.397261381149292, -0.26601120829582214, 0.12079447507858276, -0.8027616739273071, 0.017326287925243378, -0.545390248298645, -0.12550053000450134, 0.37675249576568604, -0.4109480082988739, -0.12041491270065308, -0.09193633496761322, -0.426066517829895, -0.36927855014801025, 0.35973984003067017, 1.0892518758773804, 0.1980830430984497, 0.18009129166603088, -0.2122376561164856, -0.19189974665641785, 0.8450208902359009, 0.1736878752708435, -0.08655768632888794], "type": "float32", "shape": [512]}',
 '27.98868370056')

In [32]:
hard_results

,r,s,dist,thumb_rail_emb,thumb_ship_emb
0,dbr:Chengdu_Metro,dbr:Virginia-class_submarine,149.7555847168,"{""data"": [0.22622749209403992, 0.0546034500002...","{""data"": [-0.10002894699573517, -0.08042059838..."
1,dbr:Taipa_line,dbr:Virginia-class_submarine,148.5448455811,"{""data"": [0.03102342039346695, -0.059559382498...","{""data"": [-0.10002894699573517, -0.08042059838..."
2,dbr:Yangluo_Line,dbr:Virginia-class_submarine,146.525604248,"{""data"": [0.13901150226593018, 0.1055586785078...","{""data"": [-0.10002894699573517, -0.08042059838..."
3,dbr:Buenos_Aires_Underground,dbr:Virginia-class_submarine,140.4030609131,"{""data"": [-0.05835258960723877, -0.16195827722...","{""data"": [-0.10002894699573517, -0.08042059838..."
4,dbr:Line_13_(CPTM),dbr:Virginia-class_submarine,139.5791625977,"{""data"": [-0.21847796440124512, -0.04886087775...","{""data"": [-0.10002894699573517, -0.08042059838..."
5,dbr:Kolkata_Metro,dbr:I-201-class_submarine,139.0804901123,"{""data"": [-0.0022863298654556274, -0.211197406...","{""data"": [0.0012263432145118713, -0.0422745048..."
6,dbr:Orlyval,dbr:Virginia-class_submarine,138.4921875,"{""data"": [0.11910116672515869, -0.394591093063...","{""data"": [-0.10002894699573517, -0.08042059838..."
7,dbr:Abbey_Line,dbr:Virginia-class_submarine,138.0496826172,"{""data"": [0.18120601773262024, -0.300545185804...","{""data"": [-0.10002894699573517, -0.08042059838..."
8,dbr:London_Overground,dbr:Virginia-class_submarine,137.636428833,"{""data"": [0.02959146350622177, 0.0380432158708...","{""data"": [-0.10002894699573517, -0.08042059838..."
9,dbr:CDGVAL,dbr:Virginia-class_submarine,135.4937896729,"{""data"": [-0.1729656457901001, 0.0039286464452...","{""data"": [-0.10002894699573517, -0.08042059838..."

In [33]:
# load images for both results
from utils.dbs.base_db import BaseDB


def enhance_col_with_thumbs(
    db: BaseDB, df: pd.DataFrame, dbr_col: str, thumb_col_name="thumb"
) -> pd.DataFrame:

    thumbs = []
    g = tqdm.tqdm(df[dbr_col], desc=f"Fetching thumbnails for {thumb_col_name}")
    for s in g:
        g.set_description(f"Fetching thumbnails for {thumb_col_name}: '{s}'")
        s = f"<{s.replace('dbr:', 'http://dbpedia.org/resource/')}>"
        res = db.query(f"""PREFIX dbr: <http://dbpedia.org/resource/>
                            PREFIX dbo: <http://dbpedia.org/ontology/>
                            SELECT ?thumb ?thumb_lc WHERE {{
                                {s} dbo:thumbnail_original ?thumb .
                                BIND (LCASE(STR(?thumb)) AS ?thumb_lc) 
                                FILTER (STRENDS(?thumb_lc, ".png") || STRENDS(?thumb_lc, ".jpg") || STRENDS(?thumb_lc, ".jpeg"))
                            }} LIMIT 1""")
        # print(f"Query result for {s}: {res}")
        if len(res) > 0:
            thumbs.append(res["thumb"].values[0])
        else:
            thumbs.append(None)
    df[thumb_col_name] = thumbs
    return df


with db_qlever as db:
    easy_results = enhance_col_with_thumbs(db, easy_results, "s")
    hard_results = enhance_col_with_thumbs(
        db, hard_results, "s", thumb_col_name="thumb_s"
    )
    hard_results = enhance_col_with_thumbs(
        db, hard_results, "r", thumb_col_name="thumb_r"
    )

2026-04-24 14:42:23,169 - INFO - Logging QLever setup to scratch/dbpedia/db/qlever-with-tidx/qlever-with-tidx_run.log
2026-04-24 14:42:23,170 - INFO - Loading dataset into QLever server from ../data/dbpedia/dbpedia_complete.nt.gz

2026-04-24 14:42:23,170 - WARNING - DB directory ../data/dbpedia/index-encoded already exists!
2026-04-24 14:42:23,171 - INFO - Stopping server!
2026-04-24 14:42:23,248 - ERROR - Command failed with return code 1
2026-04-24 14:42:23,248 - INFO - Starting QLever server on port 25943
2026-04-24 14:42:23,248 - INFO - Running command: qlever-server -i dbpedia-encoded-tidx --port 25943 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-24 14:42:23,250 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-24 14:42:24,251 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-24 14:42:25,253 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:25943/qlever-with-tidx/sparql)
2026-04-24 14:42:26,265 - INFO - Server is up and responding to queries
Fetching thumbnails for thumb: 'dbr:Gorch_Fock_(1933)': 100%|██████████| 10/10 [00:00<00:00, 169.28it/s]
Fetching thumbnails for thumb_s: 'dbr:Virginia-class_submarine': 100%|██████████| 10/10 [00:00<00:00, 192.25it/s]
Fetching thumbnails for thumb_r: 'dbr:CDGVAL': 100%|██████████| 10/10 [00:00<00:00, 194.50it/s]
2026-04-24 14:42:26,434 - INFO - Stopping server!
2026-04-24 14:42:26,515 - ERROR - Command failed with return code 1

In [34]:
hard_results.to_csv(Path("scratch") / "dbpedia_hard_results.csv", index=False)
easy_results.to_csv(Path("scratch") / "dbpedia_easy_results.csv", index=False)

In [35]:
easy_results.loc[0, 'thumb'].split('/')[-1]

'Plastiki_hull_closeup.jpg'

## Token

You need to set your Oauth tokens in the local `.env`:
```sh
MEDIA_WIKI_TOKEN="..."
MEDIA_WIKI_SECRET="..."
MEDIA_WIKI_ACCESS_TOKEN="..."
MEDIA_WIKI_ACCESS_SECRET="..."
```
You can register a new token [here](https://meta.wikimedia.org/wiki/Special:OAuthConsumerRegistration/propose/oauth1a).

In [36]:
import requests
from requests_oauthlib import OAuth1
import dotenv
from utils.datasets.dbpedia_utils.helpers import USER_AGENT

dotenv.load_dotenv()  # to load MEDIAWIKI_TOKEN from .env file

auth = OAuth1(
    os.getenv("MEDIA_WIKI_TOKEN"),
    os.getenv("MEDIA_WIKI_SECRET"),
    os.getenv("MEDIA_WIKI_ACCESS_TOKEN"),
    os.getenv("MEDIA_WIKI_ACCESS_SECRET"),
)

In [37]:
auth.client

<Client client_key=eea9f51d9008d744c272c3ece851b184, client_secret=****, resource_owner_key=914b284deef1f1f0525ea803d55914b0, resource_owner_secret=****, signature_method=HMAC-SHA1, signature_type=AUTH_HEADER, callback_uri=None, rsa_key=None, verifier=None, realm=None, encoding=utf-8, decoding=utf-8, nonce=None, timestamp=None>

In [38]:
url=f"https://commons.wikimedia.org/wiki/Special:FilePath/{easy_results.loc[0, 'thumb'].split('/')[-1]}?width=330"
resp = requests.get(
    url,
    auth=auth,
    headers={"User-Agent": USER_AGENT},
)

In [47]:
import pywikibot

pywikibot.config.usernames['commons']['commons'] = "Dakantz"
# set user-agent

authenticate = (
    os.getenv("MEDIA_WIKI_TOKEN"),
    os.getenv("MEDIA_WIKI_SECRET"),
    os.getenv("MEDIA_WIKI_ACCESS_TOKEN"),
    os.getenv("MEDIA_WIKI_ACCESS_SECRET"),
)
pywikibot.config.authenticate['commons.wikimedia.org'] = authenticate
pywikibot.config.user_agent = USER_AGENT
site = pywikibot.Site('commons', 'commons')
site.login()

In [53]:
site.allimages()

In [68]:
from PIL import Image
fname = easy_results.loc[0, "thumb"].split("/")[-1]
img = pywikibot.FilePage(site, fname)

img.download(filename=fname, url_width=330)
img = Image.open(fname)

In [71]:
from utils.datasets.dbpedia_utils import image_formatter


def thumbs_to_pil(
    thumbs: pd.Series, scratch_dir=Path("../scratch/dbpedia_thumbs")
) -> pd.Series:

    scratch_dir.mkdir(parents=True, exist_ok=True)
    pil_images = []
    g = tqdm.tqdm(thumbs, desc="Fetching thumbnails")
    for thumb in g:
        g.set_description(f"Fetching thumbnail for {thumb}...")
        # url_thumb = get_wc_thumb(thumb)

        fname = thumb.split("/")[-1]
        out_f = scratch_dir / fname
        if not out_f.exists():
            img = pywikibot.FilePage(site, fname)
            img.download(filename=out_f, url_width=330)
        img = Image.open(out_f)
        pil_images.append(img)
    return pd.Series(pil_images, index=thumbs.index)


easy_results["thumb_img"] = thumbs_to_pil(easy_results["thumb"])
hard_results["thumb_s_img"] = thumbs_to_pil(hard_results["thumb_s"])
hard_results["thumb_r_img"] = thumbs_to_pil(hard_results["thumb_r"])

Fetching thumbnail for https://upload.wikimedia.org/wikipedia/commons/0/04/Plastiki_hull_closeup.jpg...:   0%|          | 0/10 [00:00<?, ?it/s]Sleeping for 60.0 seconds, 2026-04-24 15:01:31
Fetching thumbnail for http://upload.wikimedia.org/wikipedia/commons/5/54/2006Boston088.jpg...:  50%|█████     | 5/10 [01:11<00:39,  7.81s/it]         WARNING: Http response status 429
WARNING: Unsuccessful request (429): https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/2006Boston088.jpg/330px-2006Boston088.jpg
Fetching thumbnail for http://upload.wikimedia.org/wikipedia/commons/5/54/2006Boston088.jpg...:  50%|█████     | 5/10 [01:14<01:14, 14.86s/it]

FileNotFoundError: [Errno 2] No such file or directory: '../scratch/dbpedia_thumbs/2006Boston088.jpg'

In [ ]:
out_dir = Path("../scratch/results/")


def to_tex_with_thumbs(
    df,
    t_cols=["thumb_img"],
    col_mapping={
        "s": "Ship",
        "r": "Railway",
        "thumb_img_tex": "Thumbnail",
        "dist": "Distance",
    },
    base_dir="figures/generated",
    sub_dir="dbpedia/media",
    out_name="dbpedia_easy_results.tex",
    col_format ="lp{3cm}r"
):
    out_dir.mkdir(parents=True, exist_ok=True)
    results_dir = Path(out_dir) / sub_dir
    results_dir.mkdir(parents=True, exist_ok=True)
    fig_dir = Path(base_dir) / sub_dir
    for t_col in t_cols:
        df[f"{t_col}_tex"] = df[t_col]
        
        for i, r in df.iterrows():
            if r[t_col] is not None and isinstance(r[t_col], Image.Image):
                fname = f"{t_col}_{i}.png"
                fig_file = fig_dir / fname
                im_file = results_dir / fname
                df.at[i, f"{t_col}_tex"] = f"\\includegraphics[width=3cm]{{{fig_file}}}"
                print(f"Saving image for row {i} to {im_file} and referencing as {fig_file} in LaTeX", r[t_col])
                img: Image = r[t_col]
                img.save(im_file)
            else:
                df.at[i, f"{t_col}_tex"] = "No image"
    df_renamed = df.rename(columns=col_mapping)
    print(f"Renamed columns for LaTeX: {df_renamed.columns}")
    allowed_cols = [c for c in list(col_mapping.values()) if c in df_renamed.columns]
    print(f"Allowed columns for LaTeX output: {allowed_cols}")
    df_renamed = df_renamed[allowed_cols]
    df_renamed.set_index(allowed_cols[0], inplace=True)
    df_renamed.style.to_latex(
        buf= results_dir / out_name,
        column_format=col_format,
    )


to_tex_with_thumbs(easy_results)

Saving image for row 0 to ../scratch/results/dbpedia/media/thumb_img_0.png and referencing as figures/generated/dbpedia/media/thumb_img_0.png in LaTeX <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=330x247 at 0x7FF50012B5C0>
Saving image for row 1 to ../scratch/results/dbpedia/media/thumb_img_1.png and referencing as figures/generated/dbpedia/media/thumb_img_1.png in LaTeX <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=330x217 at 0x7FF500128050>
Saving image for row 2 to ../scratch/results/dbpedia/media/thumb_img_2.png and referencing as figures/generated/dbpedia/media/thumb_img_2.png in LaTeX <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=330x250 at 0x7FF4FBFE3360>
Renamed columns for LaTeX: Index(['Ship', 'thumb_emb', 'Distance', 'thumb', 'thumb_img', 'Thumbnail'], dtype='str')
Allowed columns for LaTeX output: ['Ship', 'Thumbnail', 'Distance']