In [58]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [59]:
import tqdm
import sys
import os

In [60]:
from sentence_transformers import SentenceTransformer

encoding_model = SentenceTransformer("all-MiniLM-L6-v2")

2026-08-19 09:58:35,802 - INFO - Use pytorch device_name: cpu
2026-08-19 09:58:35,802 - INFO - Load pretrained SentenceTransformer: all-MiniLM-L6-v2

2026-08-19 09:58:36,017 - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-08-19 09:58:36,033 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/modules.json "HTTP/1.1 200 OK"
2026-08-19 09:58:36,167 - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-08-19 09:58:36,184 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-08-19 09:58:36,314 - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-08-19 09:58:36,331 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-08-19 09:58:36,463 - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-08-19 09:58:36,479 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/README.md "HTTP/1.1 200 OK"
2026-08-19 09:58:36,615 - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-08-19 09:58:36,632 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/modules.json "HTTP/1.1 200 OK"
2026-08-19 09:58:36,838 - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-19 09:58:36,854 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-08-19 09:58:37,028 - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-08-19 09:58:37,239 - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-19 09:58:37,256 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/config.json "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-08-19 09:58:37,431 - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-19 09:58:37,448 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/config.json "HTTP/1.1 200 OK"
2026-08-19 09:58:37,582 - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-19 09:58:37,599 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/tokenizer_config.json "HTTP/1.1 200 OK"
2026-08-19 09:58:37,736 - INFO - HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L6-v2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-08-19 09:58:37,873 - INFO - HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L6-v2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-08-19 09:58:38,072 - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-19 09:58:38,089 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-08-19 09:58:38,223 - INFO - HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L6-v2 "HTTP/1.1 200 OK"

In [61]:
import dotenv
import os

config = dotenv.dotenv_values(".env")
replace_keys = ["JAVA_HOME", "FUSEKI_HOME"]
append_keys = ["PATH"]
for key, value in config.items():
    # append to os.environ
    if key in append_keys:
        os.environ[key] = f"{os.environ.get(key, '')}:{value}"
    elif key in replace_keys:
        os.environ[key] = value

# check and compare values in fuseki log
os.environ["OPENBLAS_NUM_THREADS"] = "4"

In [62]:
sys.path.append(".")

In [63]:
from utils.datasets import SimpleSet, BerlinSparqlBenchmark
from utils.dbs.qlever import QleverDB
from utils.dbs.fuseki import FusekiDB
from utils.dbs.base_db import BaseDB
from utils.dbs.qlever_native import QleverDBNative
from utils.dbs.fuseki_native import FusekiDBNative
from utils.datasets.base_dataset import QUERY_DIFFICULTY, QUERY_TYPE
from pathlib import Path
import pandas as pd
import numpy as np
from utils.datasets.base_dataset import DataTensor

In [64]:
powers = np.arange(0, 6)  # extend on a more powerful machine
sizes = 10**powers

In [65]:
datasets: dict[int, BerlinSparqlBenchmark] = {}
raw_sizes: dict[int, int] = {}
for power, size in zip(powers, sizes):
    print(f"Running BDSDM generation for size {size}...")
    dataset = BerlinSparqlBenchmark(base_dir=Path(f"./data/bsbm_{power}"), n=size)
    dataset.setup()
    datasets[power] = dataset
    # raw_sizes[power] = dataset.get_triple_count()

2026-08-19 09:58:38,665 - INFO - BSBM dataset already exists in data/bsbm_0, skipping generation
2026-08-19 09:58:38,665 - INFO - BSBM dataset already exists in data/bsbm_1, skipping generation
2026-08-19 09:58:38,666 - INFO - BSBM dataset already exists in data/bsbm_2, skipping generation
2026-08-19 09:58:38,666 - INFO - BSBM dataset already exists in data/bsbm_3, skipping generation
2026-08-19 09:58:38,666 - INFO - BSBM dataset already exists in data/bsbm_4, skipping generation
2026-08-19 09:58:38,667 - INFO - BSBM dataset already exists in data/bsbm_5, skipping generation

Running BDSDM generation for size 1...
Running BDSDM generation for size 10...
Running BDSDM generation for size 100...
Running BDSDM generation for size 1000...
Running BDSDM generation for size 10000...
Running BDSDM generation for size 100000...

In [66]:
encoded_sizes: dict[int, int] = {}
for power, size in zip(powers, sizes):
    print(f"Encoding dataset of size {size}/power {power}...")
    dataset = datasets[power]
    encoded_sizes[power] = dataset.encode(encoding_model)
    #  dataset.get_triple_count(encoded=True)

Encoding dataset of size 1/power 0...
Encoded TTL file already exists at data/bsbm_0/dataset_encoded.nt, skipping encoding
Encoding dataset of size 10/power 1...
Encoded TTL file already exists at data/bsbm_1/dataset_encoded.nt, skipping encoding
Encoding dataset of size 100/power 2...
Encoded TTL file already exists at data/bsbm_2/dataset_encoded.nt, skipping encoding
Encoding dataset of size 1000/power 3...
Encoded TTL file already exists at data/bsbm_3/dataset_encoded.nt, skipping encoding
Encoding dataset of size 10000/power 4...
Encoded TTL file already exists at data/bsbm_4/dataset_encoded.nt, skipping encoding
Encoding dataset of size 100000/power 5...
Encoded TTL file already exists at data/bsbm_5/dataset_encoded.nt, skipping encoding

## BSBM queries

### Simple Use case: 
find 10 products with a specific encoded label


### Complex Use case: 
For a specific product find 10 other similar products via their product label.

In [67]:
test_label = "house furniture storage container"
test_tensor = DataTensor.from_numpy(encoding_model.encode(test_label))

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [68]:
test_tensor.to_literal().n3()

'"{\\"data\\": [0.001923849806189537, 0.059069667011499405, -0.06259278953075409, -0.008788925595581532, 0.08017760515213013, 0.0004897266626358032, 0.049011558294296265, -0.016156358644366264, -0.04537816718220711, 0.011929630301892757, -0.003551364177837968, -0.0034783161245286465, 0.023264417424798012, 0.02449001744389534, -0.023595571517944336, -0.073823943734169, 0.014226873405277729, -0.00022305997845251113, -0.03111756220459938, 0.07163400948047638, -0.04559392109513283, 0.044428009539842606, 0.0004388350062072277, -0.004044292028993368, 0.05173112079501152, 0.08436278998851776, -0.028667306527495384, -0.032494205981492996, 0.058949727565050125, -0.0051073553040623665, 0.09506019204854965, -0.029170090332627296, -0.07172352075576782, 0.036426812410354614, 0.01788988709449768, 0.07774496078491211, -0.01058284193277359, -0.02719942107796669, -0.014839782379567623, 0.004996407311409712, -0.05195301026105881, -0.01563340425491333, -0.0004883587826043367, 0.012572054751217365, -0.043422963470220566, -0.011021864600479603, -0.024199120700359344, -0.030226601287722588, 0.04542998597025871, -0.007276976015418768, 0.01397930271923542, 0.050883397459983826, -0.01848265342414379, 0.049168676137924194, -0.008279561065137386, 0.044504038989543915, 0.04745961353182793, 0.043078307062387466, -0.046442680060863495, 0.036845613270998, 0.10432934015989304, -0.015816830098628998, 0.10823524743318558, -0.028953377157449722, 0.04555060341954231, -0.030880587175488472, -0.051015835255384445, 0.05478580296039581, -0.0291702002286911, -0.005334345158189535, -0.06260965764522552, 0.034982938319444656, 0.026750046759843826, 0.04171916842460632, 0.03431631997227669, -0.07216819375753403, -0.00024255513562820852, -0.048893045634031296, 0.02389506623148918, 0.12748239934444427, -0.08703242987394333, 0.03412925824522972, 0.02240350842475891, 0.002564689377322793, -0.17344096302986145, 0.04103534668684006, -0.017823603004217148, -0.0076851267367601395, -0.09476081281900406, -0.07406330108642578, 0.08501428365707397, 0.04020910710096359, 0.08708695322275162, -0.026967616751790047, -0.060038503259420395, -0.003988019190728664, -0.02539210394024849, 0.022482113912701607, 0.060429759323596954, 0.037002742290496826, -0.0065333242528140545, 0.021862275898456573, 0.00022625424026045948, -0.033486779779195786, -0.07245824486017227, -0.1024286150932312, 0.049249906092882156, -0.009056593291461468, 0.007512359414249659, 0.0021412500645965338, -0.09075023233890533, 0.040666837245225906, -0.06107519939541817, -0.002982238307595253, -0.06842709332704544, 0.0025372530799359083, -0.01641230843961239, -0.043180201202631, 0.039085742086172104, -0.10427255183458328, 0.0473635196685791, -0.019185954704880714, 0.05296330899000168, 0.019953425973653793, 0.0329863503575325, 0.03303090110421181, 0.04857225716114044, 7.191068898027963e-35, -0.018325448036193848, -0.06909802556037903, 0.024108240380883217, 0.04407642409205437, 0.06294272840023041, 0.029094791039824486, 0.06375113874673843, 0.07381084561347961, 0.0368872731924057, 0.019980719313025475, -0.013145486824214458, -0.027676766738295555, -0.10194964706897736, -0.002321777166798711, -0.0032931924797594547, -0.02191285789012909, -0.09255401045084, 0.03210889920592308, 0.015278536826372147, -0.04234621301293373, 0.0064256093464791775, 0.04209345206618309, -0.019585780799388885, 0.03202011436223984, 0.037421416491270065, -0.018620574846863747, 0.019987355917692184, -0.013685979880392551, -0.03424428403377533, 0.012987463735044003, 0.04883616417646408, -0.0011513904901221395, -0.008845774456858635, 0.005870802327990532, -0.07762148231267929, -0.025999465957283974, -0.06829018890857697, 0.018836436793208122, -0.02234852872788906, -0.07037260383367538, 0.012542112730443478, 0.03438114747405052, 0.14274704456329346, 0.07548227161169052, 0.008455806411802769, -0.02049204707145691, 0.004560847766697407, -0.025547219440340996, -0.11879655718803406, 0.001291911699809134, -0.03331619128584862, 0.025502456352114677, -0.09485730528831482, 0.08408985286951065, -0.05816476047039032, -0.029875924810767174, -0.01281525194644928, -0.06466028094291687, 0.0453050322830677, 0.004283205606043339, 0.035003237426280975, 0.04375073313713074, 0.043108899146318436, -0.001907631172798574, 0.016851212829351425, -0.026979830116033554, 0.010974003002047539, 0.016453053802251816, 0.09936032444238663, 0.009172468446195126, 0.007693963125348091, -0.00969709176570177, 0.023047752678394318, -0.021144036203622818, 0.03724559023976326, -0.013058981858193874, -0.029100554063916206, 0.01229681633412838, -0.09894735366106033, -0.12643840909004211, 0.04589775577187538, -0.07361725717782974, 0.04434674605727196, 0.050329189747571945, -0.06559285521507263, -0.09371957182884216, 0.024369491264224052, -0.01520457398146391, -0.0038548363372683525, 0.027220020070672035, -0.031000541523098946, 0.015559685416519642, -0.006960012950003147, -0.041212767362594604, -0.08390278369188309, -4.97649344593706e-34, 0.05890499800443649, -0.06461971998214722, -0.07525855302810669, 0.058098528534173965, 0.06788986176252365, 0.019036881625652313, -0.007119014859199524, -0.043491482734680176, -0.017167028039693832, -0.04744131118059158, -0.04438185319304466, 0.0017611982766538858, 0.11509203165769577, 0.055401794612407684, -0.04163767397403717, 0.06279648095369339, -0.004321553744375706, -0.06458307802677155, 0.04710076004266739, 0.027388490736484528, -0.028406115248799324, -0.0031859995797276497, 0.01728656329214573, 0.03930680826306343, -0.042606621980667114, -0.03965207189321518, 0.050438474863767624, -0.05095212534070015, -0.009358619339764118, -0.005097959190607071, -0.042747560888528824, -0.09899874031543732, 0.046798769384622574, 0.06118430569767952, -0.029022959992289543, -0.11554227024316788, -0.011058848351240158, -0.036974892020225525, -0.08948592841625214, -0.014271756634116173, 0.013834885321557522, -0.01605868525803089, -0.04475671425461769, 0.03806497901678085, -0.05086902156472206, -0.06123126670718193, -0.08582713454961777, 0.018628671765327454, 0.10956262052059174, 0.03865630552172661, -0.005097296088933945, -0.024105655029416084, -0.012989535927772522, -0.07685093581676483, -0.00417094212025404, 0.089471735060215, -0.005915124900639057, 0.014249371364712715, -0.013326791115105152, 0.1283029317855835, -0.0087217316031456, 0.10300467163324356, 0.03298785537481308, -0.011241207830607891, 0.024034647271037102, 0.048094574362039566, 0.011020636186003685, -0.037912674248218536, -0.05348319187760353, 0.025995740666985512, 0.1147560179233551, 0.023856690153479576, 0.08506986498832703, 0.1052437573671341, 0.003146340372040868, -0.06395517289638519, 0.09612903743982315, -0.013588497415184975, 0.07226214557886124, 0.008729256689548492, -0.03723451867699623, -0.011913117952644825, 0.00031532489811070263, 0.007079592905938625, 0.03848397731781006, -0.09682920575141907, -0.014785494655370712, 0.002893038559705019, -0.06805280596017838, 0.0401400662958622, -0.022343454882502556, 0.08511822670698166, -0.13211962580680847, 0.03063001111149788, 0.0910293459892273, -1.2904515678258122e-08, -0.04676821827888489, -0.006705537438392639, 0.022972706705331802, -0.022980324923992157, -0.07330192625522614, -0.05493609607219696, 0.147051140666008, 0.07781931012868881, 0.032597970217466354, -0.04455342888832092, 0.011822628788650036, -0.0011622520396485925, -0.08087407797574997, -0.029209928587079048, -0.04869680851697922, 0.01635807752609253, -0.013975921086966991, 0.02993103303015232, -0.02186085842549801, 0.027337562292814255, 0.06173807755112648, -0.05552144721150398, 0.11173667758703232, -0.002850713673979044, 0.0067396159283816814, -0.014453276060521603, 0.03404010832309723, 0.06328174471855164, 0.09785991162061691, 0.016026383265852928, 0.02463620714843273, 0.010196371003985405, 0.03231675177812576, 0.03482783958315849, 0.012972479686141014, 0.06374970823526382, -0.12293172627687454, -0.01703498885035515, -0.028862323611974716, -0.036092162132263184, -0.0514722540974617, -0.11512449383735657, -0.012429235503077507, -0.08940501511096954, 0.06870079040527344, 0.026553628966212273, -0.03257280960679054, 0.046524085104465485, 0.00020684042829088867, 0.06025783717632294, -0.015267660841345787, 0.0010977181373164058, 0.005369286052882671, 0.03770275413990021, 0.023572636768221855, 0.0035807902459055185, -0.03384198620915413, -0.026205267757177353, 0.06975211203098297, 0.020543193444609642, -0.015171892009675503, 0.05312025547027588, 0.014551732689142227, 0.02318691834807396], \\"type\\": \\"float32\\", \\"shape\\": [384]}"^^<https://w3id.org/rdf-tensor/datatypes#NumericDataTensor>'

In [69]:
base_bsbm_set = datasets[3]
db_with_tensor_idx = QleverDBNative(
    id="test",
    base_dir=Path(f"./scratch/bsbm/{base_bsbm_set.base_dir.name}"),
    dataset=base_bsbm_set,
    use_encoded_ttl=True,
    name="QLever",
)
db_no_tensor_idx = QleverDBNative(
    id="test",
    base_dir=Path(f"./scratch/bsbm/{base_bsbm_set.base_dir.name}"),
    dataset=base_bsbm_set,
    use_encoded_ttl=True,
    name="QLever (no Tensor Vocabulary)",
    enable_tensor_index=False,
)
db_fuseki = FusekiDBNative(
    id="test_fuseki",
    base_dir=Path(f"./scratch/bsbm/{base_bsbm_set.base_dir.name}"),
    dataset=base_bsbm_set,
    use_encoded_ttl=True,
    name="Fuseki + RDFTensor",
)
possible_queries = db_with_tensor_idx.get_queries(test_tensor)

from utils.dbs.executable_db import ExecutableDB

dbs:list[ExecutableDB] = [db_with_tensor_idx, db_no_tensor_idx, db_fuseki]
print(possible_queries)

2026-08-19 09:58:39,624 - WARNING - Killing any existing process using port 26052 before starting the server
2026-08-19 09:58:39,637 - ERROR - Command failed with return code 1
2026-08-19 09:58:39,637 - INFO - Initialized QLeverDBNative with id=test, port_id=26052, dataset=bsbm, name=QLever, use_encoded_ttl=True, endpoint=http://localhost:26052/test-with-tidx/sparql
2026-08-19 09:58:39,638 - WARNING - Killing any existing process using port 26053 before starting the server
2026-08-19 09:58:39,649 - ERROR - Command failed with return code 1
2026-08-19 09:58:39,649 - INFO - Initialized QLeverDBNative with id=test, port_id=26053, dataset=bsbm, name=QLever (no Tensor Vocabulary), use_encoded_ttl=True, endpoint=http://localhost:26053/test-no-tidx/sparql
2026-08-19 09:58:39,651 - WARNING - Killing any existing process using port 29054 before starting the server

2026-08-19 09:58:39,661 - ERROR - Command failed with return code 1

{<QUERY_DIFFICULTY.EASY: 'easy'>: {<QUERY_TYPE.EMBEDDED: 'embedded'>: '\nPREFIX dt: <https://w3id.org/rdf-tensor/datatypes#>\nPREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#>\nPREFIX dtf: <https://w3id.org/rdf-tensor/functions#>\nPREFIX bsbmi: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>\nPREFIX bsbmv: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>\nSELECT DISTINCT ?product  ?vector ?dist \nWHERE {\n?product rdf:label_embedding ?vector .\n?product bsbmv:productFeature ?feat .\nBIND(dtf:cosineSimilarity(?vector, "{\\"data\\": [0.001923849806189537, 0.059069667011499405, -0.06259278953075409, -0.008788925595581532, 0.08017760515213013, 0.0004897266626358032, 0.049011558294296265, -0.016156358644366264, -0.04537816718220711, 0.011929630301892757, -0.003551364177837968, -0.0034783161245286465, 0.023264417424798012, 0.02449001744389534, -0.023595571517944336, -0.073823943734169, 0.014226873405277729, -0.00022305997845251113, -0.03111756220459938, 0.07163400948047638, -0.04559392109513283, 0.044428009539842606, 0.0004388350062072277, -0.004044292028993368, 0.05173112079501152, 0.08436278998851776, -0.028667306527495384, -0.032494205981492996, 0.058949727565050125, -0.0051073553040623665, 0.09506019204854965, -0.029170090332627296, -0.07172352075576782, 0.036426812410354614, 0.01788988709449768, 0.07774496078491211, -0.01058284193277359, -0.02719942107796669, -0.014839782379567623, 0.004996407311409712, -0.05195301026105881, -0.01563340425491333, -0.0004883587826043367, 0.012572054751217365, -0.043422963470220566, -0.011021864600479603, -0.024199120700359344, -0.030226601287722588, 0.04542998597025871, -0.007276976015418768, 0.01397930271923542, 0.050883397459983826, -0.01848265342414379, 0.049168676137924194, -0.008279561065137386, 0.044504038989543915, 0.04745961353182793, 0.043078307062387466, -0.046442680060863495, 0.036845613270998, 0.10432934015989304, -0.015816830098628998, 0.10823524743318558, -0.028953377157449722, 0.04555060341954231, -0.030880587175488472, -0.051015835255384445, 0.05478580296039581, -0.0291702002286911, -0.005334345158189535, -0.06260965764522552, 0.034982938319444656, 0.026750046759843826, 0.04171916842460632, 0.03431631997227669, -0.07216819375753403, -0.00024255513562820852, -0.048893045634031296, 0.02389506623148918, 0.12748239934444427, -0.08703242987394333, 0.03412925824522972, 0.02240350842475891, 0.002564689377322793, -0.17344096302986145, 0.04103534668684006, -0.017823603004217148, -0.0076851267367601395, -0.09476081281900406, -0.07406330108642578, 0.08501428365707397, 0.04020910710096359, 0.08708695322275162, -0.026967616751790047, -0.060038503259420395, -0.003988019190728664, -0.02539210394024849, 0.022482113912701607, 0.060429759323596954, 0.037002742290496826, -0.0065333242528140545, 0.021862275898456573, 0.00022625424026045948, -0.033486779779195786, -0.07245824486017227, -0.1024286150932312, 0.049249906092882156, -0.009056593291461468, 0.007512359414249659, 0.0021412500645965338, -0.09075023233890533, 0.040666837245225906, -0.06107519939541817, -0.002982238307595253, -0.06842709332704544, 0.0025372530799359083, -0.01641230843961239, -0.043180201202631, 0.039085742086172104, -0.10427255183458328, 0.0473635196685791, -0.019185954704880714, 0.05296330899000168, 0.019953425973653793, 0.0329863503575325, 0.03303090110421181, 0.04857225716114044, 7.191068898027963e-35, -0.018325448036193848, -0.06909802556037903, 0.024108240380883217, 0.04407642409205437, 0.06294272840023041, 0.029094791039824486, 0.06375113874673843, 0.07381084561347961, 0.0368872731924057, 0.019980719313025475, -0.013145486824214458, -0.027676766738295555, -0.10194964706897736, -0.002321777166798711, -0.0032931924797594547, -0.02191285789012909, -0.09255401045084, 0.03210889920592308, 0.015278536826372147, -0.04234621301293373, 0.0064256093464791775, 0.04209345206618309, -0.019585780799388885, 0.03202011436223984, 0.037421416491270065, -0.018620574846863747, 0.019987355917692184, -0.013685979880392551, -0.03424428403377533, 0.012987463735044003, 0.04883616417646408, -0.0011513904901221395, -0.008845774456858635, 0.005870802327990532, -0.07762148231267929, -0.025999465957283974, -0.06829018890857697, 0.018836436793208122, -0.02234852872788906, -0.07037260383367538, 0.012542112730443478, 0.03438114747405052, 0.14274704456329346, 0.07548227161169052, 0.008455806411802769, -0.02049204707145691, 0.004560847766697407, -0.025547219440340996, -0.11879655718803406, 0.001291911699809134, -0.03331619128584862, 0.025502456352114677, -0.09485730528831482, 0.08408985286951065, -0.05816476047039032, -0.029875924810767174, -0.01281525194644928, -0.06466028094291687, 0.0453050322830677, 0.004283205606043339, 0.035003237426280975, 0.04375073313713074, 0.043108899146318436, -0.001907631172798574, 0.016851212829351425, -0.026979830116033554, 0.010974003002047539, 0.016453053802251816, 0.09936032444238663, 0.009172468446195126, 0.007693963125348091, -0.00969709176570177, 0.023047752678394318, -0.021144036203622818, 0.03724559023976326, -0.013058981858193874, -0.029100554063916206, 0.01229681633412838, -0.09894735366106033, -0.12643840909004211, 0.04589775577187538, -0.07361725717782974, 0.04434674605727196, 0.050329189747571945, -0.06559285521507263, -0.09371957182884216, 0.024369491264224052, -0.01520457398146391, -0.0038548363372683525, 0.027220020070672035, -0.031000541523098946, 0.015559685416519642, -0.006960012950003147, -0.041212767362594604, -0.08390278369188309, -4.97649344593706e-34, 0.05890499800443649, -0.06461971998214722, -0.07525855302810669, 0.058098528534173965, 0.06788986176252365, 0.019036881625652313, -0.007119014859199524, -0.043491482734680176, -0.017167028039693832, -0.04744131118059158, -0.04438185319304466, 0.0017611982766538858, 0.11509203165769577, 0.055401794612407684, -0.04163767397403717, 0.06279648095369339, -0.004321553744375706, -0.06458307802677155, 0.04710076004266739, 0.027388490736484528, -0.028406115248799324, -0.0031859995797276497, 0.01728656329214573, 0.03930680826306343, -0.042606621980667114, -0.03965207189321518, 0.050438474863767624, -0.05095212534070015, -0.009358619339764118, -0.005097959190607071, -0.042747560888528824, -0.09899874031543732, 0.046798769384622574, 0.06118430569767952, -0.029022959992289543, -0.11554227024316788, -0.011058848351240158, -0.036974892020225525, -0.08948592841625214, -0.014271756634116173, 0.013834885321557522, -0.01605868525803089, -0.04475671425461769, 0.03806497901678085, -0.05086902156472206, -0.06123126670718193, -0.08582713454961777, 0.018628671765327454, 0.10956262052059174, 0.03865630552172661, -0.005097296088933945, -0.024105655029416084, -0.012989535927772522, -0.07685093581676483, -0.00417094212025404, 0.089471735060215, -0.005915124900639057, 0.014249371364712715, -0.013326791115105152, 0.1283029317855835, -0.0087217316031456, 0.10300467163324356, 0.03298785537481308, -0.011241207830607891, 0.024034647271037102, 0.048094574362039566, 0.011020636186003685, -0.037912674248218536, -0.05348319187760353, 0.025995740666985512, 0.1147560179233551, 0.023856690153479576, 0.08506986498832703, 0.1052437573671341, 0.003146340372040868, -0.06395517289638519, 0.09612903743982315, -0.013588497415184975, 0.07226214557886124, 0.008729256689548492, -0.03723451867699623, -0.011913117952644825, 0.00031532489811070263, 0.007079592905938625, 0.03848397731781006, -0.09682920575141907, -0.014785494655370712, 0.002893038559705019, -0.06805280596017838, 0.0401400662958622, -0.022343454882502556, 0.08511822670698166, -0.13211962580680847, 0.03063001111149788, 0.0910293459892273, -1.2904515678258122e-08, -0.04676821827888489, -0.006705537438392639, 0.022972706705331802, -0.022980324923992157, -0.07330192625522614, -0.05493609607219696, 0.147051140666008, 0.07781931012868881, 0.032597970217466354, -0.04455342888832092, 0.011822628788650036, -0.0011622520396485925, -0.08087407797574997, -0.029209928587079048, -0.04869680851697922, 0.01635807752609253, -0.013975921086966991, 0.02993103303015232, -0.02186085842549801, 0.027337562292814255, 0.06173807755112648, -0.05552144721150398, 0.11173667758703232, -0.002850713673979044, 0.0067396159283816814, -0.014453276060521603, 0.03404010832309723, 0.06328174471855164, 0.09785991162061691, 0.016026383265852928, 0.02463620714843273, 0.010196371003985405, 0.03231675177812576, 0.03482783958315849, 0.012972479686141014, 0.06374970823526382, -0.12293172627687454, -0.01703498885035515, -0.028862323611974716, -0.036092162132263184, -0.0514722540974617, -0.11512449383735657, -0.012429235503077507, -0.08940501511096954, 0.06870079040527344, 0.026553628966212273, -0.03257280960679054, 0.046524085104465485, 0.00020684042829088867, 0.06025783717632294, -0.015267660841345787, 0.0010977181373164058, 0.005369286052882671, 0.03770275413990021, 0.023572636768221855, 0.0035807902459055185, -0.03384198620915413, -0.026205267757177353, 0.06975211203098297, 0.020543193444609642, -0.015171892009675503, 0.05312025547027588, 0.014551732689142227, 0.02318691834807396], \\"type\\": \\"float32\\", \\"shape\\": [384]}"^^<https://w3id.org/rdf-tensor/datatypes#NumericDataTensor>) AS ?dist) .\n} GROUP BY ?product ?vector ?dist\nORDER BY DESC(?dist)\nLIMIT 10\n', <QUERY_TYPE.INDEX: 'index'>: '\nPREFIX dt: <https://w3id.org/rdf-tensor/datatypes#>\nPREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#>\nPREFIX dtf: <https://w3id.org/rdf-tensor/functions#>\nPREFIX bsbmi: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>\nPREFIX bsbmv: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>\nPREFIX tensorIndex: <https://qlever.cs.uni-freiburg.de/tensorIndex/>\nSELECT DISTINCT ?product  ?vector ?dist\nWHERE {\nSERVICE tensorIndex: {\n       _:config tensorIndex:numNN 10 ;\n      tensorIndex:left ?query_vector ;\n      tensorIndex:bindDistance ?dist ;\n      tensorIndex:payload ?product ;\n      tensorIndex:searchK 1;\n      tensorIndex:algorithm tensorIndex:ivf ;\n      tensorIndex:experimentalRightCacheName "easy_index_bsbm" ;\n      tensorIndex:right ?vector .\n       {\n            {\n                SELECT DISTINCT ?product ?vector WHERE {\n                    ?product rdf:label_embedding ?vector .\n                    ?product bsbmv:productFeature ?feat .\n                } GROUP BY ?product ?vector\n            }\n        }\n    }\n    VALUES (?query_vector) { ("{\\"data\\": [0.001923849806189537, 0.059069667011499405, -0.06259278953075409, -0.008788925595581532, 0.08017760515213013, 0.0004897266626358032, 0.049011558294296265, -0.016156358644366264, -0.04537816718220711, 0.011929630301892757, -0.003551364177837968, -0.0034783161245286465, 0.023264417424798012, 0.02449001744389534, -0.023595571517944336, -0.073823943734169, 0.014226873405277729, -0.00022305997845251113, -0.03111756220459938, 0.07163400948047638, -0.04559392109513283, 0.044428009539842606, 0.0004388350062072277, -0.004044292028993368, 0.05173112079501152, 0.08436278998851776, -0.028667306527495384, -0.032494205981492996, 0.058949727565050125, -0.0051073553040623665, 0.09506019204854965, -0.029170090332627296, -0.07172352075576782, 0.036426812410354614, 0.01788988709449768, 0.07774496078491211, -0.01058284193277359, -0.02719942107796669, -0.014839782379567623, 0.004996407311409712, -0.05195301026105881, -0.01563340425491333, -0.0004883587826043367, 0.012572054751217365, -0.043422963470220566, -0.011021864600479603, -0.024199120700359344, -0.030226601287722588, 0.04542998597025871, -0.007276976015418768, 0.01397930271923542, 0.050883397459983826, -0.01848265342414379, 0.049168676137924194, -0.008279561065137386, 0.044504038989543915, 0.04745961353182793, 0.043078307062387466, -0.046442680060863495, 0.036845613270998, 0.10432934015989304, -0.015816830098628998, 0.10823524743318558, -0.028953377157449722, 0.04555060341954231, -0.030880587175488472, -0.051015835255384445, 0.05478580296039581, -0.0291702002286911, -0.005334345158189535, -0.06260965764522552, 0.034982938319444656, 0.026750046759843826, 0.04171916842460632, 0.03431631997227669, -0.07216819375753403, -0.00024255513562820852, -0.048893045634031296, 0.02389506623148918, 0.12748239934444427, -0.08703242987394333, 0.03412925824522972, 0.02240350842475891, 0.002564689377322793, -0.17344096302986145, 0.04103534668684006, -0.017823603004217148, -0.0076851267367601395, -0.09476081281900406, -0.07406330108642578, 0.08501428365707397, 0.04020910710096359, 0.08708695322275162, -0.026967616751790047, -0.060038503259420395, -0.003988019190728664, -0.02539210394024849, 0.022482113912701607, 0.060429759323596954, 0.037002742290496826, -0.0065333242528140545, 0.021862275898456573, 0.00022625424026045948, -0.033486779779195786, -0.07245824486017227, -0.1024286150932312, 0.049249906092882156, -0.009056593291461468, 0.007512359414249659, 0.0021412500645965338, -0.09075023233890533, 0.040666837245225906, -0.06107519939541817, -0.002982238307595253, -0.06842709332704544, 0.0025372530799359083, -0.01641230843961239, -0.043180201202631, 0.039085742086172104, -0.10427255183458328, 0.0473635196685791, -0.019185954704880714, 0.05296330899000168, 0.019953425973653793, 0.0329863503575325, 0.03303090110421181, 0.04857225716114044, 7.191068898027963e-35, -0.018325448036193848, -0.06909802556037903, 0.024108240380883217, 0.04407642409205437, 0.06294272840023041, 0.029094791039824486, 0.06375113874673843, 0.07381084561347961, 0.0368872731924057, 0.019980719313025475, -0.013145486824214458, -0.027676766738295555, -0.10194964706897736, -0.002321777166798711, -0.0032931924797594547, -0.02191285789012909, -0.09255401045084, 0.03210889920592308, 0.015278536826372147, -0.04234621301293373, 0.0064256093464791775, 0.04209345206618309, -0.019585780799388885, 0.03202011436223984, 0.037421416491270065, -0.018620574846863747, 0.019987355917692184, -0.013685979880392551, -0.03424428403377533, 0.012987463735044003, 0.04883616417646408, -0.0011513904901221395, -0.008845774456858635, 0.005870802327990532, -0.07762148231267929, -0.025999465957283974, -0.06829018890857697, 0.018836436793208122, -0.02234852872788906, -0.07037260383367538, 0.012542112730443478, 0.03438114747405052, 0.14274704456329346, 0.07548227161169052, 0.008455806411802769, -0.02049204707145691, 0.004560847766697407, -0.025547219440340996, -0.11879655718803406, 0.001291911699809134, -0.03331619128584862, 0.025502456352114677, -0.09485730528831482, 0.08408985286951065, -0.05816476047039032, -0.029875924810767174, -0.01281525194644928, -0.06466028094291687, 0.0453050322830677, 0.004283205606043339, 0.035003237426280975, 0.04375073313713074, 0.043108899146318436, -0.001907631172798574, 0.016851212829351425, -0.026979830116033554, 0.010974003002047539, 0.016453053802251816, 0.09936032444238663, 0.009172468446195126, 0.007693963125348091, -0.00969709176570177, 0.023047752678394318, -0.021144036203622818, 0.03724559023976326, -0.013058981858193874, -0.029100554063916206, 0.01229681633412838, -0.09894735366106033, -0.12643840909004211, 0.04589775577187538, -0.07361725717782974, 0.04434674605727196, 0.050329189747571945, -0.06559285521507263, -0.09371957182884216, 0.024369491264224052, -0.01520457398146391, -0.0038548363372683525, 0.027220020070672035, -0.031000541523098946, 0.015559685416519642, -0.006960012950003147, -0.041212767362594604, -0.08390278369188309, -4.97649344593706e-34, 0.05890499800443649, -0.06461971998214722, -0.07525855302810669, 0.058098528534173965, 0.06788986176252365, 0.019036881625652313, -0.007119014859199524, -0.043491482734680176, -0.017167028039693832, -0.04744131118059158, -0.04438185319304466, 0.0017611982766538858, 0.11509203165769577, 0.055401794612407684, -0.04163767397403717, 0.06279648095369339, -0.004321553744375706, -0.06458307802677155, 0.04710076004266739, 0.027388490736484528, -0.028406115248799324, -0.0031859995797276497, 0.01728656329214573, 0.03930680826306343, -0.042606621980667114, -0.03965207189321518, 0.050438474863767624, -0.05095212534070015, -0.009358619339764118, -0.005097959190607071, -0.042747560888528824, -0.09899874031543732, 0.046798769384622574, 0.06118430569767952, -0.029022959992289543, -0.11554227024316788, -0.011058848351240158, -0.036974892020225525, -0.08948592841625214, -0.014271756634116173, 0.013834885321557522, -0.01605868525803089, -0.04475671425461769, 0.03806497901678085, -0.05086902156472206, -0.06123126670718193, -0.08582713454961777, 0.018628671765327454, 0.10956262052059174, 0.03865630552172661, -0.005097296088933945, -0.024105655029416084, -0.012989535927772522, -0.07685093581676483, -0.00417094212025404, 0.089471735060215, -0.005915124900639057, 0.014249371364712715, -0.013326791115105152, 0.1283029317855835, -0.0087217316031456, 0.10300467163324356, 0.03298785537481308, -0.011241207830607891, 0.024034647271037102, 0.048094574362039566, 0.011020636186003685, -0.037912674248218536, -0.05348319187760353, 0.025995740666985512, 0.1147560179233551, 0.023856690153479576, 0.08506986498832703, 0.1052437573671341, 0.003146340372040868, -0.06395517289638519, 0.09612903743982315, -0.013588497415184975, 0.07226214557886124, 0.008729256689548492, -0.03723451867699623, -0.011913117952644825, 0.00031532489811070263, 0.007079592905938625, 0.03848397731781006, -0.09682920575141907, -0.014785494655370712, 0.002893038559705019, -0.06805280596017838, 0.0401400662958622, -0.022343454882502556, 0.08511822670698166, -0.13211962580680847, 0.03063001111149788, 0.0910293459892273, -1.2904515678258122e-08, -0.04676821827888489, -0.006705537438392639, 0.022972706705331802, -0.022980324923992157, -0.07330192625522614, -0.05493609607219696, 0.147051140666008, 0.07781931012868881, 0.032597970217466354, -0.04455342888832092, 0.011822628788650036, -0.0011622520396485925, -0.08087407797574997, -0.029209928587079048, -0.04869680851697922, 0.01635807752609253, -0.013975921086966991, 0.02993103303015232, -0.02186085842549801, 0.027337562292814255, 0.06173807755112648, -0.05552144721150398, 0.11173667758703232, -0.002850713673979044, 0.0067396159283816814, -0.014453276060521603, 0.03404010832309723, 0.06328174471855164, 0.09785991162061691, 0.016026383265852928, 0.02463620714843273, 0.010196371003985405, 0.03231675177812576, 0.03482783958315849, 0.012972479686141014, 0.06374970823526382, -0.12293172627687454, -0.01703498885035515, -0.028862323611974716, -0.036092162132263184, -0.0514722540974617, -0.11512449383735657, -0.012429235503077507, -0.08940501511096954, 0.06870079040527344, 0.026553628966212273, -0.03257280960679054, 0.046524085104465485, 0.00020684042829088867, 0.06025783717632294, -0.015267660841345787, 0.0010977181373164058, 0.005369286052882671, 0.03770275413990021, 0.023572636768221855, 0.0035807902459055185, -0.03384198620915413, -0.026205267757177353, 0.06975211203098297, 0.020543193444609642, -0.015171892009675503, 0.05312025547027588, 0.014551732689142227, 0.02318691834807396], \\"type\\": \\"float32\\", \\"shape\\": [384]}"^^<https://w3id.org/rdf-tensor/datatypes#NumericDataTensor>) }\n} ORDER BY DESC(?dist)\nLIMIT 10\n', <QUERY_TYPE.TWO_STAGE: 'two_stage'>: '\n            PREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#>\n            PREFIX dtf: <https://w3id.org/rdf-tensor/functions#>\n            PREFIX bsbmi: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>\n            SELECT DISTINCT ?product  ?vector ?dist\n            WHERE {\n                ?productA bsbmv:productFeature ?feat .\n                ?product rdf:label_embedding ?vector .\n                VALUES (?some_emb) { ("{\\"data\\": [0.001923849806189537, 0.059069667011499405, -0.06259278953075409, -0.008788925595581532, 0.08017760515213013, 0.0004897266626358032, 0.049011558294296265, -0.016156358644366264, -0.04537816718220711, 0.011929630301892757, -0.003551364177837968, -0.0034783161245286465, 0.023264417424798012, 0.02449001744389534, -0.023595571517944336, -0.073823943734169, 0.014226873405277729, -0.00022305997845251113, -0.03111756220459938, 0.07163400948047638, -0.04559392109513283, 0.044428009539842606, 0.0004388350062072277, -0.004044292028993368,

In [70]:
print(possible_queries[QUERY_DIFFICULTY.EASY][QUERY_TYPE.EMBEDDED])

PREFIX dt: <https://w3id.org/rdf-tensor/datatypes#>
PREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dtf: <https://w3id.org/rdf-tensor/functions#>
PREFIX bsbmi: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>
PREFIX bsbmv: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
SELECT DISTINCT ?product  ?vector ?dist
WHERE {
?product rdf:label_embedding ?vector .
?product bsbmv:productFeature ?feat .
BIND(dtf:cosineSimilarity(?vector, "{\"data\": [0.001923849806189537, 0.059069667011499405, -0.06259278953075409, -0.008788925595581532, 0.08017760515213013, 0.0004897266626358032, 0.049011558294296265, -0.016156358644366264, -0.04537816718220711, 0.011929630301892757, -0.003551364177837968, -0.0034783161245286465, 0.023264417424798012, 0.02449001744389534, -0.023595571517944336, -0.073823943734169, 0.014226873405277729, -0.00022305997845251113, -0.03111756220459938, 0.07163400948047638, -0.04559392109513283, 0.044428009539842606, 0.0004388350062072277, -0.004044292028993368, 0.05173112079501152, 0.08436278998851776, -0.028667306527495384, -0.032494205981492996, 0.058949727565050125, -0.0051073553040623665, 0.09506019204854965, -0.029170090332627296, -0.07172352075576782, 0.036426812410354614, 0.01788988709449768, 0.07774496078491211, -0.01058284193277359, -0.02719942107796669, -0.014839782379567623, 0.004996407311409712, -0.05195301026105881, -0.01563340425491333, -0.0004883587826043367, 0.012572054751217365, -0.043422963470220566, -0.011021864600479603, -0.024199120700359344, -0.030226601287722588, 0.04542998597025871, -0.007276976015418768, 0.01397930271923542, 0.050883397459983826, -0.01848265342414379, 0.049168676137924194, -0.008279561065137386, 0.044504038989543915, 0.04745961353182793, 0.043078307062387466, -0.046442680060863495, 0.036845613270998, 0.10432934015989304, -0.015816830098628998, 0.10823524743318558, -0.028953377157449722, 0.04555060341954231, -0.030880587175488472, -0.051015835255384445, 0.05478580296039581, -0.0291702002286911, -0.005334345158189535, -0.06260965764522552, 0.034982938319444656, 0.026750046759843826, 0.04171916842460632, 0.03431631997227669, -0.07216819375753403, -0.00024255513562820852, -0.048893045634031296, 0.02389506623148918, 0.12748239934444427, -0.08703242987394333, 0.03412925824522972, 0.02240350842475891, 0.002564689377322793, -0.17344096302986145, 0.04103534668684006, -0.017823603004217148, -0.0076851267367601395, -0.09476081281900406, -0.07406330108642578, 0.08501428365707397, 0.04020910710096359, 0.08708695322275162, -0.026967616751790047, -0.060038503259420395, -0.003988019190728664, -0.02539210394024849, 0.022482113912701607, 0.060429759323596954, 0.037002742290496826, -0.0065333242528140545, 0.021862275898456573, 0.00022625424026045948, -0.033486779779195786, -0.07245824486017227, -0.1024286150932312, 0.049249906092882156, -0.009056593291461468, 0.007512359414249659, 0.0021412500645965338, -0.09075023233890533, 0.040666837245225906, -0.06107519939541817, -0.002982238307595253, -0.06842709332704544, 0.0025372530799359083, -0.01641230843961239, -0.043180201202631, 0.039085742086172104, -0.10427255183458328, 0.0473635196685791, -0.019185954704880714, 0.05296330899000168, 0.019953425973653793, 0.0329863503575325, 0.03303090110421181, 0.04857225716114044, 7.191068898027963e-35, -0.018325448036193848, -0.06909802556037903, 0.024108240380883217, 0.04407642409205437, 0.06294272840023041, 0.029094791039824486, 0.06375113874673843, 0.07381084561347961, 0.0368872731924057, 0.019980719313025475, -0.013145486824214458, -0.027676766738295555, -0.10194964706897736, -0.002321777166798711, -0.0032931924797594547, -0.02191285789012909, -0.09255401045084, 0.03210889920592308, 0.015278536826372147, -0.04234621301293373, 0.0064256093464791775, 0.04209345206618309, -0.019585780799388885, 0.03202011436223984, 0.037421416491270065, -0.018620574846863747, 0.019987355917692184, -0.013685979880392551, -0.03424428403377533, 0.012987463735044003, 0.04883616417646408, -0.0011513904901221395, -0.008845774456858635, 0.005870802327990532, -0.07762148231267929, -0.025999465957283974, -0.06829018890857697, 0.018836436793208122, -0.02234852872788906, -0.07037260383367538, 0.012542112730443478, 0.03438114747405052, 0.14274704456329346, 0.07548227161169052, 0.008455806411802769, -0.02049204707145691, 0.004560847766697407, -0.025547219440340996, -0.11879655718803406, 0.001291911699809134, -0.03331619128584862, 0.025502456352114677, -0.09485730528831482, 0.08408985286951065, -0.05816476047039032, -0.029875924810767174, -0.01281525194644928, -0.06466028094291687, 0.0453050322830677, 0.004283205606043339, 0.035003237426280975, 0.04375073313713074, 0.043108899146318436, -0.001907631172798574, 0.016851212829351425, -0.026979830116033554, 0.010974003002047539, 0.016453053802251816, 0.09936032444238663, 0.009172468446195126, 0.007693963125348091, -0.00969709176570177, 0.023047752678394318, -0.021144036203622818, 0.03724559023976326, -0.013058981858193874, -0.029100554063916206, 0.01229681633412838, -0.09894735366106033, -0.12643840909004211, 0.04589775577187538, -0.07361725717782974, 0.04434674605727196, 0.050329189747571945, -0.06559285521507263, -0.09371957182884216, 0.024369491264224052, -0.01520457398146391, -0.0038548363372683525, 0.027220020070672035, -0.031000541523098946, 0.015559685416519642, -0.006960012950003147, -0.041212767362594604, -0.08390278369188309, -4.97649344593706e-34, 0.05890499800443649, -0.06461971998214722, -0.07525855302810669, 0.058098528534173965, 0.06788986176252365, 0.019036881625652313, -0.007119014859199524, -0.043491482734680176, -0.017167028039693832, -0.04744131118059158, -0.04438185319304466, 0.0017611982766538858, 0.11509203165769577, 0.055401794612407684, -0.04163767397403717, 0.06279648095369339, -0.004321553744375706, -0.06458307802677155, 0.04710076004266739, 0.027388490736484528, -0.028406115248799324, -0.0031859995797276497, 0.01728656329214573, 0.03930680826306343, -0.042606621980667114, -0.03965207189321518, 0.050438474863767624, -0.05095212534070015, -0.009358619339764118, -0.005097959190607071, -0.042747560888528824, -0.09899874031543732, 0.046798769384622574, 0.06118430569767952, -0.029022959992289543, -0.11554227024316788, -0.011058848351240158, -0.036974892020225525, -0.08948592841625214, -0.014271756634116173, 0.013834885321557522, -0.01605868525803089, -0.04475671425461769, 0.03806497901678085, -0.05086902156472206, -0.06123126670718193, -0.08582713454961777, 0.018628671765327454, 0.10956262052059174, 0.03865630552172661, -0.005097296088933945, -0.024105655029416084, -0.012989535927772522, -0.07685093581676483, -0.00417094212025404, 0.089471735060215, -0.005915124900639057, 0.014249371364712715, -0.013326791115105152, 0.1283029317855835, -0.0087217316031456, 0.10300467163324356, 0.03298785537481308, -0.011241207830607891, 0.024034647271037102, 0.048094574362039566, 0.011020636186003685, -0.037912674248218536, -0.05348319187760353, 0.025995740666985512, 0.1147560179233551, 0.023856690153479576, 0.08506986498832703, 0.1052437573671341, 0.003146340372040868, -0.06395517289638519, 0.09612903743982315, -0.013588497415184975, 0.07226214557886124, 0.008729256689548492, -0.03723451867699623, -0.011913117952644825, 0.00031532489811070263, 0.007079592905938625, 0.03848397731781006, -0.09682920575141907, -0.014785494655370712, 0.002893038559705019, -0.06805280596017838, 0.0401400662958622, -0.022343454882502556, 0.08511822670698166, -0.13211962580680847, 0.03063001111149788, 0.0910293459892273, -1.2904515678258122e-08, -0.04676821827888489, -0.006705537438392639, 0.022972706705331802, -0.022980324923992157, -0.07330192625522614, -0.05493609607219696, 0.147051140666008, 0.07781931012868881, 0.032597970217466354, -0.04455342888832092, 0.011822628788650036, -0.0011622520396485925, -0.08087407797574997, -0.029209928587079048, -0.04869680851697922, 0.01635807752609253, -0.013975921086966991, 0.02993103303015232, -0.02186085842549801, 0.027337562292814255, 0.06173807755112648, -0.05552144721150398, 0.11173667758703232, -0.002850713673979044, 0.0067396159283816814, -0.014453276060521603, 0.03404010832309723, 0.06328174471855164, 0.09785991162061691, 0.016026383265852928, 0.02463620714843273, 0.010196371003985405, 0.03231675177812576, 0.03482783958315849, 0.012972479686141014, 0.06374970823526382, -0.12293172627687454, -0.01703498885035515, -0.028862323611974716, -0.036092162132263184, -0.0514722540974617, -0.11512449383735657, -0.012429235503077507, -0.08940501511096954, 0.06870079040527344, 0.026553628966212273, -0.03257280960679054, 0.046524085104465485, 0.00020684042829088867, 0.06025783717632294, -0.015267660841345787, 0.0010977181373164058, 0.005369286052882671, 0.03770275413990021, 0.023572636768221855, 0.0035807902459055185, -0.03384198620915413, -0.026205267757177353, 0.06975211203098297, 0.020543193444609642, -0.015171892009675503, 0.05312025547027588, 0.014551732689142227, 0.02318691834807396], \"type\": \"float32\", \"shape\": [384]}"^^<https://w3id.org/rdf-tensor/datatypes#NumericDataTensor>) AS ?dist) .
} GROUP BY ?product ?vector ?dist
ORDER BY DESC(?dist)
LIMIT 10

In [71]:
import os
os.getcwd()

'/nfsd/gracedata2/kantz/Dense-Vector-KG/benchmarks'

In [105]:
import time


with db_fuseki as db:
    timings = []
    for _ in tqdm.tqdm(range(10)):
        start_time = time.time()
        noised_tensor = test_tensor.to_numpy() + np.random.normal(scale=0.01, size=test_tensor.to_numpy().shape)
        noised_tensor = DataTensor.from_numpy(noised_tensor)

        results = db.query_auto(
            noised_tensor,
            query_difficulty=QUERY_DIFFICULTY.EASY,
            query_type=QUERY_TYPE.EMBEDDED,
        )
        elapsed_time = time.time() - start_time
        timings.append(elapsed_time*1e9)  # convert to nanoseconds
print("Median elapsed time:", np.median(timings))
results

2026-08-19 10:50:37,370 - WARNING - Killing any existing process using port 29054 before starting the server

2026-08-19 10:50:37,443 - ERROR - Command failed with return code 1
2026-08-19 10:50:37,443 - INFO - Loading dataset into Fuseki server from data/bsbm_3/dataset.nt
2026-08-19 10:50:37,444 - WARNING - DB directory scratch/bsbm/bsbm_3/db/test_fuseki already exists, removing locks if any
2026-08-19 10:50:37,445 - INFO - Stopping server!
2026-08-19 10:50:37,508 - ERROR - Command failed with return code 1
2026-08-19 10:50:37,508 - INFO - Starting Fuseki server port 29054
2026-08-19 10:50:37,509 - ERROR - TENSOR_CP environment variable is not set
2026-08-19 10:50:37,510 - INFO - Using default TENSOR_CP=/nfsd/gracedata2/kantz/Dense-Vector-KG/jena-datatensor/jena-datatensor/target/*
2026-08-19 10:50:37,510 - ERROR - FUSEKI_HOME environment variable is not set
2026-08-19 10:50:37,511 - INFO - Using default FUSEKI_HOME=/home/kantz/apache-jena-fuseki-5.2.0
2026-08-19 10:50:37,511 - INFO - Using FUSEKI_HOME=/home/kantz/apache-jena-fuseki-5.2.0 and TENSOR_CP=/nfsd/gracedata2/kantz/Dense-Vector-KG/jena-datatensor/jena-datatensor/target/*
2026-08-19 10:50:37,513 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:29054/test_fuseki/sparql)
2026-08-19 10:50:38,514 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:29054/test_fuseki/sparql)
2026-08-19 10:50:39,712 - INFO - Server is up and responding to queries
100%|██████████| 10/10 [00:20<00:00,  2.05s/it]
2026-08-19 10:51:00,248 - INFO - Stopping server!

 382618Median elapsed time: 1823994874.9542236

29054/tcp:

,product,vector,dist
0,bsbmi:dataFromProducer14/Product668,"{""data"": [0.06415609270334244, 0.0112423812970...",0.3215971863272915
1,bsbmi:dataFromProducer19/Product897,"{""data"": [0.02605944126844406, 0.0248944889754...",0.2904596318614194
2,bsbmi:dataFromProducer14/Product665,"{""data"": [-0.005199954379349947, 0.05737551674...",0.2699475543209706
3,bsbmi:dataFromProducer5/Product187,"{""data"": [0.08207504451274872, 0.0040897363796...",0.26294023744154954
4,bsbmi:dataFromProducer14/Product648,"{""data"": [-0.06801604479551315, 0.064525954425...",0.24247276754477667
5,bsbmi:dataFromProducer16/Product776,"{""data"": [-0.05298737809062004, 0.066510111093...",0.2314222704756462
6,bsbmi:dataFromProducer9/Product383,"{""data"": [-0.020090781152248383, -0.0054141189...",0.22833389495934472
7,bsbmi:dataFromProducer9/Product439,"{""data"": [-0.1157810166478157, 0.1029479503631...",0.222577668105088
8,bsbmi:dataFromProducer13/Product610,"{""data"": [-0.04075666889548302, 0.088839158415...",0.2200760708877457
9,bsbmi:dataFromProducer21/Product981,"{""data"": [0.07412167638540268, -0.010792593471...",0.21233305057905177

In [106]:
db_no_tensor_idx.server_log_file

PosixPath('scratch/bsbm/bsbm_3/db/test-no-tidx/test-no-tidx_run.log')

In [115]:
subtimings = db_fuseki.get_timings_per_query()
subtiming_records = []
for i, query_timings in enumerate(subtimings):
    for key, ts in query_timings.items():
        for t in ts:
            subtiming_records.append(
                {"query_id": i - 1, "timing_key": key, "timings": t}
            )
df_subtimings = pd.DataFrame(subtiming_records)
df_timings = pd.DataFrame(
    [
        {"query_id": i, "timing_key": "totalExecution", "timings": t}
        for i, t in enumerate(timings)
    ]
)
full_timings = pd.concat([df_subtimings, df_timings], ignore_index=True)

In [116]:
len(subtimings)

12

In [113]:
full_timings["timing_key"].describe()

count                 10
unique                 1
top       totalExecution
freq                  10
Name: timing_key, dtype: object

In [117]:
full_timings.groupby(["query_id", "timing_key"])[["timings"]].sum().reset_index().sort_values(by=["query_id", "timing_key"])

    query_id              timing_key       timings
0          0          totalExecution  4.219892e+09
1          1  tensorCosineSimilarity  1.641806e+09
2          1        tensorFromString  1.451797e+09
3          1          totalExecution  2.039872e+09
4          2  tensorCosineSimilarity  1.646995e+09
5          2        tensorFromString  1.270832e+06
6          2          totalExecution  1.575237e+09
7          3  tensorCosineSimilarity  1.113496e+09
8          3        tensorFromString  1.316819e+06
9          3          totalExecution  1.990099e+09
10         4  tensorCosineSimilarity  1.619883e+09
11         4        tensorFromString  9.179790e+05
12         4          totalExecution  1.670265e+09
13         5  tensorCosineSimilarity  1.153635e+09
14         5        tensorFromString  1.003207e+06
15         5          totalExecution  1.844473e+09
16         6  tensorCosineSimilarity  1.458846e+09
17         6        tensorFromString  2.529159e+06
18         6          totalExecution  1.616630e+09
19         7  tensorCosineSimilarity  1.154191e+09
20         7        tensorFromString  9.946880e+05
21         7          totalExecution  1.803517e+09
22         8  tensorCosineSimilarity  1.485550e+09
23         8        tensorFromString  9.481000e+05
24         8          totalExecution  1.755904e+09
25         9  tensorCosineSimilarity  1.387020e+09
26         9        tensorFromString  1.028800e+06
27         9          totalExecution  2.008541e+09
28        10  tensorCosineSimilarity  1.607051e+09
29        10        tensorFromString  1.054850e+06

In [128]:
repetitions = 128


def run_queries(
    db: ExecutableDB, q_type: QUERY_TYPE, test_tensor: DataTensor, repetitions=128
):
    query_timings_ns = []
    available_qs = db.get_available_query_types()
    if q_type not in available_qs:
        print(f"Query type {q_type} not available for database {db.name}. Skipping.")
        return query_timings_ns
    g = tqdm.tqdm(range(repetitions), total=repetitions, unit="query", leave=False)
    g.set_description(f"Running queries on {db.name}/{q_type}: ")
    for _ in g:
        start_time = time.time()
        noised_tensor = test_tensor.to_numpy() + np.random.normal(
            scale=0.01, size=test_tensor.to_numpy().shape
        )
        noised_tensor = DataTensor.from_numpy(noised_tensor)

        results = db.query_auto(
            noised_tensor,
            query_difficulty=QUERY_DIFFICULTY.EASY,
            query_type=q_type,
        )
        elapsed_time = time.time() - start_time
        query_timings_ns.append(elapsed_time * 1e9)
    return query_timings_ns


all_timings = None
for q_type in [QUERY_TYPE.EMBEDDED, QUERY_TYPE.INDEX]:
    for db in dbs:
        db.clear_log()
        with db as db_instance:
            query_timings_ns = run_queries(
                db_instance, q_type, test_tensor, repetitions=8
            )
            if len(query_timings_ns) == 0:
                continue
            subtimings = db_instance.get_timings_per_query()
            subtiming_records = []
            for i, qt in enumerate(subtimings):
                for key, ts in qt.items():
                    for t in ts:
                        subtiming_records.append(
                            {
                                "query_id": i - 1,
                                "timing_key": key,
                                "timings": t,
                                "engine": db_instance.name,
                                "query_type": q_type.name.lower(),
                            }
                        )
            df_subtimings = pd.DataFrame(subtiming_records)
            df_timings = pd.DataFrame(
                [
                    {
                        "query_id": i,
                        "timing_key": "totalExecution",
                        "timings": t,
                        "engine": db_instance.name,
                        "query_type": q_type.name.lower(),
                    }
                    for i, t in enumerate(query_timings_ns)
                ]
            )
            full_timings = pd.concat([df_subtimings, df_timings], ignore_index=True)

            full_timings_sums = (
                full_timings.groupby(["query_id", "timing_key", "engine", "query_type"])[["timings"]]
                .count()
                .reset_index()
                .sort_values(by=["query_id", "timing_key"])
            )
            all_timings = (
                pd.concat([all_timings, full_timings_sums], ignore_index=True)
                if all_timings is not None
                else full_timings_sums
            )

2026-08-19 10:59:52,636 - INFO - Logging QLever setup to scratch/bsbm/bsbm_3/db/test-with-tidx/test-with-tidx_run.log
2026-08-19 10:59:52,637 - INFO - Loading dataset into QLever server from data/bsbm_3/dataset.nt
2026-08-19 10:59:52,637 - WARNING - DB directory scratch/bsbm/bsbm_3/db/test-with-tidx already exists!
2026-08-19 10:59:52,638 - INFO - Stopping server!
2026-08-19 10:59:52,652 - ERROR - Command failed with return code 1
2026-08-19 10:59:52,653 - INFO - Starting QLever server on port 26052
2026-08-19 10:59:52,653 - INFO - Running command: qlever-server -i test-with-tidx --port 26052 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-08-19 10:59:52,655 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:26052/test-with-tidx/sparql)

2026-08-19 10:59:53,666 - INFO - Server is up and responding to queries
2026-08-19 11:00:00,249 - INFO - Stopping server!
2026-08-19 11:00:00,323 - ERROR - Command failed with return code 1
2026-08-19 11:00:00,324 - INFO - Logging QLever setup to scratch/bsbm/bsbm_3/db/test-no-tidx/test-no-tidx_run.log
2026-08-19 11:00:00,324 - INFO - Loading dataset into QLever server from data/bsbm_3/dataset.nt
2026-08-19 11:00:00,325 - WARNING - DB directory scratch/bsbm/bsbm_3/db/test-no-tidx already exists!
2026-08-19 11:00:00,326 - INFO - Stopping server!
2026-08-19 11:00:00,338 - ERROR - Command failed with return code 1
2026-08-19 11:00:00,338 - INFO - Starting QLever server on port 26053
2026-08-19 11:00:00,339 - INFO - Running command: qlever-server -i test-no-tidx --port 26053 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-08-19 11:00:00,341 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:26053/test-no-tidx/sparql)
2026-08-19 11:00:01,352 - INFO - Server is up and responding to queries
2026-08-19 11:00:13,494 - INFO - Stopping server!
2026-08-19 11:00:13,563 - ERROR - Command failed with return code 1
2026-08-19 11:00:13,564 - WARNING - Killing any existing process using port 29054 before starting the server
2026-08-19 11:00:13,576 - ERROR - Command failed with return code 1
2026-08-19 11:00:13,576 - INFO - Loading dataset into Fuseki server from data/bsbm_3/dataset.nt
2026-08-19 11:00:13,577 - WARNING - DB directory scratch/bsbm/bsbm_3/db/test_fuseki already exists, removing locks if any
2026-08-19 11:00:13,578 - INFO - Stopping server!
2026-08-19 11:00:13,589 - ERROR - Command failed with return code 1
2026-08-19 11:00:13,590 - INFO - Starting Fuseki server port 29054
2026-08-19 11:00:13,591 - ERROR - TENSOR_CP environment variable is not set
2026-08-19 11:00:13,591 - INFO - Using default TENSOR_CP=/nfsd/gracedata2/kantz/Dense-Vector-KG/jena-datatensor/jena-datatensor/target/*
2026-08-19 11:00:13,592 - ERROR - FUSEKI_HOME environment variable is not set
2026-08-19 11:00:13,592 - INFO - Using default FUSEKI_HOME=/home/kantz/apache-jena-fuseki-5.2.0
2026-08-19 11:00:13,592 - INFO - Using FUSEKI_HOME=/home/kantz/apache-jena-fuseki-5.2.0 and TENSOR_CP=/nfsd/gracedata2/kantz/Dense-Vector-KG/jena-datatensor/jena-datatensor/target/*
2026-08-19 11:00:13,595 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:29054/test_fuseki/sparql)
2026-08-19 11:00:14,596 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:29054/test_fuseki/sparql)
2026-08-19 11:00:15,784 - INFO - Server is up and responding to queries
2026-08-19 11:00:33,937 - INFO - Stopping server!
29054/tcp:
2026-08-19 11:00:34,019 - INFO - Logging QLever setup to scratch/bsbm/bsbm_3/db/test-with-tidx/test-with-tidx_run.log
2026-08-19 11:00:34,020 - INFO - Loading dataset into QLever server from data/bsbm_3/dataset.nt
2026-08-19 11:00:34,021 - WARNING - DB directory scratch/bsbm/bsbm_3/db/test-with-tidx already exists!
2026-08-19 11:00:34,021 - INFO - Stopping server!
2026-08-19 11:00:34,090 - ERROR - Command failed with return code 1
2026-08-19 11:00:34,091 - INFO - Starting QLever server on port 26052
2026-08-19 11:00:34,091 - INFO - Running command: qlever-server -i test-with-tidx --port 26052 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-08-19 11:00:34,093 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:26052/test-with-tidx/sparql)

 397096

2026-08-19 11:00:35,104 - INFO - Server is up and responding to queries
2026-08-19 11:00:35,480 - INFO - Stopping server!
2026-08-19 11:00:35,548 - ERROR - Command failed with return code 1
2026-08-19 11:00:35,577 - INFO - Logging QLever setup to scratch/bsbm/bsbm_3/db/test-no-tidx/test-no-tidx_run.log
2026-08-19 11:00:35,577 - INFO - Loading dataset into QLever server from data/bsbm_3/dataset.nt
2026-08-19 11:00:35,578 - WARNING - DB directory scratch/bsbm/bsbm_3/db/test-no-tidx already exists!
2026-08-19 11:00:35,578 - INFO - Stopping server!
2026-08-19 11:00:35,643 - ERROR - Command failed with return code 1
2026-08-19 11:00:35,644 - INFO - Starting QLever server on port 26053
2026-08-19 11:00:35,644 - INFO - Running command: qlever-server -i test-no-tidx --port 26053 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-08-19 11:00:35,646 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:26053/test-no-tidx/sparql)
2026-08-19 11:00:36,657 - INFO - Server is up and responding to queries
2026-08-19 11:00:37,047 - INFO - Stopping server!
2026-08-19 11:00:37,116 - ERROR - Command failed with return code 1
2026-08-19 11:00:37,123 - WARNING - Killing any existing process using port 29054 before starting the server
2026-08-19 11:00:37,188 - ERROR - Command failed with return code 1
2026-08-19 11:00:37,189 - INFO - Loading dataset into Fuseki server from data/bsbm_3/dataset.nt
2026-08-19 11:00:37,190 - WARNING - DB directory scratch/bsbm/bsbm_3/db/test_fuseki already exists, removing locks if any
2026-08-19 11:00:37,190 - INFO - Stopping server!
2026-08-19 11:00:37,255 - ERROR - Command failed with return code 1
2026-08-19 11:00:37,256 - INFO - Starting Fuseki server port 29054
2026-08-19 11:00:37,256 - ERROR - TENSOR_CP environment variable is not set
2026-08-19 11:00:37,257 - INFO - Using default TENSOR_CP=/nfsd/gracedata2/kantz/Dense-Vector-KG/jena-datatensor/jena-datatensor/target/*
2026-08-19 11:00:37,257 - ERROR - FUSEKI_HOME environment variable is not set
2026-08-19 11:00:37,257 - INFO - Using default FUSEKI_HOME=/home/kantz/apache-jena-fuseki-5.2.0
2026-08-19 11:00:37,258 - INFO - Using FUSEKI_HOME=/home/kantz/apache-jena-fuseki-5.2.0 and TENSOR_CP=/nfsd/gracedata2/kantz/Dense-Vector-KG/jena-datatensor/jena-datatensor/target/*
2026-08-19 11:00:37,260 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:29054/test_fuseki/sparql)
2026-08-19 11:00:38,261 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:29054/test_fuseki/sparql)
2026-08-19 11:00:39,428 - INFO - Server is up and responding to queries
2026-08-19 11:00:39,429 - INFO - Stopping server!

Query type QUERY_TYPE.INDEX not available for database Fuseki + RDFTensor. Skipping.
 398017

29054/tcp:

In [125]:
from utils.format import map_df_readable

all_timings.to_csv("scratch/sub_bsbm_timings.csv", index=False)
all_timings = map_df_readable(all_timings)

In [138]:
all_timings["engine"].unique()

<ArrowStringArray>
['QLever', 'QLever (no Tensor Vocabulary)', 'Fuseki + RDFTensor']
Length: 3, dtype: str

In [144]:
all_timings[
    (all_timings["engine"] == "Fuseki + RDFTensor") & (all_timings["query_type"] == "embedded")
]

     query_id              timing_key              engine query_type  timings
98          0  tensorCosineSimilarity  Fuseki + RDFTensor   embedded    20548
99          0        tensorFromString  Fuseki + RDFTensor   embedded     1000
100         0          totalExecution  Fuseki + RDFTensor   embedded        1
101         1  tensorCosineSimilarity  Fuseki + RDFTensor   embedded    20548
102         1        tensorFromString  Fuseki + RDFTensor   embedded        1
103         1          totalExecution  Fuseki + RDFTensor   embedded        1
104         2  tensorCosineSimilarity  Fuseki + RDFTensor   embedded    20548
105         2        tensorFromString  Fuseki + RDFTensor   embedded        1
106         2          totalExecution  Fuseki + RDFTensor   embedded        1
107         3  tensorCosineSimilarity  Fuseki + RDFTensor   embedded    20548
108         3        tensorFromString  Fuseki + RDFTensor   embedded        1
109         3          totalExecution  Fuseki + RDFTensor   embedded        1
110         4  tensorCosineSimilarity  Fuseki + RDFTensor   embedded    20548
111         4        tensorFromString  Fuseki + RDFTensor   embedded        1
112         4          totalExecution  Fuseki + RDFTensor   embedded        1
113         5  tensorCosineSimilarity  Fuseki + RDFTensor   embedded    20548
114         5        tensorFromString  Fuseki + RDFTensor   embedded        1
115         5          totalExecution  Fuseki + RDFTensor   embedded        1
116         6  tensorCosineSimilarity  Fuseki + RDFTensor   embedded    20548
117         6        tensorFromString  Fuseki + RDFTensor   embedded        1
118         6          totalExecution  Fuseki + RDFTensor   embedded        1
119         7  tensorCosineSimilarity  Fuseki + RDFTensor   embedded    20548
120         7        tensorFromString  Fuseki + RDFTensor   embedded        1
121         7          totalExecution  Fuseki + RDFTensor   embedded        1

In [142]:
all_timings[
    (all_timings["engine"] == "QLever (no Tensor Vocabulary)") & (all_timings["query_type"] == "embedded")
]

,query_id,timing_key,engine,query_type,timings
57,-1,processQueryAndSendResult,QLever (no Tensor Vocabulary),embedded,1
58,0,processQueryAndSendResult,QLever (no Tensor Vocabulary),embedded,1
59,0,readWordFromDisk,QLever (no Tensor Vocabulary),embedded,20663
60,0,tensorCosineSimilarity,QLever (no Tensor Vocabulary),embedded,20548
61,0,tensorFromString,QLever (no Tensor Vocabulary),embedded,20551
62,0,totalExecution,QLever (no Tensor Vocabulary),embedded,1
63,1,processQueryAndSendResult,QLever (no Tensor Vocabulary),embedded,1
64,1,readWordFromDisk,QLever (no Tensor Vocabulary),embedded,20663
65,1,tensorCosineSimilarity,QLever (no Tensor Vocabulary),embedded,20548
66,1,tensorFromString,QLever (no Tensor Vocabulary),embedded,20551
67,1,totalExecution,QLever (no Tensor Vocabulary),embedded,1
68,2,processQueryAndSendResult,QLever (no Tensor Vocabulary),embedded,1
69,2,readWordFromDisk,QLever (no Tensor Vocabulary),embedded,20662
70,2,tensorCosineSimilarity,QLever (no Tensor Vocabulary),embedded,20548
71,2,tensorFromString,QLever (no Tensor Vocabulary),embedded,20551
72,2,totalExecution,QLever (no Tensor Vocabulary),embedded,1
73,3,processQueryAndSendResult,QLever (no Tensor Vocabulary),embedded,1
74,3,readWordFromDisk,QLever (no Tensor Vocabulary),embedded,20663
75,3,tensorCosineSimilarity,QLever (no Tensor Vocabulary),embedded,20548
76,3,tensorFromString,QLever (no Tensor Vocabulary),embedded,20551
77,3,totalExecution,QLever (no Tensor Vocabulary),embedded,1
78,4,processQueryAndSendResult,QLever (no Tensor Vocabulary),embedded,1
79,4,readWordFromDisk,QLever (no Tensor Vocabulary),embedded,20663
80,4,tensorCosineSimilarity,QLever (no Tensor Vocabulary),embedded,20548
81,4,tensorFromString,QLever (no Tensor Vocabulary),embedded,20551
82,4,totalExecution,QLever (no Tensor Vocabulary),embedded,1
83,5,processQueryAndSendResult,QLever (no Tensor Vocabulary),embedded,1
84,5,readWordFromDisk,QLever (no Tensor Vocabulary),embedded,20663
85,5,tensorCosineSimilarity,QLever (no Tensor Vocabulary),embedded,20548
86,5,tensorFromString,QLever (no Tensor Vocabulary),embedded,20551
87,5,totalExecution,QLever (no Tensor Vocabulary),embedded,1
88,6,processQueryAndSendResult,QLever (no Tensor Vocabulary),embedded,1
89,6,readWordFromDisk,QLever (no Tensor Vocabulary),embedded,20663
90,6,tensorCosineSimilarity,QLever (no Tensor Vocabulary),embedded,20548
91,6,tensorFromString,QLever (no Tensor Vocabulary),embedded,20551
92,6,totalExecution,QLever (no Tensor Vocabulary),embedded,1
93,7,processQueryAndSendResult,QLever (no Tensor Vocabulary),embedded,1
94,7,readWordFromDisk,QLever (no Tensor Vocabulary),embedded,20663
95,7,tensorCosineSimilarity,QLever (no Tensor Vocabulary),embedded,20548
96,7,tensorFromString,QLever (no Tensor Vocabulary),embedded,20551
97,7,totalExecution,QLever (no Tensor Vocabulary),embedded,1

In [126]:
all_timings["timing_key"].unique()

<ArrowStringArray>
['processQueryAndSendResult',            'readTensorData',
          'readWordFromDisk',    'tensorCosineSimilarity',
          'tensorFromBuffer',          'tensorFromString',
            'totalExecution',  'tensorIndexComputeResult']
Length: 8, dtype: str

In [127]:
timing_mapping = {
    "totalExecution": "Total (ms)",
    "readTensorData": "Read Tensors (ms)",
    "readWordFromDisk": "Read RDF (ms)",
    "tensorCosineSimilarity": "Cosine Similarity (ms)",
    "tensorFromBuffer": "Parse from Buffer (ms)",
    "tensorFromString": "Parse from String (ms)",
    "tensorIndexComputeResult": "Index Lookup (ms)",
}
all_timings["timing_key"] = all_timings["timing_key"].map(timing_mapping).fillna(all_timings["timing_key"])

# timing mappings to columns

all_timings_grouped = (
    all_timings.groupby(["engine", "query_type", "timing_key"])[["timings"]]
    .median()
    .reset_index()
    .sort_values(by=["engine", "query_type", "timing_key"])
)
all_timings_grouped["timings"] = all_timings_grouped["timings"] / 1e6  # convert to ms

all_timings_grouped

              engine query_type                 timing_key      timings
0          RDFTensor   Embedded     Cosine Similarity (ms)  1431.662300
1          RDFTensor   Embedded     Parse from String (ms)     0.953318
2          RDFTensor   Embedded                 Total (ms)  1757.084727
3   \systemname-Base   Embedded     Cosine Similarity (ms)     9.089006
4   \systemname-Base   Embedded     Parse from String (ms)    20.230249
5   \systemname-Base   Embedded              Read RDF (ms)    29.624893
6   \systemname-Base   Embedded                 Total (ms)  1179.110169
7   \systemname-Base   Embedded  processQueryAndSendResult  1151.317713
8   \systemname-Base      Index          Index Lookup (ms)     3.954499
9   \systemname-Base      Index     Parse from String (ms)     0.002724
10  \systemname-Base      Index              Read RDF (ms)     0.193411
11  \systemname-Base      Index                 Total (ms)    25.285363
12  \systemname-Base      Index  processQueryAndSendResult     4.728329
13    \systemname-TV   Embedded     Cosine Similarity (ms)     8.300608
14    \systemname-TV   Embedded     Parse from Buffer (ms)     2.747562
15    \systemname-TV   Embedded     Parse from String (ms)     0.020866
16    \systemname-TV   Embedded              Read RDF (ms)     0.209392
17    \systemname-TV   Embedded          Read Tensors (ms)   188.608091
18    \systemname-TV   Embedded                 Total (ms)   538.276553
19    \systemname-TV   Embedded  processQueryAndSendResult   517.552285
20    \systemname-TV      Index          Index Lookup (ms)     4.785185
21    \systemname-TV      Index     Parse from Buffer (ms)     0.113561
22    \systemname-TV      Index     Parse from String (ms)     0.002975
23    \systemname-TV      Index              Read RDF (ms)     0.461216
24    \systemname-TV      Index          Read Tensors (ms)     9.508288
25    \systemname-TV      Index                 Total (ms)    25.979280
26    \systemname-TV      Index  processQueryAndSendResult     5.435574

In [132]:
all_timings_pivot = all_timings_grouped.pivot_table(
    index=["engine", "query_type"], columns="timing_key", values="timings"
).reset_index().fillna("-").set_index(["engine", "query_type"])
all_timings_pivot

timing_key                  Cosine Similarity (ms) Index Lookup (ms)  \
engine           query_type
RDFTensor        Embedded                1431.6623                 -
\systemname-Base Embedded                 9.089006                 -
                 Index                           -          3.954499
\systemname-TV   Embedded                 8.300608                 -
                 Index                           -          4.785185

timing_key                  Parse from Buffer (ms)  Parse from String (ms)  \
engine           query_type
RDFTensor        Embedded                        -                0.953318
\systemname-Base Embedded                        -               20.230249
                 Index                           -                0.002724
\systemname-TV   Embedded                 2.747562                0.020866
                 Index                    0.113561                0.002975

timing_key                  Read RDF (ms) Read Tensors (ms)   Total (ms)  \
engine           query_type
RDFTensor        Embedded               -                 -  1757.084727
\systemname-Base Embedded       29.624893                 -  1179.110169
                 Index           0.193411                 -    25.285363
\systemname-TV   Embedded        0.209392        188.608091   538.276553
                 Index           0.461216          9.508288    25.979280

timing_key                  processQueryAndSendResult
engine           query_type
RDFTensor        Embedded                           -
\systemname-Base Embedded                 1151.317713
                 Index                       4.728329
\systemname-TV   Embedded                  517.552285
                 Index                       5.435574

In [ ]:
counts=[]
for power, size in zip(powers, sizes):
    difficulties = [
        QUERY_DIFFICULTY.HARD,
        QUERY_DIFFICULTY.EASY,
    ]
    dataset = datasets[power]
    db = QleverDBNative(
        id="timing-qlever",
        base_dir=Path(f"./scratch/bsbm/{dataset.base_dir.name}"),
        dataset=dataset,
        use_encoded_ttl=True,
    )
    with db:
        full_number_of_tensors = db.query("""
PREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#>
SELECT (COUNT(?v) AS ?count) WHERE {
    {
    SELECT ?s ?v WHERE {          
    ?s rdf:label_embedding ?v .
    }
    } UNION {
            SELECT ?s ?v WHERE {
        ?s rdf:comment_embedding ?v .}
    }
}
""")["count"].values[0]
        full_size = db.get_triple_count()
        counts.append({
            "power": power,
            "size": size,
            "full_size": full_size,
            "full_number_of_tensors": full_number_of_tensors,
        })
counts_df = pd.DataFrame(counts)
counts_df

2026-04-17 17:08:59,387 - WARNING - Killing any existing process using port 26087 before starting the server
2026-04-17 17:08:59,409 - ERROR - Command failed with return code 1
2026-04-17 17:08:59,410 - INFO - Initialized QLeverDBNative with id=timing-qlever, port_id=26087, dataset=bsbm, name=QLever Native (Extended), use_encoded_ttl=True, endpoint=http://localhost:26087/timing-qlever-with-tidx/sparql
2026-04-17 17:08:59,410 - INFO - Logging QLever setup to scratch/bsbm/bsbm_0/db/timing-qlever-with-tidx/timing-qlever-with-tidx_run.log
2026-04-17 17:08:59,411 - INFO - Loading dataset into QLever server from data/bsbm_0/dataset.nt
2026-04-17 17:08:59,412 - WARNING - DB directory scratch/bsbm/bsbm_0/db/timing-qlever-with-tidx already exists!
2026-04-17 17:08:59,412 - INFO - Stopping server!
2026-04-17 17:08:59,430 - ERROR - Command failed with return code 1
2026-04-17 17:08:59,430 - INFO - Starting QLever server on port 26087
2026-04-17 17:08:59,431 - INFO - Running command: qlever-server -i timing-qlever-with-tidx --port 26087 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-17 17:08:59,433 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:26087/timing-qlever-with-tidx/sparql)
2026-04-17 17:09:00,444 - INFO - Server is up and responding to queries
2026-04-17 17:09:00,457 - INFO - Stopping server!
2026-04-17 17:09:00,595 - ERROR - Command failed with return code 1
2026-04-17 17:09:00,597 - WARNING - Killing any existing process using port 26088 before starting the server
2026-04-17 17:09:00,615 - ERROR - Command failed with return code 1
2026-04-17 17:09:00,616 - INFO - Initialized QLeverDBNative with id=timing-qlever, port_id=26088, dataset=bsbm, name=QLever Native (Extended), use_encoded_ttl=True, endpoint=http://localhost:26088/timing-qlever-with-tidx/sparql
2026-04-17 17:09:00,616 - INFO - Logging QLever setup to scratch/bsbm/bsbm_1/db/timing-qlever-with-tidx/timing-qlever-with-tidx_run.log
2026-04-17 17:09:00,617 - INFO - Loading dataset into QLever server from data/bsbm_1/dataset.nt
2026-04-17 17:09:00,617 - WARNING - DB directory scratch/bsbm/bsbm_1/db/timing-qlever-with-tidx already exists!
2026-04-17 17:09:00,618 - INFO - Stopping server!
2026-04-17 17:09:00,635 - ERROR - Command failed with return code 1
2026-04-17 17:09:00,636 - INFO - Starting QLever server on port 26088
2026-04-17 17:09:00,636 - INFO - Running command: qlever-server -i timing-qlever-with-tidx --port 26088 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-17 17:09:00,638 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:26088/timing-qlever-with-tidx/sparql)
2026-04-17 17:09:01,648 - INFO - Server is up and responding to queries
2026-04-17 17:09:01,662 - INFO - Stopping server!
2026-04-17 17:09:01,756 - ERROR - Command failed with return code 1
2026-04-17 17:09:01,757 - WARNING - Killing any existing process using port 26089 before starting the server
2026-04-17 17:09:01,773 - ERROR - Command failed with return code 1
2026-04-17 17:09:01,774 - INFO - Initialized QLeverDBNative with id=timing-qlever, port_id=26089, dataset=bsbm, name=QLever Native (Extended), use_encoded_ttl=True, endpoint=http://localhost:26089/timing-qlever-with-tidx/sparql
2026-04-17 17:09:01,775 - INFO - Logging QLever setup to scratch/bsbm/bsbm_2/db/timing-qlever-with-tidx/timing-qlever-with-tidx_run.log
2026-04-17 17:09:01,775 - INFO - Loading dataset into QLever server from data/bsbm_2/dataset.nt
2026-04-17 17:09:01,776 - WARNING - DB directory scratch/bsbm/bsbm_2/db/timing-qlever-with-tidx already exists!
2026-04-17 17:09:01,776 - INFO - Stopping server!
2026-04-17 17:09:01,792 - ERROR - Command failed with return code 1
2026-04-17 17:09:01,792 - INFO - Starting QLever server on port 26089
2026-04-17 17:09:01,793 - INFO - Running command: qlever-server -i timing-qlever-with-tidx --port 26089 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-17 17:09:01,795 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:26089/timing-qlever-with-tidx/sparql)
2026-04-17 17:09:02,807 - INFO - Server is up and responding to queries
2026-04-17 17:09:02,827 - INFO - Stopping server!
2026-04-17 17:09:02,846 - ERROR - Command failed with return code 1
2026-04-17 17:09:02,847 - WARNING - Killing any existing process using port 26090 before starting the server
2026-04-17 17:09:02,865 - ERROR - Command failed with return code 1
2026-04-17 17:09:02,866 - INFO - Initialized QLeverDBNative with id=timing-qlever, port_id=26090, dataset=bsbm, name=QLever Native (Extended), use_encoded_ttl=True, endpoint=http://localhost:26090/timing-qlever-with-tidx/sparql
2026-04-17 17:09:02,867 - INFO - Logging QLever setup to scratch/bsbm/bsbm_3/db/timing-qlever-with-tidx/timing-qlever-with-tidx_run.log
2026-04-17 17:09:02,868 - INFO - Loading dataset into QLever server from data/bsbm_3/dataset.nt
2026-04-17 17:09:02,868 - WARNING - DB directory scratch/bsbm/bsbm_3/db/timing-qlever-with-tidx already exists!
2026-04-17 17:09:02,869 - INFO - Stopping server!
2026-04-17 17:09:02,885 - ERROR - Command failed with return code 1
2026-04-17 17:09:02,886 - INFO - Starting QLever server on port 26090
2026-04-17 17:09:02,886 - INFO - Running command: qlever-server -i timing-qlever-with-tidx --port 26090 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-17 17:09:02,888 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:26090/timing-qlever-with-tidx/sparql)
2026-04-17 17:09:03,900 - INFO - Server is up and responding to queries
2026-04-17 17:09:03,930 - INFO - Stopping server!
2026-04-17 17:09:04,029 - ERROR - Command failed with return code 1
2026-04-17 17:09:04,031 - WARNING - Killing any existing process using port 26091 before starting the server
2026-04-17 17:09:04,048 - ERROR - Command failed with return code 1
2026-04-17 17:09:04,049 - INFO - Initialized QLeverDBNative with id=timing-qlever, port_id=26091, dataset=bsbm, name=QLever Native (Extended), use_encoded_ttl=True, endpoint=http://localhost:26091/timing-qlever-with-tidx/sparql
2026-04-17 17:09:04,050 - INFO - Logging QLever setup to scratch/bsbm/bsbm_4/db/timing-qlever-with-tidx/timing-qlever-with-tidx_run.log
2026-04-17 17:09:04,050 - INFO - Loading dataset into QLever server from data/bsbm_4/dataset.nt
2026-04-17 17:09:04,052 - WARNING - DB directory scratch/bsbm/bsbm_4/db/timing-qlever-with-tidx already exists!
2026-04-17 17:09:04,052 - INFO - Stopping server!
2026-04-17 17:09:04,068 - ERROR - Command failed with return code 1
2026-04-17 17:09:04,069 - INFO - Starting QLever server on port 26091
2026-04-17 17:09:04,070 - INFO - Running command: qlever-server -i timing-qlever-with-tidx --port 26091 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-17 17:09:04,071 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:26091/timing-qlever-with-tidx/sparql)
2026-04-17 17:09:05,082 - INFO - Server is up and responding to queries
2026-04-17 17:09:05,128 - INFO - Stopping server!
2026-04-17 17:09:05,227 - ERROR - Command failed with return code 1
2026-04-17 17:09:05,228 - WARNING - Killing any existing process using port 26092 before starting the server
2026-04-17 17:09:05,246 - ERROR - Command failed with return code 1
2026-04-17 17:09:05,247 - INFO - Initialized QLeverDBNative with id=timing-qlever, port_id=26092, dataset=bsbm, name=QLever Native (Extended), use_encoded_ttl=True, endpoint=http://localhost:26092/timing-qlever-with-tidx/sparql
2026-04-17 17:09:05,248 - INFO - Logging QLever setup to scratch/bsbm/bsbm_5/db/timing-qlever-with-tidx/timing-qlever-with-tidx_run.log
2026-04-17 17:09:05,248 - INFO - Loading dataset into QLever server from data/bsbm_5/dataset.nt
2026-04-17 17:09:05,249 - WARNING - DB directory scratch/bsbm/bsbm_5/db/timing-qlever-with-tidx already exists!
2026-04-17 17:09:05,249 - INFO - Stopping server!
2026-04-17 17:09:05,265 - ERROR - Command failed with return code 1
2026-04-17 17:09:05,266 - INFO - Starting QLever server on port 26092
2026-04-17 17:09:05,267 - INFO - Running command: qlever-server -i timing-qlever-with-tidx --port 26092 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-17 17:09:05,270 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:26092/timing-qlever-with-tidx/sparql)
2026-04-17 17:09:06,282 - INFO - Server is up and responding to queries
2026-04-17 17:09:06,389 - INFO - Stopping server!
2026-04-17 17:09:06,489 - ERROR - Command failed with return code 1

   power    size  full_size full_number_of_tensors
0      0       1       2418                    576
1      1      10       5595                    608
2      2     100      42417                   2240
3      3    1000     383751                  11840
4      4   10000    3577077                  42304
5      5  100000   35177974                 305792

In [ ]:
counts_df = counts_df.astype(int)
counts_df

   power    size  full_size  full_number_of_tensors
0      0       1       2418                     576
1      1      10       5595                     608
2      2     100      42417                    2240
3      3    1000     383751                   11840
4      4   10000    3577077                   42304
5      5  100000   35177974                  305792

In [ ]:
out_dir = Path("./scratch/results")
out_dir.mkdir(parents=True, exist_ok=True)
from utils.helpers import pretty_print_counts
pretty_print_counts(counts_df, out_dir / "bsbm_counts.tex")

   Power  Generation $t$       $n$  $n_{tensors}$
0      0               1      2418            576
1      1              10      5595            608
2      2             100     42417           2240
3      3            1000    383751          11840
4      4           10000   3577077          42304
5      5          100000  35177974         305792