In [ ]:
%load_ext autoreload
%autoreload 2

In [ ]:
import tqdm
import sys
import os

In [ ]:
from sentence_transformers import SentenceTransformer

encoding_model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
import dotenv
import os

config = dotenv.dotenv_values(".env")
replace_keys = ["JAVA_HOME", "FUSEKI_HOME"]
append_keys = ["PATH"]
for key, value in config.items():
    # append to os.environ
    if key in append_keys:
        os.environ[key] = f"{os.environ.get(key, '')}:{value}"
    elif key in replace_keys:
        os.environ[key] = value

# check and compare values in fuseki log
os.environ["OPENBLAS_NUM_THREADS"] = "4"

In [ ]:
sys.path.append(".")

In [ ]:
from utils.datasets import SimpleSet, BerlinSparqlBenchmark
from utils.dbs.qlever import QleverDB
from utils.dbs.fuseki import FusekiDB
from utils.dbs.base_db import BaseDB
from utils.dbs.qlever_native import QleverDBNative
from utils.dbs.fuseki_native import FusekiDBNative
from utils.datasets.base_dataset import QUERY_DIFFICULTY, QUERY_TYPE
from pathlib import Path
import pandas as pd
import numpy as np
from utils.datasets.base_dataset import DataTensor

2026-04-28 16:13:24,262 - INFO - Loading faiss with AVX512 support.
2026-04-28 16:13:24,263 - INFO - Could not load library with AVX512 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx512'")
2026-04-28 16:13:24,264 - INFO - Loading faiss with AVX2 support.
2026-04-28 16:13:24,265 - INFO - Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2026-04-28 16:13:24,265 - INFO - Loading faiss.
2026-04-28 16:13:24,293 - INFO - Successfully loaded faiss.

In [ ]:
powers = np.arange(0, 6)  # extend on a more powerful machine
sizes = 10**powers

In [ ]:
datasets: dict[int, BerlinSparqlBenchmark] = {}
raw_sizes: dict[int, int] = {}
for power, size in zip(powers, sizes):
    print(f"Running BDSDM generation for size {size}...")
    dataset = BerlinSparqlBenchmark(base_dir=Path(f"./data/bsbm_{power}"), n=size)
    dataset.setup()
    datasets[power] = dataset
    # raw_sizes[power] = dataset.get_triple_count()

2026-04-28 16:13:24,423 - INFO - BSBM dataset already exists in data/bsbm_0, skipping generation
2026-04-28 16:13:24,424 - INFO - BSBM dataset already exists in data/bsbm_1, skipping generation
2026-04-28 16:13:24,425 - INFO - BSBM dataset already exists in data/bsbm_2, skipping generation
2026-04-28 16:13:24,425 - INFO - BSBM dataset already exists in data/bsbm_3, skipping generation
2026-04-28 16:13:24,426 - INFO - BSBM dataset already exists in data/bsbm_4, skipping generation
2026-04-28 16:13:24,426 - INFO - BSBM dataset already exists in data/bsbm_5, skipping generation

Running BDSDM generation for size 1...
Running BDSDM generation for size 10...
Running BDSDM generation for size 100...
Running BDSDM generation for size 1000...
Running BDSDM generation for size 10000...
Running BDSDM generation for size 100000...

In [ ]:
encoded_sizes: dict[int, int] = {}
for power, size in zip(powers, sizes):
    print(f"Encoding dataset of size {size}/power {power}...")
    dataset = datasets[power]
    encoded_sizes[power] = dataset.encode(encoding_model)
    #  dataset.get_triple_count(encoded=True)

Encoding dataset of size 1/power 0...
Encoded TTL file already exists at data/bsbm_0/dataset_encoded.nt, skipping encoding
Encoding dataset of size 10/power 1...
Encoded TTL file already exists at data/bsbm_1/dataset_encoded.nt, skipping encoding
Encoding dataset of size 100/power 2...
Encoded TTL file already exists at data/bsbm_2/dataset_encoded.nt, skipping encoding
Encoding dataset of size 1000/power 3...
Encoded TTL file already exists at data/bsbm_3/dataset_encoded.nt, skipping encoding
Encoding dataset of size 10000/power 4...
Encoded TTL file already exists at data/bsbm_4/dataset_encoded.nt, skipping encoding
Encoding dataset of size 100000/power 5...
Encoded TTL file already exists at data/bsbm_5/dataset_encoded.nt, skipping encoding

## BSBM queries

### Simple Use case: 
find 10 products with a specific encoded label


### Complex Use case: 
For a specific product find 10 other similar products via their product label.

In [ ]:
test_label = "house furniture storage container"
test_tensor = DataTensor.from_numpy(encoding_model.encode(test_label))

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
test_tensor.to_literal().n3()

'"{\\"data\\": [0.001923849806189537, 0.059069667011499405, -0.06259278953075409, -0.008788925595581532, 0.08017760515213013, 0.0004897266626358032, 0.049011558294296265, -0.016156358644366264, -0.04537816718220711, 0.011929630301892757, -0.003551364177837968, -0.0034783161245286465, 0.023264417424798012, 0.02449001744389534, -0.023595571517944336, -0.073823943734169, 0.014226873405277729, -0.00022305997845251113, -0.03111756220459938, 0.07163400948047638, -0.04559392109513283, 0.044428009539842606, 0.0004388350062072277, -0.004044292028993368, 0.05173112079501152, 0.08436278998851776, -0.028667306527495384, -0.032494205981492996, 0.058949727565050125, -0.0051073553040623665, 0.09506019204854965, -0.029170090332627296, -0.07172352075576782, 0.036426812410354614, 0.01788988709449768, 0.07774496078491211, -0.01058284193277359, -0.02719942107796669, -0.014839782379567623, 0.004996407311409712, -0.05195301026105881, -0.01563340425491333, -0.0004883587826043367, 0.012572054751217365, -0.043422963470220566, -0.011021864600479603, -0.024199120700359344, -0.030226601287722588, 0.04542998597025871, -0.007276976015418768, 0.01397930271923542, 0.050883397459983826, -0.01848265342414379, 0.049168676137924194, -0.008279561065137386, 0.044504038989543915, 0.04745961353182793, 0.043078307062387466, -0.046442680060863495, 0.036845613270998, 0.10432934015989304, -0.015816830098628998, 0.10823524743318558, -0.028953377157449722, 0.04555060341954231, -0.030880587175488472, -0.051015835255384445, 0.05478580296039581, -0.0291702002286911, -0.005334345158189535, -0.06260965764522552, 0.034982938319444656, 0.026750046759843826, 0.04171916842460632, 0.03431631997227669, -0.07216819375753403, -0.00024255513562820852, -0.048893045634031296, 0.02389506623148918, 0.12748239934444427, -0.08703242987394333, 0.03412925824522972, 0.02240350842475891, 0.002564689377322793, -0.17344096302986145, 0.04103534668684006, -0.017823603004217148, -0.0076851267367601395, -0.09476081281900406, -0.07406330108642578, 0.08501428365707397, 0.04020910710096359, 0.08708695322275162, -0.026967616751790047, -0.060038503259420395, -0.003988019190728664, -0.02539210394024849, 0.022482113912701607, 0.060429759323596954, 0.037002742290496826, -0.0065333242528140545, 0.021862275898456573, 0.00022625424026045948, -0.033486779779195786, -0.07245824486017227, -0.1024286150932312, 0.049249906092882156, -0.009056593291461468, 0.007512359414249659, 0.0021412500645965338, -0.09075023233890533, 0.040666837245225906, -0.06107519939541817, -0.002982238307595253, -0.06842709332704544, 0.0025372530799359083, -0.01641230843961239, -0.043180201202631, 0.039085742086172104, -0.10427255183458328, 0.0473635196685791, -0.019185954704880714, 0.05296330899000168, 0.019953425973653793, 0.0329863503575325, 0.03303090110421181, 0.04857225716114044, 7.191068898027963e-35, -0.018325448036193848, -0.06909802556037903, 0.024108240380883217, 0.04407642409205437, 0.06294272840023041, 0.029094791039824486, 0.06375113874673843, 0.07381084561347961, 0.0368872731924057, 0.019980719313025475, -0.013145486824214458, -0.027676766738295555, -0.10194964706897736, -0.002321777166798711, -0.0032931924797594547, -0.02191285789012909, -0.09255401045084, 0.03210889920592308, 0.015278536826372147, -0.04234621301293373, 0.0064256093464791775, 0.04209345206618309, -0.019585780799388885, 0.03202011436223984, 0.037421416491270065, -0.018620574846863747, 0.019987355917692184, -0.013685979880392551, -0.03424428403377533, 0.012987463735044003, 0.04883616417646408, -0.0011513904901221395, -0.008845774456858635, 0.005870802327990532, -0.07762148231267929, -0.025999465957283974, -0.06829018890857697, 0.018836436793208122, -0.02234852872788906, -0.07037260383367538, 0.012542112730443478, 0.03438114747405052, 0.14274704456329346, 0.07548227161169052, 0.008455806411802769, -0.02049204707145691, 0.004560847766697407, -0.025547219440340996, -0.11879655718803406, 0.001291911699809134, -0.03331619128584862, 0.025502456352114677, -0.09485730528831482, 0.08408985286951065, -0.05816476047039032, -0.029875924810767174, -0.01281525194644928, -0.06466028094291687, 0.0453050322830677, 0.004283205606043339, 0.035003237426280975, 0.04375073313713074, 0.043108899146318436, -0.001907631172798574, 0.016851212829351425, -0.026979830116033554, 0.010974003002047539, 0.016453053802251816, 0.09936032444238663, 0.009172468446195126, 0.007693963125348091, -0.00969709176570177, 0.023047752678394318, -0.021144036203622818, 0.03724559023976326, -0.013058981858193874, -0.029100554063916206, 0.01229681633412838, -0.09894735366106033, -0.12643840909004211, 0.04589775577187538, -0.07361725717782974, 0.04434674605727196, 0.050329189747571945, -0.06559285521507263, -0.09371957182884216, 0.024369491264224052, -0.01520457398146391, -0.0038548363372683525, 0.027220020070672035, -0.031000541523098946, 0.015559685416519642, -0.006960012950003147, -0.041212767362594604, -0.08390278369188309, -4.97649344593706e-34, 0.05890499800443649, -0.06461971998214722, -0.07525855302810669, 0.058098528534173965, 0.06788986176252365, 0.019036881625652313, -0.007119014859199524, -0.043491482734680176, -0.017167028039693832, -0.04744131118059158, -0.04438185319304466, 0.0017611982766538858, 0.11509203165769577, 0.055401794612407684, -0.04163767397403717, 0.06279648095369339, -0.004321553744375706, -0.06458307802677155, 0.04710076004266739, 0.027388490736484528, -0.028406115248799324, -0.0031859995797276497, 0.01728656329214573, 0.03930680826306343, -0.042606621980667114, -0.03965207189321518, 0.050438474863767624, -0.05095212534070015, -0.009358619339764118, -0.005097959190607071, -0.042747560888528824, -0.09899874031543732, 0.046798769384622574, 0.06118430569767952, -0.029022959992289543, -0.11554227024316788, -0.011058848351240158, -0.036974892020225525, -0.08948592841625214, -0.014271756634116173, 0.013834885321557522, -0.01605868525803089, -0.04475671425461769, 0.03806497901678085, -0.05086902156472206, -0.06123126670718193, -0.08582713454961777, 0.018628671765327454, 0.10956262052059174, 0.03865630552172661, -0.005097296088933945, -0.024105655029416084, -0.012989535927772522, -0.07685093581676483, -0.00417094212025404, 0.089471735060215, -0.005915124900639057, 0.014249371364712715, -0.013326791115105152, 0.1283029317855835, -0.0087217316031456, 0.10300467163324356, 0.03298785537481308, -0.011241207830607891, 0.024034647271037102, 0.048094574362039566, 0.011020636186003685, -0.037912674248218536, -0.05348319187760353, 0.025995740666985512, 0.1147560179233551, 0.023856690153479576, 0.08506986498832703, 0.1052437573671341, 0.003146340372040868, -0.06395517289638519, 0.09612903743982315, -0.013588497415184975, 0.07226214557886124, 0.008729256689548492, -0.03723451867699623, -0.011913117952644825, 0.00031532489811070263, 0.007079592905938625, 0.03848397731781006, -0.09682920575141907, -0.014785494655370712, 0.002893038559705019, -0.06805280596017838, 0.0401400662958622, -0.022343454882502556, 0.08511822670698166, -0.13211962580680847, 0.03063001111149788, 0.0910293459892273, -1.2904515678258122e-08, -0.04676821827888489, -0.006705537438392639, 0.022972706705331802, -0.022980324923992157, -0.07330192625522614, -0.05493609607219696, 0.147051140666008, 0.07781931012868881, 0.032597970217466354, -0.04455342888832092, 0.011822628788650036, -0.0011622520396485925, -0.08087407797574997, -0.029209928587079048, -0.04869680851697922, 0.01635807752609253, -0.013975921086966991, 0.02993103303015232, -0.02186085842549801, 0.027337562292814255, 0.06173807755112648, -0.05552144721150398, 0.11173667758703232, -0.002850713673979044, 0.0067396159283816814, -0.014453276060521603, 0.03404010832309723, 0.06328174471855164, 0.09785991162061691, 0.016026383265852928, 0.02463620714843273, 0.010196371003985405, 0.03231675177812576, 0.03482783958315849, 0.012972479686141014, 0.06374970823526382, -0.12293172627687454, -0.01703498885035515, -0.028862323611974716, -0.036092162132263184, -0.0514722540974617, -0.11512449383735657, -0.012429235503077507, -0.08940501511096954, 0.06870079040527344, 0.026553628966212273, -0.03257280960679054, 0.046524085104465485, 0.00020684042829088867, 0.06025783717632294, -0.015267660841345787, 0.0010977181373164058, 0.005369286052882671, 0.03770275413990021, 0.023572636768221855, 0.0035807902459055185, -0.03384198620915413, -0.026205267757177353, 0.06975211203098297, 0.020543193444609642, -0.015171892009675503, 0.05312025547027588, 0.014551732689142227, 0.02318691834807396], \\"type\\": \\"float32\\", \\"shape\\": [384]}"^^<https://w3id.org/rdf-tensor/datatypes#NumericDataTensor>'

In [ ]:
base_bsbm_set = datasets[4]
db = QleverDBNative(
    id="test",
    base_dir=Path(f"./scratch/bsbm/{base_bsbm_set.base_dir.name}"),
    dataset=base_bsbm_set,
    use_encoded_ttl=True,
)
possible_queries = db.get_queries(test_tensor)
print(possible_queries)

2026-04-28 16:13:25,128 - WARNING - Killing any existing process using port 26043 before starting the server
2026-04-28 16:13:25,149 - ERROR - Command failed with return code 1
2026-04-28 16:13:25,150 - INFO - Initialized QLeverDBNative with id=test, port_id=26043, dataset=bsbm, name=QLever Native (Extended), use_encoded_ttl=True, endpoint=http://localhost:26043/test-with-tidx/sparql

{<QUERY_DIFFICULTY.EASY: 'easy'>: {<QUERY_TYPE.EMBEDDED: 'embedded'>: '\nPREFIX dt: <https://w3id.org/rdf-tensor/datatypes#>\nPREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#>\nPREFIX dtf: <https://w3id.org/rdf-tensor/functions#>\nPREFIX bsbmi: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>\nPREFIX bsbmv: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>\nSELECT DISTINCT ?product  ?vector ?dist \nWHERE {\n?product rdf:label_embedding ?vector .\n?product bsbmv:productFeature ?feat .\nBIND(dtf:dotProduct(?vector, "{\\"data\\": [0.001923849806189537, 0.059069667011499405, -0.06259278953075409, -0.008788925595581532, 0.08017760515213013, 0.0004897266626358032, 0.049011558294296265, -0.016156358644366264, -0.04537816718220711, 0.011929630301892757, -0.003551364177837968, -0.0034783161245286465, 0.023264417424798012, 0.02449001744389534, -0.023595571517944336, -0.073823943734169, 0.014226873405277729, -0.00022305997845251113, -0.03111756220459938, 0.07163400948047638, -0.04559392109513283, 0.044428009539842606, 0.0004388350062072277, -0.004044292028993368, 0.05173112079501152, 0.08436278998851776, -0.028667306527495384, -0.032494205981492996, 0.058949727565050125, -0.0051073553040623665, 0.09506019204854965, -0.029170090332627296, -0.07172352075576782, 0.036426812410354614, 0.01788988709449768, 0.07774496078491211, -0.01058284193277359, -0.02719942107796669, -0.014839782379567623, 0.004996407311409712, -0.05195301026105881, -0.01563340425491333, -0.0004883587826043367, 0.012572054751217365, -0.043422963470220566, -0.011021864600479603, -0.024199120700359344, -0.030226601287722588, 0.04542998597025871, -0.007276976015418768, 0.01397930271923542, 0.050883397459983826, -0.01848265342414379, 0.049168676137924194, -0.008279561065137386, 0.044504038989543915, 0.04745961353182793, 0.043078307062387466, -0.046442680060863495, 0.036845613270998, 0.10432934015989304, -0.015816830098628998, 0.10823524743318558, -0.028953377157449722, 0.04555060341954231, -0.030880587175488472, -0.051015835255384445, 0.05478580296039581, -0.0291702002286911, -0.005334345158189535, -0.06260965764522552, 0.034982938319444656, 0.026750046759843826, 0.04171916842460632, 0.03431631997227669, -0.07216819375753403, -0.00024255513562820852, -0.048893045634031296, 0.02389506623148918, 0.12748239934444427, -0.08703242987394333, 0.03412925824522972, 0.02240350842475891, 0.002564689377322793, -0.17344096302986145, 0.04103534668684006, -0.017823603004217148, -0.0076851267367601395, -0.09476081281900406, -0.07406330108642578, 0.08501428365707397, 0.04020910710096359, 0.08708695322275162, -0.026967616751790047, -0.060038503259420395, -0.003988019190728664, -0.02539210394024849, 0.022482113912701607, 0.060429759323596954, 0.037002742290496826, -0.0065333242528140545, 0.021862275898456573, 0.00022625424026045948, -0.033486779779195786, -0.07245824486017227, -0.1024286150932312, 0.049249906092882156, -0.009056593291461468, 0.007512359414249659, 0.0021412500645965338, -0.09075023233890533, 0.040666837245225906, -0.06107519939541817, -0.002982238307595253, -0.06842709332704544, 0.0025372530799359083, -0.01641230843961239, -0.043180201202631, 0.039085742086172104, -0.10427255183458328, 0.0473635196685791, -0.019185954704880714, 0.05296330899000168, 0.019953425973653793, 0.0329863503575325, 0.03303090110421181, 0.04857225716114044, 7.191068898027963e-35, -0.018325448036193848, -0.06909802556037903, 0.024108240380883217, 0.04407642409205437, 0.06294272840023041, 0.029094791039824486, 0.06375113874673843, 0.07381084561347961, 0.0368872731924057, 0.019980719313025475, -0.013145486824214458, -0.027676766738295555, -0.10194964706897736, -0.002321777166798711, -0.0032931924797594547, -0.02191285789012909, -0.09255401045084, 0.03210889920592308, 0.015278536826372147, -0.04234621301293373, 0.0064256093464791775, 0.04209345206618309, -0.019585780799388885, 0.03202011436223984, 0.037421416491270065, -0.018620574846863747, 0.019987355917692184, -0.013685979880392551, -0.03424428403377533, 0.012987463735044003, 0.04883616417646408, -0.0011513904901221395, -0.008845774456858635, 0.005870802327990532, -0.07762148231267929, -0.025999465957283974, -0.06829018890857697, 0.018836436793208122, -0.02234852872788906, -0.07037260383367538, 0.012542112730443478, 0.03438114747405052, 0.14274704456329346, 0.07548227161169052, 0.008455806411802769, -0.02049204707145691, 0.004560847766697407, -0.025547219440340996, -0.11879655718803406, 0.001291911699809134, -0.03331619128584862, 0.025502456352114677, -0.09485730528831482, 0.08408985286951065, -0.05816476047039032, -0.029875924810767174, -0.01281525194644928, -0.06466028094291687, 0.0453050322830677, 0.004283205606043339, 0.035003237426280975, 0.04375073313713074, 0.043108899146318436, -0.001907631172798574, 0.016851212829351425, -0.026979830116033554, 0.010974003002047539, 0.016453053802251816, 0.09936032444238663, 0.009172468446195126, 0.007693963125348091, -0.00969709176570177, 0.023047752678394318, -0.021144036203622818, 0.03724559023976326, -0.013058981858193874, -0.029100554063916206, 0.01229681633412838, -0.09894735366106033, -0.12643840909004211, 0.04589775577187538, -0.07361725717782974, 0.04434674605727196, 0.050329189747571945, -0.06559285521507263, -0.09371957182884216, 0.024369491264224052, -0.01520457398146391, -0.0038548363372683525, 0.027220020070672035, -0.031000541523098946, 0.015559685416519642, -0.006960012950003147, -0.041212767362594604, -0.08390278369188309, -4.97649344593706e-34, 0.05890499800443649, -0.06461971998214722, -0.07525855302810669, 0.058098528534173965, 0.06788986176252365, 0.019036881625652313, -0.007119014859199524, -0.043491482734680176, -0.017167028039693832, -0.04744131118059158, -0.04438185319304466, 0.0017611982766538858, 0.11509203165769577, 0.055401794612407684, -0.04163767397403717, 0.06279648095369339, -0.004321553744375706, -0.06458307802677155, 0.04710076004266739, 0.027388490736484528, -0.028406115248799324, -0.0031859995797276497, 0.01728656329214573, 0.03930680826306343, -0.042606621980667114, -0.03965207189321518, 0.050438474863767624, -0.05095212534070015, -0.009358619339764118, -0.005097959190607071, -0.042747560888528824, -0.09899874031543732, 0.046798769384622574, 0.06118430569767952, -0.029022959992289543, -0.11554227024316788, -0.011058848351240158, -0.036974892020225525, -0.08948592841625214, -0.014271756634116173, 0.013834885321557522, -0.01605868525803089, -0.04475671425461769, 0.03806497901678085, -0.05086902156472206, -0.06123126670718193, -0.08582713454961777, 0.018628671765327454, 0.10956262052059174, 0.03865630552172661, -0.005097296088933945, -0.024105655029416084, -0.012989535927772522, -0.07685093581676483, -0.00417094212025404, 0.089471735060215, -0.005915124900639057, 0.014249371364712715, -0.013326791115105152, 0.1283029317855835, -0.0087217316031456, 0.10300467163324356, 0.03298785537481308, -0.011241207830607891, 0.024034647271037102, 0.048094574362039566, 0.011020636186003685, -0.037912674248218536, -0.05348319187760353, 0.025995740666985512, 0.1147560179233551, 0.023856690153479576, 0.08506986498832703, 0.1052437573671341, 0.003146340372040868, -0.06395517289638519, 0.09612903743982315, -0.013588497415184975, 0.07226214557886124, 0.008729256689548492, -0.03723451867699623, -0.011913117952644825, 0.00031532489811070263, 0.007079592905938625, 0.03848397731781006, -0.09682920575141907, -0.014785494655370712, 0.002893038559705019, -0.06805280596017838, 0.0401400662958622, -0.022343454882502556, 0.08511822670698166, -0.13211962580680847, 0.03063001111149788, 0.0910293459892273, -1.2904515678258122e-08, -0.04676821827888489, -0.006705537438392639, 0.022972706705331802, -0.022980324923992157, -0.07330192625522614, -0.05493609607219696, 0.147051140666008, 0.07781931012868881, 0.032597970217466354, -0.04455342888832092, 0.011822628788650036, -0.0011622520396485925, -0.08087407797574997, -0.029209928587079048, -0.04869680851697922, 0.01635807752609253, -0.013975921086966991, 0.02993103303015232, -0.02186085842549801, 0.027337562292814255, 0.06173807755112648, -0.05552144721150398, 0.11173667758703232, -0.002850713673979044, 0.0067396159283816814, -0.014453276060521603, 0.03404010832309723, 0.06328174471855164, 0.09785991162061691, 0.016026383265852928, 0.02463620714843273, 0.010196371003985405, 0.03231675177812576, 0.03482783958315849, 0.012972479686141014, 0.06374970823526382, -0.12293172627687454, -0.01703498885035515, -0.028862323611974716, -0.036092162132263184, -0.0514722540974617, -0.11512449383735657, -0.012429235503077507, -0.08940501511096954, 0.06870079040527344, 0.026553628966212273, -0.03257280960679054, 0.046524085104465485, 0.00020684042829088867, 0.06025783717632294, -0.015267660841345787, 0.0010977181373164058, 0.005369286052882671, 0.03770275413990021, 0.023572636768221855, 0.0035807902459055185, -0.03384198620915413, -0.026205267757177353, 0.06975211203098297, 0.020543193444609642, -0.015171892009675503, 0.05312025547027588, 0.014551732689142227, 0.02318691834807396], \\"type\\": \\"float32\\", \\"shape\\": [384]}"^^<https://w3id.org/rdf-tensor/datatypes#NumericDataTensor>) AS ?dist) .\n} GROUP BY ?product ?vector ?dist\nORDER BY DESC(?dist)\nLIMIT 10\n', <QUERY_TYPE.INDEX: 'index'>: '\nPREFIX dt: <https://w3id.org/rdf-tensor/datatypes#>\nPREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#>\nPREFIX dtf: <https://w3id.org/rdf-tensor/functions#>\nPREFIX bsbmi: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>\nPREFIX bsbmv: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>\nPREFIX tensorIndex: <https://qlever.cs.uni-freiburg.de/tensorIndex/>\nSELECT DISTINCT ?product  ?vector ?dist\nWHERE {\nSERVICE tensorIndex: {\n       _:config tensorIndex:numNN 10 ;\n      tensorIndex:left ?query_vector ;\n      tensorIndex:bindDistance ?dist ;\n      tensorIndex:payload ?product ;\n      tensorIndex:searchK 1;\n      tensorIndex:algorithm tensorIndex:ivf;\n    # tensorIndex:experimentalRightCacheName "easy_index_bsbm" ;\n      tensorIndex:right ?vector .\n       {\n            {\n                SELECT DISTINCT ?product ?vector WHERE {\n                    ?product rdf:label_embedding ?vector .\n                    ?product bsbmv:productFeature ?feat .\n                } GROUP BY ?product ?vector\n            }\n        }\n    }\n    VALUES (?query_vector) { ("{\\"data\\": [0.001923849806189537, 0.059069667011499405, -0.06259278953075409, -0.008788925595581532, 0.08017760515213013, 0.0004897266626358032, 0.049011558294296265, -0.016156358644366264, -0.04537816718220711, 0.011929630301892757, -0.003551364177837968, -0.0034783161245286465, 0.023264417424798012, 0.02449001744389534, -0.023595571517944336, -0.073823943734169, 0.014226873405277729, -0.00022305997845251113, -0.03111756220459938, 0.07163400948047638, -0.04559392109513283, 0.044428009539842606, 0.0004388350062072277, -0.004044292028993368, 0.05173112079501152, 0.08436278998851776, -0.028667306527495384, -0.032494205981492996, 0.058949727565050125, -0.0051073553040623665, 0.09506019204854965, -0.029170090332627296, -0.07172352075576782, 0.036426812410354614, 0.01788988709449768, 0.07774496078491211, -0.01058284193277359, -0.02719942107796669, -0.014839782379567623, 0.004996407311409712, -0.05195301026105881, -0.01563340425491333, -0.0004883587826043367, 0.012572054751217365, -0.043422963470220566, -0.011021864600479603, -0.024199120700359344, -0.030226601287722588, 0.04542998597025871, -0.007276976015418768, 0.01397930271923542, 0.050883397459983826, -0.01848265342414379, 0.049168676137924194, -0.008279561065137386, 0.044504038989543915, 0.04745961353182793, 0.043078307062387466, -0.046442680060863495, 0.036845613270998, 0.10432934015989304, -0.015816830098628998, 0.10823524743318558, -0.028953377157449722, 0.04555060341954231, -0.030880587175488472, -0.051015835255384445, 0.05478580296039581, -0.0291702002286911, -0.005334345158189535, -0.06260965764522552, 0.034982938319444656, 0.026750046759843826, 0.04171916842460632, 0.03431631997227669, -0.07216819375753403, -0.00024255513562820852, -0.048893045634031296, 0.02389506623148918, 0.12748239934444427, -0.08703242987394333, 0.03412925824522972, 0.02240350842475891, 0.002564689377322793, -0.17344096302986145, 0.04103534668684006, -0.017823603004217148, -0.0076851267367601395, -0.09476081281900406, -0.07406330108642578, 0.08501428365707397, 0.04020910710096359, 0.08708695322275162, -0.026967616751790047, -0.060038503259420395, -0.003988019190728664, -0.02539210394024849, 0.022482113912701607, 0.060429759323596954, 0.037002742290496826, -0.0065333242528140545, 0.021862275898456573, 0.00022625424026045948, -0.033486779779195786, -0.07245824486017227, -0.1024286150932312, 0.049249906092882156, -0.009056593291461468, 0.007512359414249659, 0.0021412500645965338, -0.09075023233890533, 0.040666837245225906, -0.06107519939541817, -0.002982238307595253, -0.06842709332704544, 0.0025372530799359083, -0.01641230843961239, -0.043180201202631, 0.039085742086172104, -0.10427255183458328, 0.0473635196685791, -0.019185954704880714, 0.05296330899000168, 0.019953425973653793, 0.0329863503575325, 0.03303090110421181, 0.04857225716114044, 7.191068898027963e-35, -0.018325448036193848, -0.06909802556037903, 0.024108240380883217, 0.04407642409205437, 0.06294272840023041, 0.029094791039824486, 0.06375113874673843, 0.07381084561347961, 0.0368872731924057, 0.019980719313025475, -0.013145486824214458, -0.027676766738295555, -0.10194964706897736, -0.002321777166798711, -0.0032931924797594547, -0.02191285789012909, -0.09255401045084, 0.03210889920592308, 0.015278536826372147, -0.04234621301293373, 0.0064256093464791775, 0.04209345206618309, -0.019585780799388885, 0.03202011436223984, 0.037421416491270065, -0.018620574846863747, 0.019987355917692184, -0.013685979880392551, -0.03424428403377533, 0.012987463735044003, 0.04883616417646408, -0.0011513904901221395, -0.008845774456858635, 0.005870802327990532, -0.07762148231267929, -0.025999465957283974, -0.06829018890857697, 0.018836436793208122, -0.02234852872788906, -0.07037260383367538, 0.012542112730443478, 0.03438114747405052, 0.14274704456329346, 0.07548227161169052, 0.008455806411802769, -0.02049204707145691, 0.004560847766697407, -0.025547219440340996, -0.11879655718803406, 0.001291911699809134, -0.03331619128584862, 0.025502456352114677, -0.09485730528831482, 0.08408985286951065, -0.05816476047039032, -0.029875924810767174, -0.01281525194644928, -0.06466028094291687, 0.0453050322830677, 0.004283205606043339, 0.035003237426280975, 0.04375073313713074, 0.043108899146318436, -0.001907631172798574, 0.016851212829351425, -0.026979830116033554, 0.010974003002047539, 0.016453053802251816, 0.09936032444238663, 0.009172468446195126, 0.007693963125348091, -0.00969709176570177, 0.023047752678394318, -0.021144036203622818, 0.03724559023976326, -0.013058981858193874, -0.029100554063916206, 0.01229681633412838, -0.09894735366106033, -0.12643840909004211, 0.04589775577187538, -0.07361725717782974, 0.04434674605727196, 0.050329189747571945, -0.06559285521507263, -0.09371957182884216, 0.024369491264224052, -0.01520457398146391, -0.0038548363372683525, 0.027220020070672035, -0.031000541523098946, 0.015559685416519642, -0.006960012950003147, -0.041212767362594604, -0.08390278369188309, -4.97649344593706e-34, 0.05890499800443649, -0.06461971998214722, -0.07525855302810669, 0.058098528534173965, 0.06788986176252365, 0.019036881625652313, -0.007119014859199524, -0.043491482734680176, -0.017167028039693832, -0.04744131118059158, -0.04438185319304466, 0.0017611982766538858, 0.11509203165769577, 0.055401794612407684, -0.04163767397403717, 0.06279648095369339, -0.004321553744375706, -0.06458307802677155, 0.04710076004266739, 0.027388490736484528, -0.028406115248799324, -0.0031859995797276497, 0.01728656329214573, 0.03930680826306343, -0.042606621980667114, -0.03965207189321518, 0.050438474863767624, -0.05095212534070015, -0.009358619339764118, -0.005097959190607071, -0.042747560888528824, -0.09899874031543732, 0.046798769384622574, 0.06118430569767952, -0.029022959992289543, -0.11554227024316788, -0.011058848351240158, -0.036974892020225525, -0.08948592841625214, -0.014271756634116173, 0.013834885321557522, -0.01605868525803089, -0.04475671425461769, 0.03806497901678085, -0.05086902156472206, -0.06123126670718193, -0.08582713454961777, 0.018628671765327454, 0.10956262052059174, 0.03865630552172661, -0.005097296088933945, -0.024105655029416084, -0.012989535927772522, -0.07685093581676483, -0.00417094212025404, 0.089471735060215, -0.005915124900639057, 0.014249371364712715, -0.013326791115105152, 0.1283029317855835, -0.0087217316031456, 0.10300467163324356, 0.03298785537481308, -0.011241207830607891, 0.024034647271037102, 0.048094574362039566, 0.011020636186003685, -0.037912674248218536, -0.05348319187760353, 0.025995740666985512, 0.1147560179233551, 0.023856690153479576, 0.08506986498832703, 0.1052437573671341, 0.003146340372040868, -0.06395517289638519, 0.09612903743982315, -0.013588497415184975, 0.07226214557886124, 0.008729256689548492, -0.03723451867699623, -0.011913117952644825, 0.00031532489811070263, 0.007079592905938625, 0.03848397731781006, -0.09682920575141907, -0.014785494655370712, 0.002893038559705019, -0.06805280596017838, 0.0401400662958622, -0.022343454882502556, 0.08511822670698166, -0.13211962580680847, 0.03063001111149788, 0.0910293459892273, -1.2904515678258122e-08, -0.04676821827888489, -0.006705537438392639, 0.022972706705331802, -0.022980324923992157, -0.07330192625522614, -0.05493609607219696, 0.147051140666008, 0.07781931012868881, 0.032597970217466354, -0.04455342888832092, 0.011822628788650036, -0.0011622520396485925, -0.08087407797574997, -0.029209928587079048, -0.04869680851697922, 0.01635807752609253, -0.013975921086966991, 0.02993103303015232, -0.02186085842549801, 0.027337562292814255, 0.06173807755112648, -0.05552144721150398, 0.11173667758703232, -0.002850713673979044, 0.0067396159283816814, -0.014453276060521603, 0.03404010832309723, 0.06328174471855164, 0.09785991162061691, 0.016026383265852928, 0.02463620714843273, 0.010196371003985405, 0.03231675177812576, 0.03482783958315849, 0.012972479686141014, 0.06374970823526382, -0.12293172627687454, -0.01703498885035515, -0.028862323611974716, -0.036092162132263184, -0.0514722540974617, -0.11512449383735657, -0.012429235503077507, -0.08940501511096954, 0.06870079040527344, 0.026553628966212273, -0.03257280960679054, 0.046524085104465485, 0.00020684042829088867, 0.06025783717632294, -0.015267660841345787, 0.0010977181373164058, 0.005369286052882671, 0.03770275413990021, 0.023572636768221855, 0.0035807902459055185, -0.03384198620915413, -0.026205267757177353, 0.06975211203098297, 0.020543193444609642, -0.015171892009675503, 0.05312025547027588, 0.014551732689142227, 0.02318691834807396], \\"type\\": \\"float32\\", \\"shape\\": [384]}"^^<https://w3id.org/rdf-tensor/datatypes#NumericDataTensor>) }\n} ORDER BY DESC(?dist)\nLIMIT 10\n', <QUERY_TYPE.TWO_STAGE: 'two_stage'>: '\n            PREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#>\n            PREFIX dtf: <https://w3id.org/rdf-tensor/functions#>\n            PREFIX bsbmi: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>\n            SELECT DISTINCT ?product  ?vector ?feat ?dist\n            WHERE {\n                ?productA bsbmv:productFeature ?feat .\n                ?product rdf:label_embedding ?vector .\n                VALUES (?some_emb) { ("{\\"data\\": [0.001923849806189537, 0.059069667011499405, -0.06259278953075409, -0.008788925595581532, 0.08017760515213013, 0.0004897266626358032, 0.049011558294296265, -0.016156358644366264, -0.04537816718220711, 0.011929630301892757, -0.003551364177837968, -0.0034783161245286465, 0.023264417424798012, 0.02449001744389534, -0.023595571517944336, -0.073823943734169, 0.014226873405277729, -0.00022305997845251113, -0.03111756220459938, 0.07163400948047638, -0.04559392109513283, 0.044428009539842606, 0.0004388350062072277, -0.004044292028993368, 

In [ ]:
from typing import Literal


def get_query_index_variations(
    embedding: DataTensor,
    numNN: int = 1,
    searchK: int = 16,
    mode: Literal["naive", "hsnw", "ivf"] = "naive",
) -> str:
    args = f"""
    _:config tensorIndex:numNN {numNN} ;
    tensorIndex:left ?query_vector ;
    tensorIndex:bindDistance ?dist ;
    tensorIndex:payload ?product ;
    tensorIndex:algorithm tensorIndex:{mode} ;
    tensorIndex:distance tensorIndex:dot ;
    """
    if mode != "naive":
        args += f"""
        tensorIndex:experimentalRightCacheName "easy_index_{mode}_{searchK}" ;
        tensorIndex:searchK {searchK} ;
        """
    if mode == "ivf":
        args += """
        tensorIndex:kIVF 16 ;
        """
    return f"""
PREFIX dt: <https://w3id.org/rdf-tensor/datatypes#>
PREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dtf: <https://w3id.org/rdf-tensor/functions#>
PREFIX bsbmi: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>
PREFIX bsbmv: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX tensorIndex: <https://qlever.cs.uni-freiburg.de/tensorIndex/>
SELECT DISTINCT ?product  ?vector ?dist
WHERE {{
SERVICE tensorIndex: {{
        {args}
    tensorIndex:right ?vector .
       {{
            {{
                SELECT DISTINCT ?product ?vector WHERE {{
                    ?product rdf:label_embedding ?vector .
                    ?product bsbmv:productFeature ?feat .
                }} GROUP BY ?product ?vector
            }}
        }}
    }}
    VALUES (?query_vector) {{ ({embedding.to_literal().n3()}) }}
}} ORDER BY DESC(?dist)
LIMIT 16
"""

In [ ]:
# 1. get reference results using naive
k = 16
with db:
    query = get_query_index_variations(test_tensor, numNN=k, mode="naive")
    print("Running naive query...")
    results_naive = db.query(query)
results_naive

2026-04-28 16:13:25,265 - INFO - Logging QLever setup to scratch/bsbm/bsbm_4/db/test-with-tidx/test-with-tidx_run.log
2026-04-28 16:13:25,266 - INFO - Loading dataset into QLever server from data/bsbm_4/dataset.nt
2026-04-28 16:13:25,267 - WARNING - DB directory scratch/bsbm/bsbm_4/db/test-with-tidx already exists!
2026-04-28 16:13:25,267 - INFO - Stopping server!
2026-04-28 16:13:25,288 - ERROR - Command failed with return code 1
2026-04-28 16:13:25,288 - INFO - Starting QLever server on port 26043
2026-04-28 16:13:25,288 - INFO - Running command: qlever-server -i test-with-tidx --port 26043 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-28 16:13:25,298 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:26043/test-with-tidx/sparql)
2026-04-28 16:13:26,310 - INFO - Server is up and responding to queries
2026-04-28 16:13:26,382 - INFO - Stopping server!
2026-04-28 16:13:26,460 - ERROR - Command failed with return code 1

Running naive query...

,product,vector,dist
0,bsbmi:dataFromProducer42/Product1985,"{""data"": [-0.053947802633047104, 0.09995079785...",0.4656711816788
1,bsbmi:dataFromProducer204/Product9871,"{""data"": [-0.019114747643470764, 0.04421398043...",0.4265947937965
2,bsbmi:dataFromProducer126/Product6035,"{""data"": [-0.027103513479232788, 0.09437111020...",0.4230341911316
3,bsbmi:dataFromProducer90/Product4341,"{""data"": [-0.046234358102083206, 0.02935838326...",0.4177694320679
4,bsbmi:dataFromProducer107/Product5062,"{""data"": [-0.03348818048834801, 0.051626261323...",0.4087207317352
5,bsbmi:dataFromProducer58/Product2673,"{""data"": [-0.01993369869887829, 0.017058538272...",0.4059612154961
6,bsbmi:dataFromProducer103/Product4854,"{""data"": [0.03547070920467377, 0.0046439259313...",0.3998067677021
7,bsbmi:dataFromProducer77/Product3653,"{""data"": [-0.05063876882195473, 0.055860601365...",0.3955109715462
8,bsbmi:dataFromProducer189/Product9168,"{""data"": [-0.02634534053504467, 0.026425572112...",0.391575217247
9,bsbmi:dataFromProducer37/Product1658,"{""data"": [-0.10466377437114716, 0.054606124758...",0.3833258748055
10,bsbmi:dataFromProducer9/Product425,"{""data"": [0.019744349643588066, 0.105314098298...",0.3831891417503
11,bsbmi:dataFromProducer112/Product5287,"{""data"": [-0.10725384205579758, 0.021497599780...",0.3792371153831
12,bsbmi:dataFromProducer4/Product142,"{""data"": [0.021707145497202873, 0.062268067151...",0.3695688247681
13,bsbmi:dataFromProducer7/Product324,"{""data"": [-0.003105619689449668, 0.11045578122...",0.365286886692
14,bsbmi:dataFromProducer105/Product4968,"{""data"": [-0.011815586127340794, 0.02802155353...",0.3617807030678
15,bsbmi:dataFromProducer59/Product2729,"{""data"": [0.04540884122252464, 0.0299678612500...",0.3601063191891

In [ ]:
# 2. get results using ivf
with db:
    query = get_query_index_variations(test_tensor, numNN=k, mode="ivf", searchK=k)
    print("Running ivf query...")
    results_idx = db.query(query)
results_idx

2026-04-28 16:13:26,517 - INFO - Logging QLever setup to scratch/bsbm/bsbm_4/db/test-with-tidx/test-with-tidx_run.log
2026-04-28 16:13:26,517 - INFO - Loading dataset into QLever server from data/bsbm_4/dataset.nt
2026-04-28 16:13:26,518 - WARNING - DB directory scratch/bsbm/bsbm_4/db/test-with-tidx already exists!
2026-04-28 16:13:26,518 - INFO - Stopping server!
2026-04-28 16:13:26,593 - ERROR - Command failed with return code 1
2026-04-28 16:13:26,593 - INFO - Starting QLever server on port 26043
2026-04-28 16:13:26,594 - INFO - Running command: qlever-server -i test-with-tidx --port 26043 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-28 16:13:26,595 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:26043/test-with-tidx/sparql)
2026-04-28 16:13:27,606 - INFO - Server is up and responding to queries
2026-04-28 16:13:27,787 - INFO - Stopping server!

Running ivf query...

2026-04-28 16:13:27,870 - ERROR - Command failed with return code 1

,product,vector,dist
0,bsbmi:dataFromProducer42/Product1985,"{""data"": [-0.053947802633047104, 0.09995079785...",0.4656711220741
1,bsbmi:dataFromProducer204/Product9871,"{""data"": [-0.019114747643470764, 0.04421398043...",0.4265947937965
2,bsbmi:dataFromProducer126/Product6035,"{""data"": [-0.027103513479232788, 0.09437111020...",0.4230341911316
3,bsbmi:dataFromProducer90/Product4341,"{""data"": [-0.046234358102083206, 0.02935838326...",0.4177694320679
4,bsbmi:dataFromProducer107/Product5062,"{""data"": [-0.03348818048834801, 0.051626261323...",0.4087207317352
5,bsbmi:dataFromProducer58/Product2673,"{""data"": [-0.01993369869887829, 0.017058538272...",0.4059612154961
6,bsbmi:dataFromProducer103/Product4854,"{""data"": [0.03547070920467377, 0.0046439259313...",0.3998067378998
7,bsbmi:dataFromProducer77/Product3653,"{""data"": [-0.05063876882195473, 0.055860601365...",0.3955109715462
8,bsbmi:dataFromProducer189/Product9168,"{""data"": [-0.02634534053504467, 0.026425572112...",0.3915751874447
9,bsbmi:dataFromProducer37/Product1658,"{""data"": [-0.10466377437114716, 0.054606124758...",0.3833258748055
10,bsbmi:dataFromProducer9/Product425,"{""data"": [0.019744349643588066, 0.105314098298...",0.3831890821457
11,bsbmi:dataFromProducer112/Product5287,"{""data"": [-0.10725384205579758, 0.021497599780...",0.3792370557785
12,bsbmi:dataFromProducer4/Product142,"{""data"": [0.021707145497202873, 0.062268067151...",0.3695688247681
13,bsbmi:dataFromProducer7/Product324,"{""data"": [-0.003105619689449668, 0.11045578122...",0.3652869164944
14,bsbmi:dataFromProducer105/Product4968,"{""data"": [-0.011815586127340794, 0.02802155353...",0.3617807030678
15,bsbmi:dataFromProducer59/Product2729,"{""data"": [0.04540884122252464, 0.0299678612500...",0.3601063489914

In [ ]:
import time

from utils.helpers import recall_at_k, precision_at_k, ndcgscore_query

In [ ]:
recall_at_k(results_idx, results_naive, k=16)

1.0

In [ ]:
out_dir = Path("./scratch") / "results" / "bsbm" / "index_tests"
out_dir.mkdir(parents=True, exist_ok=True)

In [ ]:


with db:
    runs = 256
    search_ks = {
        "hnsw": np.arange(0, 33, 4).tolist(),
        "ivf": np.arange(0, 17, 2).tolist(),
    }
    for m, search_k_list in search_ks.items():
        search_ks[m] = [1] + search_k_list[1:]

    modes = ["hnsw", "ivf"]
    total = runs * len(modes) * sum(len(s) for s in search_ks.values())
    g = tqdm.tqdm(total=total, desc="Running index queries")

    def run_index_query(
        test_tensor: DataTensor, mode: Literal["naive", "hnsw", "ivf"], search_k: int
    ):
        query = get_query_index_variations(
            test_tensor, numNN=k, searchK=search_k, mode=mode
        )
        return db.raw_query(query)

    timing_results = []
    for mode in modes:
        for search_k in search_ks[mode]:
            run_index_query(test_tensor, mode, search_k)  # warmup
            for run in range(runs):
                noised_tensor = DataTensor.from_numpy(
                    test_tensor.data + np.random.normal(scale=1, size=test_tensor.shape)
                )
                reference_results = db.q_to_df_values(
                    run_index_query(noised_tensor, "naive", search_k)
                )
                g.update(1)
                g.set_description(
                    f"Running {mode} query, run {run + 1}/{runs}, searchK={search_k}"
                )
                result = {}
                start = time.time()
                resp = run_index_query(noised_tensor, mode, search_k)
                end = time.time()
                results_df = db.q_to_df_values(resp)

                result["mode"] = mode
                result["run"] = run
                result["time"] = end - start
                result["searchK"] = search_k
                result["ndcg_score"] = ndcgscore_query(
                    results_df, reference_results, k=k
                )
                result["recall_score"] = recall_at_k(results_df, reference_results, k=k)
                timing_results.append(result)
    g.close()

2026-04-28 16:13:28,085 - INFO - Logging QLever setup to scratch/bsbm/bsbm_4/db/test-with-tidx/test-with-tidx_run.log
2026-04-28 16:13:28,086 - INFO - Loading dataset into QLever server from data/bsbm_4/dataset.nt
2026-04-28 16:13:28,086 - WARNING - DB directory scratch/bsbm/bsbm_4/db/test-with-tidx already exists!
2026-04-28 16:13:28,087 - INFO - Stopping server!
2026-04-28 16:13:28,164 - ERROR - Command failed with return code 1
2026-04-28 16:13:28,164 - INFO - Starting QLever server on port 26043
2026-04-28 16:13:28,165 - INFO - Running command: qlever-server -i test-with-tidx --port 26043 -k 0 -m 32G --tensor-search-max-num-threads 4
2026-04-28 16:13:28,166 - INFO - Waiting for server to start..., got error: <urlopen error [Errno 111] Connection refused> (http://localhost:26043/test-with-tidx/sparql)
2026-04-28 16:13:29,178 - INFO - Server is up and responding to queries
Running ivf query, run 256/256, searchK=16:  50%|█████     | 4608/9216 [08:10<08:10,  9.40it/s]
2026-04-28 16:21:39,266 - INFO - Stopping server!
2026-04-28 16:21:39,516 - ERROR - Command failed with return code 1

In [ ]:
timing_results_df = pd.DataFrame(timing_results)
timing_results_df.to_csv(out_dir / "index_query_timings.csv", index=False)

In [ ]:
noised_tensor

DataTensor(data=[-0.29541585659025676, 1.7479325210583716, -0.1251014632094179, 1.235369663954073, 0.43863498019171754, 1.9786149169237732, 0.9071609802115765, 1.8952518483350937, 0.8151660685294816, 0.01962228867984513, 1.406735179291108, -0.8958258495698949, -1.4180430310850831, -0.8247317383146132, 0.7575070498494731, 0.05743172636420091, -0.8236178967541068, -1.1218212258093179, -0.6821265882603661, -1.5119489986142811, -0.31409410389051684, 0.02162648407712839, -0.050259223087955295, 0.47801894013951346, 1.1367245420213057, 0.20770097127577786, -2.664950895393883, -0.6811459519058084, 0.31745908784929333, -0.42571504703414903, -0.29694626619931347, 1.66616699524499, -0.7435331743099688, 0.8758314543783867, -0.9234127845397713, -1.4620426635880057, -0.7217010687832609, 1.0447647067142734, -2.3030090406137425, 0.34879685741390676, -0.07691368846828889, -0.6281559162054275, 1.7467379073739289, -0.08185912897520504, 2.1270793219101742, 1.308618033577409, -0.6084968351851459, -1.0410497582561136, 0.6905394644574515, 0.9750715497766106, 2.186640935040106, -0.17921844047562485, 0.9195073061273591, 0.12662311953170535, -0.6414215494161783, 0.05579008689544453, -0.4636086668003748, 1.4380537235612183, -1.4083727118564857, -0.705322410606688, 1.3880784170744036, 1.9085332911834572, 0.023734857900817405, -1.33052306649402, 1.0553142352479212, 0.5215492996118024, -0.07658312351033236, -0.535343626368452, -0.07735754938965046, 0.8260496324249492, -1.6565001367637855, -1.43982560681122, -0.22472113448450542, -1.0063175096635169, 1.4439054657739698, 0.08260477153819298, 0.5185536482903021, -0.695202243341085, 0.09659032456685503, 1.4637659559291067, 0.35723690538096997, -0.31512099472201155, 0.5686054598737674, -0.572416691844959, 0.24203835681074243, -0.65315487452156, 1.386452026577146, 1.3031268036495507, 1.3185363604475255, -0.14429595324773176, 0.47479567838943104, -0.13989349416810445, 0.17558428337361254, 1.5010042200408527, 0.33681098550721106, 0.9904894435729095, -0.6230178018724183, 0.12810007365950477, -0.4101339586635361, 0.41906036435878147, 1.012625273953396, -0.43463698572626963, 1.4226290381696245, 1.094905013295, -0.9237285796829633, 0.2454728284570475, 0.5313704745735228, 0.9861085371295013, 0.20358374971745827, 1.1823431988550355, -1.8633899151196534, 0.4154288418706231, -1.8808255162476042, -0.6586714807702897, 0.018244753444754805, 0.9744936314085857, -0.7518368158396251, -0.04901272391031709, -2.459832734972635, 0.8409269659502986, -0.24031245800293527, 1.0405188217688666, 2.600208409474188, 0.19262384671448085, -1.7241230623348247, -0.7350192990038944, 0.7493203345224182, -0.8931921870836667, 1.6269954314020219, 0.46600751832017984, -0.6108549836045679, 0.6419842456278175, -0.16715668209235396, 1.512432465064239, -0.015614108053034467, -1.32248990135323, 1.0711833103449608, -0.12293970230859186, 0.2948468550473839, 1.1829692690757427, 1.3169004600419145, -1.6450290839528003, -0.25013766595398695, 0.5419408425952963, -2.41705237569854, 1.266070874712797, 0.266496012082355, 0.1857723416410836, 0.3036520617071897, 0.5685087553210403, 0.6506265308465286, -0.7241302288731652, -2.4297017529982794, 0.3345194450688422, 1.9302286291516402, 1.0147481443288464, -0.9041121860318397, 0.3994987144593762, 2.57618526581796, 0.6354478740863662, 0.15948252180114864, 2.4504864674367726, 1.5533812139073235, 0.6517431103879667, 0.5849873180044957, -0.2905080219789847, 0.1996110182595154, 1.0818150499582702, -0.9591852291040949, -1.8490024823285767, 1.3973648089860213, -1.215084508559122, -0.05911205663031088, -2.119116431501055, -0.3893435675288616, 1.4538568870391542, 0.2372337387118315, 2.3453198457434845, 1.6552054334635478, -0.3481771060525204, -0.2598638966614644, -1.2029809717746054, 0.04368092670875437, -0.2960798625305874, 0.17787102864531867, 0.1176610720142936, -0.9697778050279189, 1.499016539456771, 1.9622354134827353, 1.4521114724614999, 0.36965072638016083, -0.2571359080011304, -1.2054917596958612, 0.29140087610306353, 0.7903596104501394, 0.9234543455847399, 0.6817060872777455, -0.5369584864349464, 0.9176961409464591, 0.7802056685525346, 0.395468569708888, -0.9126591104738083, -0.9967846927839039, 0.7653855212952675, 0.21072539895604936, -0.11810414115512194, 1.5893709309790096, -0.024297103826546734, -0.7387860565886766, -0.5248165141386447, -0.4937727805374674, 0.6750922023445081, 0.42082917969908035, 0.9140637147067479, -1.8722917215115145, -1.6421203764911247, 0.7606844709235258, 1.1044826492081252, -0.7101933243074247, 0.6785621739248532, -0.522288068476881, 0.5029462831028886, -0.045584004246083776, -0.9841162918510742, -1.1721552459436912, 1.5307863357123446, 0.261856180354074, 1.0569963169151197, -0.026522852748976172, 2.040315587005678, -0.3878413902899604, -0.5642026027405372, 0.09178484436768479, -0.0050225439609403386, -1.1434114556149126, -0.32972865808622737, 1.3804848696488925, -1.1200060884803242, 0.315479619112658, -0.9652178875190822, -0.3202921343733835, -1.8086688225583474, 0.9902972656170831, 1.5484335204560318, -0.4809367656992941, -1.5848483892434517, -1.5719665757637642, 0.3611965313719616, 0.5320333954144454, 0.06190620253149508, -0.46378259382027986, 1.0369982188685671, 0.6234662969762816, 0.2805348672409971, 2.0349203897534127, -1.082615414436164, 1.3619422944503423, 0.6353545077492094, 1.393201030016794, -0.33752864909211455, -1.2017903390607807, 1.1113465402606657, -2.0369707864916125, 0.22787481149035746, -0.23963024584800968, -0.05575540783763612, -2.11235699973821, -0.12641699588054603, 1.1678441842171663, -0.07339236652219416, -0.9280279080853839, 0.26022589445540684, 0.3637431724988484, 0.31231032231463335, 1.9836189635359731, -0.424426703858616, 1.5215674447248488, 0.39213028116966414, -0.07265091563696487, 0.019944389429192314, -0.01018896572381688, -0.4163238097830107, -1.1761679994042415, -1.3373124801445586, -1.0536190244540513, -0.532110587235259, -0.46472011025440135, -0.22137121694854842, 1.1010928686164023, -1.3774111218544391, -0.03600943015756163, -0.7248863420773954, -0.19027987948132966, -0.6407130606583707, 1.4946954889928132, -0.7457088275121347, 0.1750360722218121, 1.9424635837658313, -0.11200785753944106, 0.25448323435967674, 1.8289266459985196, -0.12923556421064075, -0.8100355481346437, -0.4811524860475932, 0.7476366755225393, 1.5395544216841393, -0.6847433120151766, -0.7341945458513071, -2.5878664947815513, 0.3014071710795302, 0.9305267256749483, 0.9601796797440839, -0.1901525091942534, -0.6320270568822769, 1.2490992063829252, 0.04797182860289442, -0.2659776061381194, -0.16640223128044532, -0.5610166328639324, 0.9198691938286857, -1.6725444489471988, 0.33414598179994476, 1.733082244103036, 1.9530664283003314, -0.30647473343997284, 0.059452669035001876, 0.44488825861164055, 0.7010836339038972, -1.5187091700577975, -0.011241272123565495, 0.3280048802725249, 0.9830023634274883, -0.9103832975204953, -0.320654163219241, -0.007253795187250216, -0.22304707526737128, -0.11857430363217673, 0.2805474339840305, 0.5686589625592035, 0.7752906094264458, 0.4536084823335331, 1.4063072678498827, 0.46040538072710396, -2.0859983553626864, -0.12551914988233992, -0.7776057930236211, 0.6563203588786662, 0.8721672423576761, 2.3920995267868603, 2.300385521081627, -0.31133135316962907, -0.020402460279387705, -1.6659862562260974, 0.2082423813938439, -0.3919437599099276, -0.06927098874668738, -0.37473640237871825, 1.4893924052335608, 0.7351938651192484, 0.4686055364898155, -0.5212383394118378, -1.9463412187386941, -1.6110223263058134, -0.9989339049034651, -0.6342484010331645, -0.9606608283538469, 0.5684010006710174, -2.278111574128721, -1.5695921688755547, 1.336170414688103, 0.8347661312142832, 0.18648684902132912, -0.26036063176040936, -2.1901914515950875, -0.1988205675542433, -0.3889680286535773, 1.0059211874410086, -1.107160959999683, -0.6288832065632148, 1.201978837319021, 1.4636516421553292, -0.3520288180901906, 2.3061276813906537, 0.8390697056159263], type='float64', shape=(384,))